(() => {
  const T=(name,structureKey,aliases,why,imageAnchor,imageHint,q,options,whyQ)=>({name,structureKey,aliases,why,imageAnchor,imageHint,quiz:{q,options,correct:0,why:whyQ}});
  const topics={
    conducto_mandibular:T('Conducto mandibular','conducto_mandibular',['conducto mandibular'],'Conecta anatomía ósea, paquete neurovascular, panorámica y CBCT.','cbctAnatomyTrainer','Usá primero Mandíbula sagital y después Mandíbula axial/coronal.','¿Qué estructura principal recorre el conducto mandibular?',['Paquete neurovascular alveolar inferior','Nervio lingual','Arteria facial'],'El conducto aloja el nervio alveolar inferior y vasos acompañantes.'),
    foramen_mentoniano:T('Foramen mentoniano','foramen_mentoniano',['foramen mentoniano'],'Es una referencia clave en anestesia, cirugía, implantología e interpretación radiográfica.','realRadiographCase','Comparalo en panorámica y después confirmá continuidad con el conducto en CBCT.','¿Con qué trayecto óseo se continúa el foramen mentoniano?',['Conducto mandibular','Conducto infraorbitario','Meato acústico externo'],'Es una salida anterior del sistema del conducto mandibular.'),
    seno_maxilar:T('Seno maxilar','seno_maxilar',['seno maxilar'],'Integra maxilar posterior, raíces dentarias, panorámica y cortes CBCT.','cbctAnatomyTrainer','Abrí Maxilar coronal y relacioná piso sinusal con raíces posteriores.','¿Qué relación es especialmente importante en Odontología?',['Piso del seno con raíces posteriores superiores','Techo del seno con incisivos inferiores','Pared medial con cóndilo'],'La proximidad entre piso sinusal y dientes posteriores superiores es clínicamente relevante.'),
    cortical_vestibular:T('Cortical vestibular','mandibula',['cortical vestibular'],'Ayuda a construir orientación bucolingual y espesor óseo en CBCT.','cbctAnatomyTrainer','Comparala con la cortical lingual en cortes axial y coronal.','La cortical vestibular corresponde a…',['La cortical externa hacia el vestíbulo','La cortical interna hacia la lengua','El techo del conducto'],'Vestibular indica el lado externo orientado hacia el vestíbulo oral.'),
    cortical_lingual:T('Cortical lingual','mandibula',['cortical lingual'],'Es indispensable para interpretar posición bucolingual del conducto y límites mandibulares.','cbctAnatomyTrainer','Buscala en el mismo corte que la vestibular y compará ambas corticales.','La cortical lingual se orienta principalmente hacia…',['La lengua','El vestíbulo','La ATM'],'Lingual describe la cortical interna orientada hacia la lengua.'),
    raiz_molar:T('Raíz de molar','maxilar',['raíz de molar','raiz de molar'],'Permite relacionar dentición, seno maxilar y lectura multiplanar.','cbctAnatomyTrainer','Usá Maxilar coronal para seguir raíz y piso sinusal.','En molares superiores, ¿qué relación conviene evaluar en CBCT?',['Raíces con el piso del seno maxilar','Raíces con el foramen mentoniano','Raíces con el cóndilo'],'Las raíces posteriores superiores pueden estar muy próximas al piso del seno.'),
    condilo_mandibular:T('Cóndilo mandibular','condilo_mandibular',['cóndilo mandibular','condilo mandibular'],'Integra anatomía mandibular, ATM, panorámica y orientación tridimensional.','realRadiographCase','Compará ambos cóndilos en panorámica y luego volvé al 3D.','¿Con qué hueso se articula el cóndilo mandibular?',['Temporal','Esfenoides','Maxilar'],'El cóndilo forma la ATM con el temporal, interpuesto el disco.'),
    coronoides_mandibular:T('Apófisis coronoides','coronoides_mandibular',['apófisis coronoides','apofisis coronoides'],'Refuerza la orientación de la rama y su relación con el temporal.','realRadiographCase','Diferenciala del cóndilo usando la escotadura mandibular.','¿Qué músculo se inserta de forma importante en la coronoides?',['Temporal','Buccinador','Digástrico'],'La apófisis coronoides recibe una inserción principal del músculo temporal.'),
    mandibula:T('Mandíbula','mandibula',['mandíbula','mandibula'],'Es el eje para entender conducto mandibular, ATM, dentición inferior y anestesia.','cbctAnatomyTrainer','Relacioná cuerpo, rama y conducto en 3D y cortes CBCT.','¿Qué característica distingue a la mandíbula?',['Es el principal hueso móvil del cráneo','Forma el techo orbitario','Contiene el seno maxilar'],'La mandíbula es el principal hueso móvil y sostiene la arcada inferior.'),
    maxilar:T('Maxilar','maxilar',['maxilar'],'Conecta arcada superior, seno maxilar, órbita y región infraorbitaria.','cbctAnatomyTrainer','Usá el corte coronal del maxilar y volvé al 3D.','¿Qué cavidad neumática se encuentra dentro del maxilar?',['Seno maxilar','Seno esfenoidal','Celdillas mastoideas'],'El seno maxilar ocupa gran parte del cuerpo del maxilar.'),
    esfenoides:T('Esfenoides','esfenoides',['esfenoides'],'Organiza relaciones profundas de base craneal con V2, V3 y región pterigopalatina.',null,'Estudialo desde vista inferior y relacioná alas y procesos pterigoideos.','¿Qué combinación es correcta?',['Foramen redondo = V2; oval = V3','Redondo = V3; oval = V2','Oval = nervio facial'],'La relación clásica útil es redondo–V2 y oval–V3.'),
    temporal_hueso:T('Hueso temporal','temporal',['temporal','hueso temporal'],'Es esencial para comprender ATM, base lateral del cráneo y relaciones preauriculares.',null,'Ubicá fosa mandibular, meato acústico y mastoides.','¿Qué estructura mandibular se articula con el temporal?',['Cóndilo mandibular','Coronoides','Foramen mentoniano'],'La cabeza condilar participa en la ATM con el temporal.'),
    cigomatico:T('Cigomático','cigomatico',['cigomático','cigomatico'],'Refuerza orientación orbitofacial y arco cigomático.',null,'Seguí el arco cigomático hacia temporal y maxilar.','¿En qué región contribuye el cigomático?',['Reborde orbitario lateral y mejilla','Tabique nasal posterior','Foramen mandibular'],'El cigomático forma la prominencia malar y parte de la órbita.'),
    foramen_mandibular:T('Foramen mandibular','foramen_mandibular',['foramen mandibular'],'Es una referencia esencial para anestesia troncular y entrada del paquete alveolar inferior.','cbctAnatomyTrainer','Relacioná cara medial de la rama, entrada del conducto y trayecto hacia anterior.','¿Qué ingresa por el foramen mandibular?',['Paquete neurovascular alveolar inferior','Nervio infraorbitario','Arteria facial'],'Por allí ingresan nervio y vasos alveolares inferiores.'),
    foramen_oval:T('Foramen oval','esfenoides',['foramen oval'],'Relaciona base craneal con la salida de V3 y la fosa infratemporal.',null,'Ubicalo conceptualmente en el ala mayor del esfenoides y comparalo con redondo y espinoso.','¿Qué rama del trigémino atraviesa principalmente el foramen oval?',['V3','V2','V1'],'El nervio mandibular, V3, atraviesa principalmente el foramen oval.'),
    foramen_redondo:T('Foramen redondo','esfenoides',['foramen redondo'],'Es la referencia ósea clásica para seguir V2 hacia la región pterigopalatina.',null,'Comparalo con foramen oval y el trayecto de V2.','¿Qué rama atraviesa el foramen redondo?',['V2','V3','Nervio facial'],'El nervio maxilar, V2, atraviesa el foramen redondo.'),
    alveolar_inferior:T('Nervio alveolar inferior','foramen_mandibular',['nervio alveolar inferior'],'Une V3, anestesia mandibular, conducto y sensibilidad dentaria inferior.','cbctAnatomyTrainer','Seguí foramen mandibular → conducto → región mentoniana.','¿Por dónde entra a la mandíbula?',['Foramen mandibular','Foramen mentoniano','Foramen infraorbitario'],'El nervio entra por el foramen mandibular.'),
    nervio_mentoniano:T('Nervio mentoniano','foramen_mentoniano',['nervio mentoniano'],'Conecta el trayecto alveolar inferior con sensibilidad de mentón y labio inferior.','realRadiographCase','Relacioná foramen mentoniano con el final anterior del conducto.','¿De qué nervio deriva?',['Nervio alveolar inferior','Nervio lingual','Nervio infraorbitario'],'Es una rama terminal del alveolar inferior.'),
    nervio_lingual:T('Nervio lingual','mandibula',['nervio lingual'],'Es importante por su cercanía a la región lingual mandibular y cirugía de terceros molares.',null,'Comparalo con el nervio alveolar inferior: uno discurre en tejidos blandos y el otro entra al conducto.','¿Cuál afirmación es correcta?',['No recorre el conducto mandibular','Sale por el foramen mentoniano','Atraviesa el foramen redondo'],'El nervio lingual no viaja dentro del conducto mandibular.'),
    v2:T('V2 · nervio maxilar','maxilar',['v2','v2 · nervio maxilar'],'Integra foramen redondo, región pterigopalatina, infraorbitario y territorio maxilar.',null,'Relacioná esfenoides, maxilar y foramen infraorbitario.','¿Por qué foramen craneal pasa V2?',['Foramen redondo','Foramen oval','Foramen espinoso'],'V2 atraviesa el foramen redondo.'),
    atm:T('ATM','condilo_mandibular',['atm'],'Integra cóndilo, temporal, disco y biomecánica mandibular.',null,'Activá la capa ATM y observá la demostración de movimiento.','¿Qué estructura se interpone entre cóndilo y temporal?',['Disco articular','Nervio lingual','Seno maxilar'],'El disco articular participa en la relación entre ambas superficies.'),
    masetero:T('Masetero','angulo_mandibular',['masetero'],'Relaciona arco cigomático, rama/ángulo mandibular y elevación de la mandíbula.',null,'Activá músculos y observá su dirección de fibras.','¿Cuál es una función principal del masetero?',['Elevar la mandíbula','Transmitir V2','Abrir el seno maxilar'],'El masetero es un potente elevador mandibular.'),
    pterigoideo_lateral:T('Pterigoideo lateral','condilo_mandibular',['pterigoideo lateral'],'Ayuda a integrar fosa infratemporal, ATM y traslación mandibular.',null,'Activá músculos y después Movimiento ATM.','¿Con qué movimiento se relaciona especialmente?',['Protrusión/traslación mandibular','Cierre de sutura sagital','Descenso del paladar'],'Participa en protrusión y traslación condilar, entre otras acciones.')
  };

  const normalize=(s='')=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const topicForName=(name='')=>{const n=normalize(name);return Object.entries(topics).find(([,t])=>t.aliases.some(a=>normalize(a)===n))?.[0]||null;};
  const score=v=>v?.attempts?Math.round(v.correct*100/v.attempts):null;
  const progress=()=>window.SimulatorProgress?.get?.()||{byTarget:{},attempts:0};
  function rankedTopics(){const data=progress(),rows=[];for(const [name,v] of Object.entries(data.byTarget||{})){const key=topicForName(name);if(!key||!v?.attempts)continue;rows.push({key,attempts:v.attempts,correct:v.correct,score:score(v)});}rows.sort((a,b)=>a.score-b.score||b.attempts-a.attempts);const used=new Set();const ranked=rows.filter(r=>{if(used.has(r.key))return false;used.add(r.key);return true;});for(const fallback of ['conducto_mandibular','foramen_mentoniano','seno_maxilar','cortical_vestibular'])if(!used.has(fallback))ranked.push({key:fallback,attempts:0,correct:0,score:null});return ranked.slice(0,3);}

  function init(){
    if(document.getElementById('adaptiveStudy'))return true;
    const anchor=document.getElementById('progressDashboard')||document.getElementById('sourcePolicyPanel')||document.getElementById('cbctAnatomyTrainer');if(!anchor)return false;
    const section=document.createElement('section');section.id='adaptiveStudy';section.className='adaptiveStudy';section.innerHTML=`<div class="adaptiveHead"><div><span class="simEy">Repaso adaptativo · usa solo tu progreso local</span><h2>Tu próxima sesión de estudio</h2><p>El simulador prioriza automáticamente los temas con más errores. Si todavía no hay suficiente historial, propone una ruta diagnóstica corta.</p></div><span id="adaptiveStatus" class="adaptiveStatus">Plan listo</span></div><div id="adaptiveRecommendations" class="adaptiveRecommendations"></div><div id="adaptiveSession" class="adaptiveSession" hidden><div class="adaptiveSessionTop"><div><span class="simEy">Sesión guiada</span><h3 id="adaptiveTopic"></h3></div><b id="adaptiveStepCount">Paso 1 de 5</b></div><div class="adaptiveProgress"><span id="adaptiveBar"></span></div><div id="adaptiveStep" class="adaptiveStep"></div><div class="adaptiveActions"><button id="adaptiveBack" type="button">← Anterior</button><button id="adaptiveDo" type="button" class="primary">Abrir actividad</button><button id="adaptiveNext" type="button">Siguiente →</button></div></div>`;anchor.insertAdjacentElement('beforebegin',section);
    const recHost=section.querySelector('#adaptiveRecommendations'),session=section.querySelector('#adaptiveSession'),topicTitle=section.querySelector('#adaptiveTopic'),stepCount=section.querySelector('#adaptiveStepCount'),bar=section.querySelector('#adaptiveBar'),stepBox=section.querySelector('#adaptiveStep'),back=section.querySelector('#adaptiveBack'),next=section.querySelector('#adaptiveNext'),doBtn=section.querySelector('#adaptiveDo'),status=section.querySelector('#adaptiveStatus');let currentKey=null,stepIndex=0,quizAnswered=false;
    const stepsFor=key=>{const t=topics[key];return[{title:'1. Recordá la idea central',text:`Leé la ficha o referencia de ${t.name}, ubicá qué estructura la contiene, con qué se relaciona y por qué importa en Odontología.`,action:'3d'},{title:'2. Ubicala en el cráneo 3D',text:`Observá ${t.name} desde más de una vista y comprobá sus relaciones espaciales.`,action:'3d'},{title:'3. Pasá a imagen',text:t.imageHint,action:t.imageAnchor?'image':'3d'},{title:'4. Compará otra representación',text:'Volvé al 3D después de la imagen o esquema y explicá mentalmente cómo se relacionan ambas representaciones.',action:'3d'},{title:'5. Cerrá con una pregunta específica',text:'Respondé sin volver a mirar la ficha. El resultado recalcula tu prioridad de repaso.',action:'selfquiz'}];};
    function renderRecommendations(){const ranked=rankedTopics();status.textContent=progress().attempts?'Basado en tu rendimiento':'Ruta diagnóstica inicial';recHost.innerHTML=ranked.map((r,i)=>{const t=topics[r.key],result=r.score===null?'Todavía sin datos':`${r.score}% · ${r.correct}/${r.attempts}`;return `<article><span>${i===0?'Prioridad':'Alternativa'}</span><h3>${t.name}</h3><p>${t.why}</p><div><b>${result}</b><button type="button" data-start-topic="${r.key}">Empezar sesión</button></div></article>`;}).join('');recHost.querySelectorAll('[data-start-topic]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.startTopic)));}
    function start(key){currentKey=key;stepIndex=0;quizAnswered=false;session.hidden=false;topicTitle.textContent=topics[key].name;renderStep();session.scrollIntoView({behavior:'smooth',block:'center'});}
    function renderSelfQuiz(){const q=topics[currentKey].quiz;stepBox.innerHTML=`<h4>5. ${q.q}</h4><div class="adaptiveQuiz">${q.options.map((x,i)=>`<button type="button" data-answer="${i}">${x}</button>`).join('')}</div><p id="adaptiveFeedback">Elegí una opción.</p>`;stepBox.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(quizAnswered)return;quizAnswered=true;const chosen=Number(b.dataset.answer),ok=chosen===q.correct;stepBox.querySelectorAll('[data-answer]').forEach((x,i)=>{x.disabled=true;x.classList.toggle('correct',i===q.correct);x.classList.toggle('wrong',i===chosen&&!ok);});stepBox.querySelector('#adaptiveFeedback').textContent=`${ok?'✓ Correcto.':'✕ Revisalo.'} ${q.why}`;document.dispatchEvent(new CustomEvent('simulator:practice-result',{detail:{mode:'Repaso adaptativo',target:topics[currentKey].name,correct:ok}}));next.disabled=false;}));}
    function renderStep(){const s=stepsFor(currentKey)[stepIndex],steps=stepsFor(currentKey);stepCount.textContent=`Paso ${stepIndex+1} de ${steps.length}`;bar.style.width=`${((stepIndex+1)/steps.length)*100}%`;back.disabled=stepIndex===0;next.textContent=stepIndex===steps.length-1?'Terminar sesión':'Siguiente →';quizAnswered=false;next.disabled=s.action==='selfquiz';doBtn.hidden=s.action==='selfquiz';if(s.action==='selfquiz'){renderSelfQuiz();return;}stepBox.innerHTML=`<h4>${s.title}</h4><p>${s.text}</p>`;doBtn.textContent=s.action==='image'?'Abrir imágenes':'Mostrar en 3D';}
    function openActivity(){const t=topics[currentKey],s=stepsFor(currentKey)[stepIndex];if(s.action==='3d'){document.dispatchEvent(new CustomEvent('simulator:select',{detail:{key:t.structureKey,sourceName:'Repaso adaptativo'}}));document.getElementById('skullStage')?.scrollIntoView({behavior:'smooth',block:'center'});}else if(s.action==='image'){document.getElementById(t.imageAnchor)?.scrollIntoView({behavior:'smooth',block:'start'});}}
    back.addEventListener('click',()=>{if(stepIndex>0){stepIndex--;renderStep();}});next.addEventListener('click',()=>{const steps=stepsFor(currentKey);if(stepIndex<steps.length-1){stepIndex++;renderStep();}else{session.hidden=true;renderRecommendations();section.scrollIntoView({behavior:'smooth',block:'start'});}});doBtn.addEventListener('click',openActivity);document.addEventListener('simulator:progress-updated',renderRecommendations);window.addEventListener('focus',renderRecommendations);renderRecommendations();return true;
  }
  if(init())return;const o=new MutationObserver(()=>{if(init())o.disconnect();});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>o.disconnect(),10000);
})();