/* Nextfuture V4.1 — agenda, tareas, cierre diario y reporte mensual */
(function(){
 'use strict';
 const OPS=`${SB}/functions/v1/nextfuture-ops`, OPS_DASH=`${SB}/functions/v1/nextfuture-ops-dashboard`;
 let DATA=null,PREFILL={};
 const e=s=>typeof esc==='function'?esc(s):String(s??'');
 const dt=v=>v?new Date(v).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
 const donly=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit'}):'—';
 const iso=v=>v?new Date(v).toISOString():null;
 const labelType={pickup:'Retiro',delivery:'Entrega',dropoff:'Recepción',home_service:'Domicilio',other:'Otro'};
 const taskType={diagnosis:'Diagnóstico',repair:'Reparación',pickup:'Retiro',delivery:'Entrega',call:'Llamar',quote:'Presupuesto',part:'Repuesto',admin:'Administrativo',other:'Otro'};
 const pri={low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'};
 const codeOf=x=>x?.order?.order_code||'';
 function localInput(hours=1){const d=new Date(Date.now()+hours*3600000);d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0);const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
 async function loadOps(){if(!tok())return null;DATA=await call(OPS_DASH);return DATA}
 async function act(body){const r=await call(OPS,body);await loadOps();return r}
 function addButton(){const actions=document.querySelector('.topbar .actions');if(!actions||document.getElementById('todayBtn'))return;const b=document.createElement('button');b.className='btn primary';b.id='todayBtn';b.textContent='Hoy';actions.insertBefore(b,document.getElementById('mgmtBtn')||actions.firstChild);b.addEventListener('click',()=>openOps());}
 function activeTaskCount(){return (DATA?.tasks||[]).filter(t=>['pending','doing'].includes(t.status)).length}
 function renderRows(){
  const tv=DATA?.today_view||{},aps=tv.appointments||[],tasks=[...(tv.overdue_tasks||[]),...(tv.tasks||[]).filter(x=>!(tv.overdue_tasks||[]).some(o=>o.id===x.id))];
  const apHtml=aps.length?aps.map(a=>`<div class="nf41-row"><div><strong>${e(labelType[a.appointment_type]||a.appointment_type)} · ${dt(a.scheduled_at)}</strong><small>${a.order?e(a.order.order_code)+' · '+e(a.order.customer?.name||'Cliente'):'Sin orden'}${a.locality?' · '+e(a.locality):''}</small>${a.note?`<small>${e(a.note)}</small>`:''}</div><div class="nf41-actions"><button class="btn tiny" data-a="confirmed" data-id="${a.id}">Confirmar</button><button class="btn tiny" data-a="en_route" data-id="${a.id}">En camino</button><button class="btn tiny" data-a="done" data-id="${a.id}">Hecho</button><button class="btn tiny" data-a="cancelled" data-id="${a.id}">Cancelar</button></div></div>`).join(''):'<div class="empty">No hay retiros/entregas pendientes para hoy.</div>';
  const tHtml=tasks.length?tasks.map(t=>{const over=t.due_at&&DATA.today&&String(t.due_at).slice(0,10)<DATA.today;return `<div class="nf41-row ${over?'nf41-overdue':''} ${t.priority==='urgent'?'nf41-urgent':''}"><div><strong>${e(t.title)}</strong><small>${e(taskType[t.task_type]||t.task_type)} · ${e(pri[t.priority]||t.priority)}${t.due_at?' · '+dt(t.due_at):''}${t.order?' · '+e(t.order.order_code):''}</small>${t.note?`<small>${e(t.note)}</small>`:''}</div><div class="nf41-actions">${t.status!=='doing'?`<button class="btn tiny" data-t="doing" data-id="${t.id}">Iniciar</button>`:''}<button class="btn tiny" data-t="done" data-id="${t.id}">Hecho</button><button class="btn tiny" data-t="cancelled" data-id="${t.id}">Cancelar</button></div></div>`}).join(''):'<div class="empty">No hay tareas pendientes.</div>';
  return {apHtml,tHtml};
 }
 function openOps(prefill={}){
  PREFILL={...PREFILL,...prefill};
  if(!DATA){drawer('Hoy','<div class="box">Cargando operaciones…</div>');loadOps().then(()=>openOps(PREFILL)).catch(x=>drawer('Hoy',`<div class="box"><div class="msg error">${e(x.message)}</div></div>`));return;}
  const v=DATA.today_view||{},m=DATA.month||{},cash=v.cash_closure,rows=renderRows(),oc=e(PREFILL.orderCode||''),at=PREFILL.appointmentType||'pickup';
  const activity=(m.days||[]).filter(x=>Number(x.income)||Number(x.expenses));
  drawer('Hoy · operaciones',`
   <div class="nf41-summary"><div class="nf41-kpi"><small>Citas hoy</small><b>${(v.appointments||[]).length}</b></div><div class="nf41-kpi"><small>Tareas activas</small><b>${activeTaskCount()}</b></div><div class="nf41-kpi"><small>Neto hoy</small><b class="${Number(v.money?.net||0)>=0?'nf41-positive':'nf41-negative'}">${money(v.money?.net||0)}</b></div><div class="nf41-kpi"><small>Neto mes</small><b class="${Number(m.net||0)>=0?'nf41-positive':'nf41-negative'}">${money(m.net||0)}</b></div></div>
   <div class="nf41-grid">
    <div class="box"><h3>Agenda de hoy</h3><div class="nf41-list">${rows.apHtml}</div></div>
    <div class="box"><h3>Tareas</h3><div class="nf41-list">${rows.tHtml}</div></div>
   </div>
   <div class="nf41-grid">
    <div class="box"><h3>Programar retiro / entrega</h3><div class="form-grid"><div class="field"><label>Orden</label><input id="opOrder" value="${oc}" placeholder="NF-..."></div><div class="field"><label>Tipo</label><select id="opType"><option value="pickup" ${at==='pickup'?'selected':''}>Retiro</option><option value="delivery" ${at==='delivery'?'selected':''}>Entrega</option><option value="dropoff">Recepción acordada</option><option value="home_service">Visita a domicilio</option><option value="other">Otro</option></select></div><div class="field"><label>Fecha y hora</label><input id="opAt" type="datetime-local" value="${localInput(1)}"></div><div class="field"><label>Localidad</label><input id="opLoc" placeholder="Moreno"></div><div class="field full"><label>Dirección / referencia</label><input id="opAddr"></div><div class="field full"><label>Nota</label><input id="opNote"></div></div><div class="row-actions"><button class="btn primary" id="saveAppointment">Programar</button></div><div id="opMsg" class="msg"></div></div>
    <div class="box"><h3>Nueva tarea</h3><div class="form-grid"><div class="field"><label>Orden</label><input id="taskOrder" value="${oc}" placeholder="Opcional · NF-..."></div><div class="field"><label>Prioridad</label><select id="taskPriority"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option><option value="low">Baja</option></select></div><div class="field full"><label>Tarea</label><input id="taskTitle" placeholder="Ej: probar batería después del cambio"></div><div class="field"><label>Tipo</label><select id="taskType"><option value="diagnosis">Diagnóstico</option><option value="repair">Reparación</option><option value="call">Llamar</option><option value="quote">Presupuesto</option><option value="part">Repuesto</option><option value="pickup">Retiro</option><option value="delivery">Entrega</option><option value="admin">Administrativa</option><option value="other">Otra</option></select></div><div class="field"><label>Vencimiento</label><input id="taskDue" type="datetime-local" value="${localInput(2)}"></div><div class="field full"><label>Nota</label><input id="taskNote"></div></div><div class="row-actions"><button class="btn primary" id="saveTask">Crear tarea</button></div><div id="taskMsg" class="msg"></div></div>
   </div>
   <div class="nf41-grid">
    <div class="box"><h3>Cierre de caja · ${donly(DATA.today)}</h3>${cash?`<div class="nf41-closed"><b>${cash.status==='closed'?'Caja cerrada':'Cierre reabierto'}</b><small>Esperado ${money(cash.expected_cash)} · contado ${money(cash.counted_cash)} · diferencia ${money(cash.difference)}</small></div>`:''}<div class="form-grid"><div class="field"><label>Efectivo inicial</label><input id="cashOpen" type="number" min="0" value="${cash?.opening_cash??0}"></div><div class="field"><label>Efectivo contado</label><input id="cashCount" type="number" min="0" value="${cash?.counted_cash??0}"></div><div class="field full"><label>Nota</label><input id="cashNote" value="${e(cash?.note||'')}"></div></div><div class="row-actions"><button class="btn primary" id="closeCash">${cash?'Actualizar cierre':'Cerrar caja de hoy'}</button>${cash?.status==='closed'?'<button class="btn" id="reopenCash">Reabrir</button>':''}</div><div id="cashMsg" class="msg"></div><p class="nf41-note">El cierre compara el efectivo esperado con el contado. Los totales generales incluyen todos los medios de pago.</p></div>
    <div class="box"><h3>Resumen mensual · ${e(m.key||'')}</h3><div class="nf41-summary"><div class="nf41-kpi"><small>Ingresos</small><b>${money(m.income||0)}</b></div><div class="nf41-kpi"><small>Gastos</small><b>${money(m.expenses||0)}</b></div><div class="nf41-kpi"><small>Neto</small><b>${money(m.net||0)}</b></div><div class="nf41-kpi"><small>Días con movimiento</small><b>${activity.length}</b></div></div><div class="nf41-month">${activity.length?activity.map(x=>`<div class="nf41-day"><small>${donly(x.date)}</small><b class="${Number(x.net)>=0?'nf41-positive':'nf41-negative'}">${money(x.net)}</b><small>+${money(x.income)} / −${money(x.expenses)}</small></div>`).join(''):'<div class="empty">Todavía no hay movimientos este mes.</div>'}</div></div>
   </div>`);
  bindOps();PREFILL={};
 }
 function bindOps(){
  document.querySelectorAll('[data-a]').forEach(b=>b.addEventListener('click',async()=>{try{await act({action:'update_appointment',id:b.dataset.id,status:b.dataset.a});openOps();toast('Agenda actualizada')}catch(x){toast(x.message)}}));
  document.querySelectorAll('[data-t]').forEach(b=>b.addEventListener('click',async()=>{try{await act({action:'update_task',id:b.dataset.id,status:b.dataset.t});openOps();toast('Tarea actualizada')}catch(x){toast(x.message)}}));
  document.getElementById('saveAppointment')?.addEventListener('click',async()=>{const at=document.getElementById('opAt').value;if(!at)return msg('#opMsg','Elegí fecha y hora.',true);msg('#opMsg','Guardando…');try{await act({action:'create_appointment',order_code:document.getElementById('opOrder').value.trim()||null,appointment_type:document.getElementById('opType').value,scheduled_at:iso(at),locality:document.getElementById('opLoc').value.trim()||null,address_notes:document.getElementById('opAddr').value.trim()||null,note:document.getElementById('opNote').value.trim()||null});openOps();toast('Cita programada')}catch(x){msg('#opMsg',x.message,true)}});
  document.getElementById('saveTask')?.addEventListener('click',async()=>{const title=document.getElementById('taskTitle').value.trim();if(!title)return msg('#taskMsg','Escribí la tarea.',true);msg('#taskMsg','Guardando…');try{await act({action:'create_task',order_code:document.getElementById('taskOrder').value.trim()||null,title,task_type:document.getElementById('taskType').value,priority:document.getElementById('taskPriority').value,due_at:iso(document.getElementById('taskDue').value),note:document.getElementById('taskNote').value.trim()||null});openOps();toast('Tarea creada')}catch(x){msg('#taskMsg',x.message,true)}});
  document.getElementById('closeCash')?.addEventListener('click',async()=>{msg('#cashMsg','Calculando cierre…');try{await act({action:'close_cash_day',close_date:DATA.today,opening_cash:Number(document.getElementById('cashOpen').value||0),counted_cash:Number(document.getElementById('cashCount').value||0),note:document.getElementById('cashNote').value.trim()||null});openOps();toast('Caja cerrada')}catch(x){msg('#cashMsg',x.message,true)}});
  document.getElementById('reopenCash')?.addEventListener('click',async()=>{try{await act({action:'reopen_cash_day',close_date:DATA.today});openOps();toast('Cierre reabierto')}catch(x){msg('#cashMsg',x.message,true)}});
 }
 function quickBox(code){const body=document.getElementById('drawerBody');if(!body||document.getElementById('nf41Quick'))return;body.insertAdjacentHTML('beforeend',`<div class="box" id="nf41Quick"><h3>Agenda y tareas</h3><div class="nf41-quick"><button class="btn" id="nf41Pickup">Programar retiro</button><button class="btn" id="nf41Delivery">Programar entrega</button><button class="btn" id="nf41Task">Crear tarea</button></div></div>`);document.getElementById('nf41Pickup').onclick=()=>openOps({orderCode:code,appointmentType:'pickup'});document.getElementById('nf41Delivery').onclick=()=>openOps({orderCode:code,appointmentType:'delivery'});document.getElementById('nf41Task').onclick=()=>openOps({orderCode:code});}
 function hookOrder(){const prev=window.openOrder;if(typeof prev!=='function'||prev.__nf41)return;const wrapped=function(code){prev(code);setTimeout(()=>quickBox(code),220)};wrapped.__nf41=true;window.openOrder=wrapped;}
 document.addEventListener('DOMContentLoaded',()=>{addButton();hookOrder();if(tok())loadOps().catch(()=>{});document.getElementById('refreshBtn')?.addEventListener('click',()=>loadOps().catch(()=>{}));});
 setTimeout(()=>{addButton();hookOrder();if(tok())loadOps().catch(()=>{})},500);
 window.nf41OpenOperations=openOps;
})();
