const SB='https://abcuvgoipnwiltlbcqxa.supabase.co';
const KEY='sb_publishable_qCFyX0zIAgDPIiWQxAIb0g_cFiK21fM';
const TRACK=`${SB}/functions/v1/nextfuture-track`;
const RESP=`${SB}/functions/v1/nextfuture-budget-response`;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>v==null?'—':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
const dt=v=>v?new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}):'—';
const labels={requested:'Solicitud',pickup_scheduled:'Retiro programado',awaiting_dropoff:'Esperando recepción',received:'Recibido',diagnosing:'Diagnóstico',awaiting_approval:'Presupuesto enviado',budget_approved:'Presupuesto aprobado',awaiting_deposit:'Esperando seña',awaiting_part:'Esperando repuesto',repairing:'Reparación',testing:'Pruebas',ready_for_pickup:'Listo',delivery_scheduled:'Entrega programada',out_for_delivery:'En camino',delivered:'Entregado',budget_rejected:'Presupuesto rechazado',cancelled:'Cancelado'};
const devices={phone:'Celular',tablet:'Tablet',notebook:'Notebook',pc:'PC de escritorio'};
let receiptToken='';
async function boot(){receiptToken=new URL(location.href).searchParams.get('token')||'';if(!receiptToken){$('#loading').innerHTML='<b class="error">Enlace incompleto.</b>';return}try{const r=await fetch(TRACK,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({token:receiptToken})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo cargar');render(d)}catch(e){$('#loading').innerHTML=`<b class="error">${esc(e.message)}</b>`}}
function budgetDecision(o){
 if(o.budget_status==='sent')return `<section class="card"><h2>Decisión sobre el presupuesto</h2><p>Revisá el total y la seña. Podés aceptar o rechazar este presupuesto desde este enlace privado.</p><div class="receipt-actions"><button id="acceptBudget" type="button">Aceptar presupuesto</button><button id="rejectBudget" type="button">Rechazar presupuesto</button></div><div id="budgetDecisionMsg"></div></section>`;
 if(o.budget_status==='approved')return `<section class="card"><h2>Presupuesto aceptado ✓</h2><p>El trabajo quedó autorizado. ${Number(o.deposit_required||0)>Number(o.deposit_received||0)?`Queda pendiente registrar una seña de <b>${money(Number(o.deposit_required||0)-Number(o.deposit_received||0))}</b>.`:'No hay seña pendiente.'}</p></section>`;
 if(o.budget_status==='rejected')return `<section class="card"><h2>Presupuesto rechazado</h2><p>La reparación quedó detenida. Podés comunicarte con Nextfuture si querés revisar alternativas.</p></section>`;
 return '';
}
function bindBudget(){
 document.getElementById('acceptBudget')?.addEventListener('click',()=>answerBudget('accept'));
 document.getElementById('rejectBudget')?.addEventListener('click',()=>answerBudget('reject'));
}
async function answerBudget(action){
 if(action==='accept'&&!confirm('¿Querés aceptar este presupuesto y autorizar el trabajo?'))return;
 if(action==='reject'&&!confirm('¿Querés rechazar este presupuesto?'))return;
 const msg=document.getElementById('budgetDecisionMsg');if(msg)msg.textContent='Registrando respuesta…';
 document.querySelectorAll('#acceptBudget,#rejectBudget').forEach(b=>b.disabled=true);
 try{const r=await fetch(RESP,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({token:receiptToken,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo registrar la respuesta');if(msg)msg.textContent=d.message||'Respuesta registrada.';setTimeout(boot,500)}catch(e){if(msg)msg.textContent=e.message||'No pudimos registrar la respuesta.';document.querySelectorAll('#acceptBudget,#rejectBudget').forEach(b=>b.disabled=false)}
}
function render(d){const o=d.order;const device=[o.brand,o.model].filter(Boolean).join(' ')||devices[o.device_type]||o.device_type;const pending=Math.max(0,Number(o.deposit_required||0)-Number(o.deposit_received||0));$('#loading').classList.add('hidden');$('#content').classList.remove('hidden');$('#content').innerHTML=`
<section class="receipt-actions"><button onclick="window.print()">Imprimir / guardar PDF</button><a href="./index.html#seguimiento">Volver a Nextfuture</a></section>
<section class="card"><div class="head"><div><small>ORDEN DE REPARACIÓN</small><div class="code">${esc(o.order_code)}</div><p>${esc(device)}</p></div><span class="pill">${esc(labels[o.order_status]||o.order_status)}</span></div></section>
<section class="card"><h2>Recepción del equipo</h2><div class="grid"><div class="item"><small>Equipo</small><b>${esc(device)}</b></div><div class="item"><small>Localidad</small><b>${esc(o.locality||'—')}</b></div><div class="item"><small>Falla declarada</small><span>${esc(o.declared_issue||'—')}</span></div><div class="item"><small>Accesorios</small><span>${esc(o.accessories||'Ninguno informado')}</span></div><div class="item"><small>Estado físico registrado</small><span>${esc(o.condition_notes||'Sin observaciones registradas')}</span></div><div class="item"><small>Fecha de recepción</small><span>${dt(o.received_at||o.created_at)}</span></div></div>${o.receipt_note?`<div class="receipt-note"><b>Nota de recepción</b><p>${esc(o.receipt_note)}</p></div>`:''}</section>
${o.diagnosis||o.work_planned?`<section class="card"><h2>Diagnóstico y trabajo</h2><div class="grid"><div class="item"><small>Diagnóstico</small><span>${esc(o.diagnosis||'Pendiente')}</span></div><div class="item"><small>Trabajo previsto</small><span>${esc(o.work_planned||'Pendiente')}</span></div><div class="item"><small>Plazo orientativo</small><span>${esc(o.repair_estimate_text||'A confirmar')}</span></div><div class="item"><small>Garantía informada</small><span>${esc(o.warranty_text||'A confirmar')}</span></div></div></section>`:''}
${o.budget_total!=null?`<section class="card"><h2>Presupuesto</h2><div class="grid"><div class="item"><small>Total</small><span class="money">${money(o.budget_total)}</span></div><div class="item"><small>Seña requerida</small><span class="money">${money(o.deposit_required)}</span></div><div class="item"><small>Seña registrada</small><span>${money(o.deposit_received)}</span></div><div class="item"><small>Pendiente de seña</small><span>${money(pending)}</span></div></div></section>`:''}
${budgetDecision(o)}
<section class="card"><h2>Seguimiento</h2><div class="timeline">${(d.events||[]).length?(d.events||[]).map(e=>`<div class="event"><b>${esc(e.public_label)}</b>${e.public_note?`<span>${esc(e.public_note)}</span>`:''}<small>${dt(e.created_at)}</small></div>`).join(''):'<div class="item">Sin novedades publicadas todavía.</div>'}</div></section>
${o.order_status==='delivered'?`<section class="card delivered"><h2>Equipo entregado</h2><p><b>La reparación fue entregada${o.delivery_confirmed_name?' a '+esc(o.delivery_confirmed_name):''}.</b></p><p>${o.delivery_confirmed_at?dt(o.delivery_confirmed_at):dt(o.completed_at)}</p>${o.delivery_note?`<p>${esc(o.delivery_note)}</p>`:''}<p>Si querés, debajo podés dejar una devolución sobre tu experiencia. Es opcional.</p></section>`:''}
<section class="card conditions"><h2>Condiciones operativas de recepción</h2><ul><li>El diagnóstico web o inicial es orientativo; el diagnóstico definitivo se confirma con la revisión técnica del equipo.</li><li>No se realizan reparaciones ni cambios de repuestos de importancia sin presupuesto y autorización previa.</li><li>El cliente debe conservar copia de seguridad de sus datos cuando sea posible. Una intervención técnica puede implicar riesgos sobre información almacenada, especialmente en equipos dañados.</li><li>Los accesorios y el estado físico considerados son los detallados en este comprobante.</li><li>Nextfuture no solicita que contraseñas, PIN, patrones, Apple ID, Google o claves bancarias queden asentadas en este comprobante.</li><li>La garantía aplicable es la que se informe específicamente para el trabajo y/o repuesto realizado.</li></ul><p class="terms-version">Versión: ${esc(o.receipt_terms_version||'2026-09-v1')}</p></section>`;bindBudget()}
boot();