const SB='https://abcuvgoipnwiltlbcqxa.supabase.co';
const KEY='sb_publishable_qCFyX0zIAgDPIiWQxAIb0g_cFiK21fM';
const TRACK=`${SB}/functions/v1/nextfuture-track`;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>v==null?'—':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
const dt=v=>v?new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}):'—';
const labels={requested:'Solicitud',pickup_scheduled:'Retiro programado',awaiting_dropoff:'Esperando recepción',received:'Recibido',diagnosing:'Diagnóstico',awaiting_approval:'Presupuesto enviado',budget_approved:'Presupuesto aprobado',awaiting_deposit:'Esperando seña',awaiting_part:'Esperando repuesto',repairing:'Reparación',testing:'Pruebas',ready_for_pickup:'Listo',delivery_scheduled:'Entrega programada',out_for_delivery:'En camino',delivered:'Entregado',budget_rejected:'Presupuesto rechazado',cancelled:'Cancelado'};
const devices={phone:'Celular',tablet:'Tablet',notebook:'Notebook',pc:'PC de escritorio'};
async function boot(){const token=new URL(location.href).searchParams.get('token')||'';if(!token){$('#loading').innerHTML='<b class="error">Enlace incompleto.</b>';return}try{const r=await fetch(TRACK,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo cargar');render(d)}catch(e){$('#loading').innerHTML=`<b class="error">${esc(e.message)}</b>`}}
function render(d){const o=d.order;const device=[o.brand,o.model].filter(Boolean).join(' ')||devices[o.device_type]||o.device_type;const pending=Math.max(0,Number(o.deposit_required||0)-Number(o.deposit_received||0));$('#loading').classList.add('hidden');$('#content').classList.remove('hidden');$('#content').innerHTML=`<section class="card"><div class="head"><div><small>ORDEN DE REPARACIÓN</small><div class="code">${esc(o.order_code)}</div><p>${esc(device)}</p></div><span class="pill">${esc(labels[o.order_status]||o.order_status)}</span></div></section><section class="card"><h2>Equipo recibido / registrado</h2><div class="grid"><div class="item"><small>Equipo</small><b>${esc(device)}</b></div><div class="item"><small>Localidad</small><b>${esc(o.locality||'—')}</b></div><div class="item"><small>Falla declarada</small><span>${esc(o.declared_issue||'—')}</span></div><div class="item"><small>Accesorios</small><span>${esc(o.accessories||'Ninguno informado')}</span></div><div class="item"><small>Estado físico registrado</small><span>${esc(o.condition_notes||'Sin observaciones registradas')}</span></div><div class="item"><small>Fecha de recepción</small><span>${dt(o.received_at||o.created_at)}</span></div></div></section>${o.diagnosis||o.work_planned?`<section class="card"><h2>Diagnóstico y trabajo</h2><div class="grid"><div class="item"><small>Diagnóstico</small><span>${esc(o.diagnosis||'Pendiente')}</span></div><div class="item"><small>Trabajo previsto</small><span>${esc(o.work_planned||'Pendiente')}</span></div><div class="item"><small>Plazo orientativo</small><span>${esc(o.repair_estimate_text||'A confirmar')}</span></div><div class="item"><small>Garantía informada</small><span>${esc(o.warranty_text||'A confirmar')}</span></div></div></section>`:''}${o.budget_total!=null?`<section class="card"><h2>Presupuesto</h2><div class="grid"><div class="item"><small>Total</small><span class="money">${money(o.budget_total)}</span></div><div class="item"><small>Seña requerida</small><span class="money">${money(o.deposit_required)}</span></div><div class="item"><small>Seña registrada</small><span>${money(o.deposit_received)}</span></div><div class="item"><small>Pendiente de seña</small><span>${money(pending)}</span></div></div></section>`:''}<section class="card"><h2>Seguimiento</h2><div class="timeline">${(d.events||[]).length?(d.events||[]).map(e=>`<div class="event"><b>${esc(e.public_label)}</b>${e.public_note?`<span>${esc(e.public_note)}</span>`:''}<small>${dt(e.created_at)}</small></div>`).join(''):'<div class="item">Sin novedades publicadas todavía.</div>'}</div></section>${o.receipt_note?`<section class="card"><h3>Nota del comprobante</h3><p>${esc(o.receipt_note)}</p></section>`:''}`}
boot();