const DIAG_DATA={
  phone:{label:'Celular',symptoms:{
    no_power:{label:'No enciende',price:'Requiere revisión',inspection:true,causes:['Batería agotada, degradada o desconectada','Puerto o circuito de carga','Falla de encendido o placa'],questions:[{id:'signs',text:'¿Hace alguna vibración, sonido o prende alguna luz?',yes:'Hay señales de vida: podría ser pantalla, batería o alimentación parcial.',no:'Sin señales de vida: hay que medir batería, carga y placa.'},{id:'charger',text:'¿Probaste con otro cargador y cable que sabés que funcionan?',yes:'Ya se descartó parcialmente cargador/cable.',no:'Conviene descartar primero cargador y cable.'},{id:'drop',text:'¿Dejó de encender después de un golpe o caída?',yes:'El golpe aumenta la probabilidad de conector, pantalla o placa.',no:'No hay un golpe reciente asociado.'}]},
    charge:{label:'No carga o carga mal',price:'$41.000–$81.000',causes:['Puerto de carga sucio o dañado','Cable/cargador incompatible o defectuoso','Flex, subplaca o circuito de carga'],questions:[{id:'other_charger',text:'¿Probaste otro cargador y cable?',yes:'Si sigue igual con otro cargador, aumenta la sospecha sobre el equipo.',no:'Todavía conviene descartar cargador y cable.'},{id:'moves',text:'¿Carga sólo si movés o inclinás el cable?',yes:'Ese comportamiento suele orientar al puerto o conector de carga.',no:'Puede ser puerto, batería o circuito de carga.'}]},
    screen:{label:'Pantalla rota o sin imagen',price:'$54.000–$126.000',causes:['Módulo de pantalla o táctil dañado','Vidrio/módulo afectado por golpe','Conector o display sin señal'],questions:[{id:'image',text:'¿Se ve imagen aunque el vidrio esté roto?',yes:'Si hay imagen, puede estar dañado el táctil o el conjunto exterior.',no:'Si no hay imagen, aumenta la posibilidad de módulo completo o conexión.'},{id:'touch',text:'¿El táctil responde normalmente?',yes:'El táctil aún responde.',no:'La falla también afecta la respuesta táctil.'}]},
    battery:{label:'La batería dura poco o se apaga',price:'$32.000–$63.000',causes:['Batería degradada','Consumo anormal de software','Batería hinchada o dañada'],questions:[{id:'swollen',text:'¿La tapa o la pantalla se levantó / la batería parece hinchada?',yes:'Posible batería hinchada: no conviene seguir cargando ni usando el equipo.',no:'No se observa hinchazón.',urgentIfYes:true},{id:'shutdown',text:'¿Se apaga aun mostrando batería disponible?',yes:'Los apagados inesperados son compatibles con batería degradada o alimentación.',no:'El síntoma parece más relacionado con autonomía reducida.'}]},
    water:{label:'Se mojó o tuvo líquido',price:'Requiere revisión',inspection:true,causes:['Humedad o corrosión interna','Cortocircuito en conectores o placa','Daño progresivo por líquido'],questions:[{id:'powered',text:'¿Intentaste encenderlo o cargarlo después de mojarse?',yes:'Encender o cargar un equipo mojado puede aumentar el daño eléctrico.',no:'Bien: evitar energizarlo reduce el riesgo de daño adicional.',urgentIfYes:true},{id:'sweet',text:'¿Fue gaseosa, bebida azucarada o agua con sal?',yes:'Los líquidos con sales o azúcar son más corrosivos y requieren limpieza técnica pronta.',no:'Igualmente conviene revisión y limpieza interna.'}]},
    slow:{label:'Está lento o se traba',price:'$25.000–$45.000',causes:['Almacenamiento casi lleno','Software, apps o sistema saturado','Memoria o almacenamiento con fallas'],questions:[{id:'storage',text:'¿Tenés muy poco espacio libre?',yes:'El poco espacio libre puede explicar parte de la lentitud.',no:'Hay que revisar software, memoria y almacenamiento.'},{id:'restart',text:'¿También se reinicia o se congela?',yes:'Los reinicios/congelamientos pueden indicar un problema más profundo de software o hardware.',no:'Parece una lentitud estable sin reinicios.'}]}
  }},
  tablet:{label:'Tablet',symptoms:{
    no_power:{label:'No enciende',price:'Requiere revisión',inspection:true,causes:['Batería o alimentación','Puerto/circuito de carga','Placa o botón de encendido'],questions:[{id:'signs',text:'¿Muestra alguna luz, logo, sonido o vibración?',yes:'Hay señales de alimentación parcial.',no:'Hay que revisar batería y alimentación desde cero.'},{id:'charger',text:'¿Probaste otro cargador compatible?',yes:'Se descartó parcialmente el cargador.',no:'Conviene descartar cargador/cable antes de intervenir.'}]},
    charge:{label:'No carga',price:'$45.000–$95.000',causes:['Puerto de carga','Cable/cargador','Flex o circuito de alimentación'],questions:[{id:'moves',text:'¿Carga si movés el conector?',yes:'Puede haber desgaste o juego en el puerto.',no:'Puede ser puerto, batería o circuito.'},{id:'other',text:'¿Probaste otro cargador/cable?',yes:'La falla parece estar en el equipo.',no:'Falta descartar el accesorio de carga.'}]},
    screen:{label:'Pantalla rota',price:'$60.000–$170.000',causes:['Vidrio/módulo de pantalla','Táctil','Conector o display'],questions:[{id:'image',text:'¿Se ve imagen?',yes:'La pantalla aún genera imagen.',no:'Puede requerir módulo completo o revisión de conexión.'},{id:'touch',text:'¿El táctil funciona?',yes:'El táctil todavía responde.',no:'El daño también afecta la capa táctil.'}]},
    battery:{label:'Problema de batería',price:'$40.000–$85.000',causes:['Batería degradada','Batería hinchada','Consumo anormal'],questions:[{id:'swollen',text:'¿La carcasa o pantalla se está levantando?',yes:'Posible batería hinchada: suspender uso y carga.',no:'No se observa hinchazón.',urgentIfYes:true},{id:'fast',text:'¿La batería cae muy rápido aun sin usarla?',yes:'Puede haber batería degradada o consumo anormal.',no:'El problema podría aparecer sólo bajo carga.'}]},
    slow:{label:'Está lenta',price:'$25.000–$45.000',causes:['Sistema saturado','Almacenamiento lleno','Memoria/almacenamiento'],questions:[{id:'storage',text:'¿Está casi sin espacio?',yes:'Liberar o revisar almacenamiento puede mejorar el rendimiento.',no:'Hay que revisar sistema y hardware.'}]}
  }},
  notebook:{label:'Notebook',symptoms:{
    no_power:{label:'No enciende',price:'Requiere revisión',inspection:true,causes:['Cargador o jack DC','Batería o circuito de alimentación','Placa madre'],questions:[{id:'lights',text:'¿Enciende alguna luz o ventilador?',yes:'Hay alimentación parcial; puede ser pantalla, RAM o placa.',no:'Hay que revisar cargador, jack y placa.'},{id:'charger',text:'¿El cargador fue probado o funciona en otro equipo compatible?',yes:'Se reduce la probabilidad de que sea sólo el cargador.',no:'El cargador debe descartarse primero.'}]},
    overheat:{label:'Se calienta mucho',price:'$54.000–$86.000',causes:['Suciedad en disipación','Pasta térmica degradada','Ventilador o sistema térmico'],questions:[{id:'fan',text:'¿El ventilador hace mucho ruido?',yes:'El sistema térmico está trabajando al límite o puede estar obstruido.',no:'Puede existir mala transferencia térmica aun sin ruido.'},{id:'shutdown',text:'¿Se apaga o reinicia cuando calienta?',yes:'Hay riesgo de protección térmica; conviene mantenimiento pronto.',no:'Todavía no hay apagado térmico reportado.'}]},
    slow:{label:'Está lenta',price:'$50.000–$72.000',causes:['Disco HDD lento o degradado','Sistema saturado','Poca RAM o almacenamiento'],questions:[{id:'hdd',text:'¿Tiene disco rígido HDD en vez de SSD?',yes:'Un cambio a SSD suele mejorar mucho el rendimiento.',no:'Hay que revisar sistema, RAM y salud del almacenamiento.'},{id:'boot',text:'¿Tarda mucho en iniciar?',yes:'El almacenamiento o el sistema pueden estar afectando el arranque.',no:'La lentitud puede aparecer sólo al usar programas.'}]},
    screen:{label:'Pantalla sin imagen o rota',price:'$99.000–$198.000',causes:['Panel/display','Flex de pantalla','Video/placa'],questions:[{id:'external',text:'¿Da imagen conectada a un monitor o TV externo?',yes:'Si afuera da imagen, aumenta la sospecha sobre pantalla o flex.',no:'También puede involucrar video, RAM o placa.'},{id:'cracked',text:'¿El panel está físicamente quebrado?',yes:'El daño físico suele requerir reemplazo del panel.',no:'Puede ser flex, backlight, señal o placa.'}]},
    charge:{label:'No carga',price:'$63.000–$113.000',causes:['Jack/conector de carga','Cargador','Circuito de alimentación'],questions:[{id:'moves',text:'¿Carga al mover el conector?',yes:'Puede haber desgaste del jack o soldadura.',no:'Puede ser cargador, batería o circuito.'},{id:'charger',text:'¿Probaste otro cargador compatible?',yes:'La falla parece más ligada al equipo.',no:'Conviene comprobar el cargador.'}]},
    keyboard:{label:'Teclado falla',price:'$63.000–$113.000',causes:['Teclado o membrana','Flex/conector','Daño por líquido'],questions:[{id:'liquid',text:'¿Se derramó líquido sobre el teclado?',yes:'Un derrame puede afectar teclado y placa; requiere revisión cuidadosa.',no:'Puede ser desgaste del teclado o flex.'},{id:'some',text:'¿Fallan sólo algunas teclas?',yes:'Es compatible con falla localizada del teclado/membrana.',no:'Si falla completo, también hay que revisar flex/controlador.'}]}
  }},
  pc:{label:'PC',symptoms:{
    no_power:{label:'No enciende',price:'Requiere revisión',inspection:true,causes:['Fuente de alimentación','Placa madre','Botón/cableado o componente en corto'],questions:[{id:'fans',text:'¿Gira algún ventilador o prende alguna luz?',yes:'Hay alimentación parcial; hay que revisar POST, RAM y video.',no:'Fuente, alimentación o placa son las primeras sospechas.'},{id:'storm',text:'¿Ocurrió después de un corte de luz o tormenta?',yes:'Aumenta la sospecha de fuente o daño eléctrico.',no:'No hay un evento eléctrico reciente informado.'}]},
    no_image:{label:'Enciende pero no da imagen',price:'$30.000–$65.000',causes:['RAM mal conectada o con falla','Placa de video / video integrado','Fuente, placa o monitor'],questions:[{id:'beep',text:'¿Hace pitidos al encender?',yes:'Los pitidos pueden ayudar a localizar RAM, video u otro componente.',no:'Sin pitidos todavía hay que revisar RAM, video y alimentación.'},{id:'monitor',text:'¿Probaste otro monitor o cable?',yes:'Se descartó parcialmente monitor/cable.',no:'Conviene descartar monitor y cable de video.'}]},
    slow:{label:'Está lenta',price:'$35.000–$55.000',causes:['Windows/sistema saturado','HDD lento o degradado','RAM insuficiente'],questions:[{id:'hdd',text:'¿Usa disco HDD?',yes:'Migrar a SSD suele producir una mejora importante.',no:'Hay que revisar sistema, RAM y salud del almacenamiento.'},{id:'startup',text:'¿Tarda mucho en iniciar Windows?',yes:'El disco o el sistema pueden estar afectando el arranque.',no:'La lentitud puede estar vinculada a programas específicos.'}]},
    restart:{label:'Se reinicia o se apaga',price:'$30.000–$55.000',causes:['Temperatura','Fuente inestable','RAM o placa'],questions:[{id:'heat',text:'¿Pasa más cuando jugás o exigís la PC?',yes:'Temperatura o fuente ganan probabilidad bajo carga.',no:'Hay que revisar fuente, RAM, sistema y placa.'},{id:'dust',text:'¿Hace mucho que no se limpia internamente?',yes:'La suciedad puede elevar temperatura y generar inestabilidad.',no:'Igualmente conviene medir temperaturas y fuente.'}]},
    windows:{label:'Windows no inicia o falla',price:'$35.000–$55.000',causes:['Sistema operativo dañado','Disco con errores','Actualización/controlador'],questions:[{id:'data',text:'¿Tenés archivos importantes que necesitás conservar?',yes:'Antes de reinstalar conviene priorizar respaldo/recuperación de datos.',no:'La reinstalación puede ser más directa si el disco está sano.'},{id:'disk',text:'¿Hace ruidos raros el disco o aparecen errores frecuentes?',yes:'Puede haber un problema físico del almacenamiento; no conviene forzar el uso.',no:'Podría ser principalmente software.'}]}
  }}
};

const diagState={device:null,symptom:null,answers:{}};
const diagProgress=document.getElementById('diagProgress');
const stages={device:document.getElementById('diagDeviceStage'),symptom:document.getElementById('diagSymptomStage'),question:document.getElementById('diagQuestionStage'),result:document.getElementById('diagResultStage')};
function diagShow(name,step){Object.values(stages).forEach(x=>x.classList.add('hidden'));stages[name].classList.remove('hidden');diagProgress.textContent=`Paso ${step} de 4`;}
function diagEsc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));}
function symptomButton(key,s){return `<button class="symptom-choice" data-diag-symptom="${key}"><b>${diagEsc(s.label)}</b><small>${s.inspection?'Necesita revisión física para cotizar con precisión.':`Referencia orientativa: ${diagEsc(s.price)}`}</small></button>`;}

document.querySelectorAll('[data-diag-device]').forEach(btn=>btn.addEventListener('click',()=>{
  diagState.device=btn.dataset.diagDevice;diagState.symptom=null;diagState.answers={};
  const device=DIAG_DATA[diagState.device];
  document.getElementById('diagSymptoms').innerHTML=Object.entries(device.symptoms).map(([k,s])=>symptomButton(k,s)).join('');
  document.querySelectorAll('[data-diag-symptom]').forEach(sbtn=>sbtn.addEventListener('click',()=>chooseSymptom(sbtn.dataset.diagSymptom)));
  diagShow('symptom',2);
}));

function chooseSymptom(key){
  diagState.symptom=key;diagState.answers={};
  const s=DIAG_DATA[diagState.device].symptoms[key];
  document.getElementById('diagQuestionIntro').textContent=`${DIAG_DATA[diagState.device].label} · ${s.label}. Estas respuestas nos ayudan a orientar mejor el diagnóstico.`;
  document.getElementById('diagQuestions').innerHTML=s.questions.map(q=>`<div class="question-card"><p>${diagEsc(q.text)}</p><div class="question-options"><label><input type="radio" name="diag_${q.id}" value="yes"> Sí</label><label><input type="radio" name="diag_${q.id}" value="no"> No</label></div></div>`).join('');
  diagShow('question',3);
}

document.getElementById('diagBackDevice').addEventListener('click',()=>diagShow('device',1));
document.getElementById('diagBackSymptom').addEventListener('click',()=>diagShow('symptom',2));
document.getElementById('diagRestart').addEventListener('click',()=>{diagState.device=null;diagState.symptom=null;diagState.answers={};document.getElementById('diagBrand').value='';document.getElementById('diagModel').value='';diagShow('device',1);});

document.getElementById('diagCalculate').addEventListener('click',()=>{
  const symptom=DIAG_DATA[diagState.device].symptoms[diagState.symptom];
  const unanswered=[];const observations=[];let urgent=false;
  symptom.questions.forEach(q=>{
    const selected=document.querySelector(`input[name="diag_${q.id}"]:checked`);
    if(!selected){unanswered.push(q.id);return;}
    diagState.answers[q.id]=selected.value;
    const yes=selected.value==='yes';
    observations.push(yes?q.yes:q.no);
    if(yes&&q.urgentIfYes) urgent=true;
  });
  if(unanswered.length){alert('Respondé todas las preguntas para obtener una orientación más útil.');return;}
  renderDiagnosis(symptom,observations,urgent);
  diagShow('result',4);
});

function renderDiagnosis(symptom,observations,urgent){
  const brand=document.getElementById('diagBrand').value.trim();
  const model=document.getElementById('diagModel').value.trim();
  const equipment=[brand,model].filter(Boolean).join(' ')||DIAG_DATA[diagState.device].label;
  const badge=urgent?'<span class="diag-badge urgent">ATENCIÓN PRIORITARIA</span>':symptom.inspection?'<span class="diag-badge warn">REQUIERE REVISIÓN</span>':'<span class="diag-badge">DIAGNÓSTICO ORIENTATIVO</span>';
  const alert=urgent?'<div class="diag-alert">Por tus respuestas conviene suspender el uso y la carga del equipo hasta revisarlo. Si hay batería hinchada o daño por líquido, no lo fuerces ni intentes abrirlo.</div>':'';
  document.getElementById('diagResultCard').innerHTML=`<div class="diag-result"><div class="diag-result-top"><div><small>RESULTADO PRELIMINAR</small><h3>${diagEsc(equipment)} · ${diagEsc(symptom.label)}</h3><p>Estas son las causas más probables según lo que respondiste.</p></div>${badge}</div><div class="diag-result-grid"><div class="diag-panel"><h4>Posibles causas</h4><ul>${symptom.causes.map(c=>`<li>${diagEsc(c)}</li>`).join('')}</ul></div><div class="diag-panel"><h4>Costo orientativo</h4><div class="diag-price">${diagEsc(symptom.price)}</div><div class="diag-price-note">${symptom.inspection?'No conviene prometer un valor sin medir y revisar físicamente el equipo.':'Referencia inicial para Zona Oeste. El precio final depende del modelo, repuesto disponible y estado real del equipo.'}</div></div><div class="diag-panel"><h4>Lo que indican tus respuestas</h4><ul>${observations.map(o=>`<li>${diagEsc(o)}</li>`).join('')}</ul></div><div class="diag-panel"><h4>Siguiente paso</h4><ul><li>Podés acercar el equipo con turno.</li><li>Podemos coordinar retiro según la zona.</li><li>Algunos trabajos pueden resolverse a domicilio.</li></ul></div></div>${alert}<div class="diag-actions"><div class="diag-selects"><div><label for="diagMode">Modalidad preferida</label><select id="diagMode"><option value="Lo acerco con turno">Lo acerco con turno</option><option value="Solicitar retiro">Solicitar retiro</option><option value="Servicio a domicilio">Servicio a domicilio</option></select></div><div><label for="diagLocality">Localidad</label><select id="diagLocality"><option>Moreno</option><option>Paso del Rey</option><option>Merlo</option><option>Ituzaingó</option><option>Morón</option><option>Otra zona</option></select></div></div><div class="diag-whatsapp"><a class="btn btn-primary" id="diagWhatsApp" target="_blank" rel="noopener">Enviar diagnóstico por WhatsApp</a></div></div><div class="diag-disclaimer">Este resultado es una orientación previa y no reemplaza el diagnóstico técnico físico. El presupuesto definitivo se confirma antes de realizar la reparación.</div></div>`;
  const link=document.getElementById('diagWhatsApp');
  const update=()=>{
    const mode=document.getElementById('diagMode').value,locality=document.getElementById('diagLocality').value;
    const msg=`Hola Nextfuture. Hice el diagnóstico previo. Equipo: ${equipment}. Síntoma: ${symptom.label}. Resultado/costo orientativo: ${symptom.price}. Modalidad: ${mode}. Localidad: ${locality}. Quiero coordinar una revisión.`;
    link.href=`https://wa.me/5491130112951?text=${encodeURIComponent(msg)}`;
  };
  document.getElementById('diagMode').addEventListener('change',update);document.getElementById('diagLocality').addEventListener('change',update);update();
}
