const steps=[
 {title:'Antes de acercarte',text:'La persona se desplomó. ¿Cuál es tu primera acción?',scene:'Una persona adulta se desploma y no responde. Vos sos quien está más cerca.',options:[['Compruebo que el lugar sea seguro para acercarme',1,'Correcto. Primero evitá convertirte en otra víctima.'],['Corro y empiezo compresiones sin mirar alrededor',0,'Primero comprobá rápidamente que la escena sea segura.'],['Le doy agua para ver si reacciona',0,'No corresponde dar agua a una persona inconsciente.']]},
 {title:'Comprobar respuesta',text:'El entorno parece seguro. ¿Cómo comprobás si responde?',scene:'Te acercaste. La persona permanece inmóvil.',options:[['Le hablo fuerte y estimulo suavemente sus hombros',1,'Correcto. Buscás una respuesta sin perder tiempo.'],['La siento en una silla',0,'No la sientes ni la pongas de pie si está inconsciente.'],['Espero unos minutos a ver si se despierta sola',0,'En una posible parada cada minuto importa.']]},
 {title:'Respiración',text:'No responde. ¿Qué dato es clave para reconocer una posible parada?',scene:'No responde cuando le hablás. Ahora evaluás su respiración.',options:[['Observo si respira normalmente; los jadeos agónicos no cuentan como respiración normal',1,'Correcto. Inconsciencia + ausencia de respiración normal es una señal de alarma para actuar.'],['Me quedo buscando el pulso durante medio minuto',0,'Para un reanimador lego, no conviene demorar el inicio por una búsqueda prolongada de pulso.'],['Si jadea, asumo que está respirando bien',0,'Los jadeos o gasping pueden aparecer en una parada y no equivalen a respiración normal.']]},
 {title:'Activar ayuda',text:'No responde y no respira normalmente. ¿Qué hacés?',scene:'La situación es compatible con una emergencia vital.',options:[['Activo el sistema de emergencias y pido que traigan un DEA; si hay alguien, reparto tareas',1,'Correcto. Activar ayuda, conseguir un DEA e iniciar RCP deben ocurrir lo antes posible.'],['La subo al auto antes de llamar a emergencias',0,'Eso puede retrasar la atención. Activá emergencias e iniciá RCP.'],['Busco su documentación antes de hacer otra cosa',0,'No retrases la RCP por documentación.']]}
];
let step=0,points=0,mistakes=0,answered=false,decisionPoints=0,compressionPoints=0,aedPoints=0,taps=[];
const $=id=>document.getElementById(id);
function renderStep(){answered=false;const s=steps[step];$('stepNumber').textContent=`Paso ${step+1} de 4`;$('stepTitle').textContent=s.title;$('stepText').textContent=s.text;$('sceneText').textContent=s.scene;$('choices').innerHTML='';$('feedback').className='feedback';$('feedback').textContent='Elegí una opción.';$('nextBtn').hidden=true;s.options.forEach(([label,ok,msg])=>{const b=document.createElement('button');b.className='choice';b.textContent=label;b.onclick=()=>choose(b,ok,msg);$('choices').appendChild(b)});updateStats()}
function choose(btn,ok,msg){if(answered)return;if(ok){answered=true;btn.classList.add('correct');decisionPoints+=10;points+=10;$('feedback').className='feedback ok';$('feedback').textContent='✓ '+msg;[...$('choices').children].forEach(x=>x.disabled=true);$('nextBtn').hidden=false}else{mistakes++;btn.classList.add('wrong');btn.disabled=true;$('feedback').className='feedback bad';$('feedback').textContent='Revisá: '+msg;updateStats()}}
$('nextBtn').onclick=()=>{if(step<steps.length-1){step++;renderStep()}else{showTrainer()}};
function showTrainer(){$('decisionPanel').classList.add('hidden');$('trainer').classList.remove('hidden');$('sceneText').textContent='Empezás RCP en el centro del pecho mientras llega el DEA.';step=4;updateStats()}
function compress(){if(taps.length>=30)return;const now=performance.now();taps.push(now);$('compressionCount').textContent=taps.length;$('compressBtn').classList.add('pressed');setTimeout(()=>$('compressBtn').classList.remove('pressed'),80);let rate=null;if(taps.length>=4){const first=Math.max(0,taps.length-10);const dt=(taps[taps.length-1]-taps[first])/1000;rate=((taps.length-1-first)/dt)*60;$('bpm').textContent=Math.round(rate);const pos=Math.max(0,Math.min(100,(rate-60)/100*100));$('needle').style.left=pos+'%';$('rhythmStatus').textContent=rate>=100&&rate<=120?'En objetivo':rate<100?'Muy lento':'Muy rápido'}if(taps.length===30){const dt=(taps[29]-taps[0])/1000;const avg=29/dt*60;compressionPoints=avg>=100&&avg<=120?30:(avg>=90&&avg<=130?20:10);points+=compressionPoints;$('trainerFeedback').innerHTML=`<b>Resultado:</b> ritmo promedio estimado de <b>${Math.round(avg)}/min</b>. ${avg>=100&&avg<=120?'Estás dentro del objetivo de 100–120/min.':'El objetivo es 100–120/min; repetí el ejercicio luego para afinar el ritmo.'}`;$('trainerNext').hidden=false;updateStats()}}
$('compressBtn').onclick=compress;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!$('trainer').classList.contains('hidden')){e.preventDefault();compress()}});$('trainerNext').onclick=showAed;
function showAed(){$('trainer').classList.add('hidden');$('aedPanel').classList.remove('hidden');$('sceneText').textContent='Llega un DEA. Mantené la secuencia segura y seguí sus indicaciones.';step=5;updateStats()}
$('aedPower').onclick=()=>{if($('aedPower').disabled)return;$('aedPower').disabled=true;$('aedS1').classList.add('done');$('padsBtn').disabled=false;$('aedScreen').textContent='COLOQUE LOS PARCHES EN EL TÓRAX DESNUDO SEGÚN LOS DIBUJOS.';aedPoints+=6;points+=6;updateStats()};$('powerHint').onclick=()=>$('aedPower').click();
$('padsBtn').onclick=()=>{$('padsBtn').disabled=true;$('aedS2').classList.add('done');$('clearBtn').disabled=false;$('aedScreen').textContent='ANALIZANDO RITMO. NO TOQUE AL PACIENTE.';aedPoints+=6;points+=6;updateStats()};
$('clearBtn').onclick=()=>{$('clearBtn').disabled=true;$('aedS3').classList.add('done');$('aedShock').disabled=false;$('aedScreen').textContent='DESCARGA INDICADA. ASEGÚRESE DE QUE NADIE TOQUE AL PACIENTE.';aedPoints+=6;points+=6;updateStats()};
$('aedShock').onclick=()=>{if($('aedShock').disabled)return;$('aedShock').disabled=true;$('aedS4').classList.add('done');$('resumeBtn').disabled=false;$('aedScreen').textContent='DESCARGA REALIZADA. REANUDE RCP INMEDIATAMENTE.';aedPoints+=6;points+=6;updateStats()};
$('resumeBtn').onclick=()=>{$('resumeBtn').disabled=true;$('aedS5').classList.add('done');$('aedScreen').textContent='CONTINÚE RCP DURANTE 2 MINUTOS Y SIGA LAS INDICACIONES DEL DEA.';aedPoints+=6;points+=6;$('finishBtn').hidden=false;updateStats()};
$('finishBtn').onclick=finish;
function finish(){$('aedPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden');$('sceneText').textContent='Simulación terminada. Revisá tu devolución y repetí para mejorar.';$('finalScore').textContent=points;$('decisionScore').textContent=`${decisionPoints}/40`;$('compressionScore').textContent=`${compressionPoints}/30`;$('aedScore').textContent=`${aedPoints}/30`;let msg=points>=90?'Muy buen desempeño en esta práctica. Repetila sin mirar las ayudas y complementala con un curso presencial para entrenar técnica y profundidad reales.':points>=70?'Buen comienzo. Repetí especialmente el entrenador de compresiones hasta sostener 100–120/min de forma estable.':'Conviene repetir la secuencia desde el principio. El objetivo es reconocer rápido, activar ayuda, iniciar compresiones y usar el DEA sin demoras.';$('resultMessage').textContent=msg;step=5;updateStats(true)}
function updateStats(done=false){$('pointsStat').textContent=points;$('mistakeStat').textContent=mistakes;$('stepStat').textContent=done?'6/6':`${Math.min(step+1,6)}/6`;$('progressBar').style.width=(done?100:Math.min(100,(step/5)*100))+'%'}
$('restartBtn').onclick=()=>location.reload();renderStep();
