/* Nextfuture V3.6 — cierre técnico, casos reales y opiniones verificadas */
const NF_CASE_ACTION=`${SB}/functions/v1/nextfuture-case-action`;
const NF_CAUSE_LABELS={battery:'Batería',charging:'Carga / puerto',display:'Pantalla / táctil',thermal:'Temperatura / refrigeración',software:'Software / sistema',storage:'Almacenamiento',network:'Conectividad',audio:'Audio',input:'Controles / periféricos',camera:'Cámara',board:'Placa / electrónica',physical:'Daño físico',power:'Alimentación / fuente',other:'Otro'};
const NF_MATCH_LABELS={matched:'Coincidió',partial:'Coincidió parcialmente',different:'La causa fue diferente',not_applicable:'No hubo diagnóstico previo',unknown:'Sin evaluar'};
const nfV36PrevOpen=openOrder;
openOrder=function(code){nfV36PrevOpen(code);setTimeout(()=>nfV36CloseBox(code),70)};

async function nfCaseCall(body){return call(NF_CASE_ACTION,body)}
function nfStars(n){return '★'.repeat(Number(n)||0)+'☆'.repeat(Math.max(0,5-(Number(n)||0)))}
function nfV36CloseBox(code){
 const o=O.find(x=>x.order_code===code),body=$('#drawerBody');if(!o||!body||$('#nfCaseCloseBox'))return;
 if(!['delivered'].includes(o.order_status)&&!o.outcome&&!o.review)return;
 const out=o.outcome||{},rev=o.review||{};
 const cats=Object.entries(NF_CAUSE_LABELS).map(([k,v])=>`<option value="${k}" ${out.final_cause_category===k?'selected':''}>${v}</option>`).join('');
 const matches=Object.entries(NF_MATCH_LABELS).map(([k,v])=>`<option value="${k}" ${(out.diagnostic_match||'unknown')===k?'selected':''}>${v}</option>`).join('');
 const reviewHtml=o.review?`<div class="nf36-review-admin"><div class="nf36-review-top"><b>${nfStars(rev.rating)} · ${esc(rev.display_name||'Cliente')}</b><span class="pill">${esc(rev.moderation_status)}</span></div><p>${esc(rev.comment||'Sin comentario escrito.')}</p><small>${rev.publish_consent?'Autorizó publicación':'Devolución privada · no autorizó publicación'}${rev.show_name?' · autorizó nombre abreviado':''}</small>${rev.moderation_status==='pending'&&rev.publish_consent?`<div class="row-actions"><button class="btn primary" id="nfPublishReview">Publicar opinión</button><button class="btn" id="nfHideReview">Ocultar por privacidad/moderación</button></div>`:''}</div>`:`<div class="nf36-awaiting"><b>Todavía no dejó una devolución.</b><p>Podés compartir nuevamente el comprobante: el formulario aparece automáticamente después de la entrega.</p></div>`;
 body.insertAdjacentHTML('beforeend',`<div class="box nf36-close" id="nfCaseCloseBox"><div class="nf36-close-head"><div><span class="kicker">CIERRE DEL CASO</span><h3>Resultado técnico y experiencia del cliente</h3></div>${o.closed_at?'<span class="nf36-closed">ARCHIVADO</span>':''}</div><div class="form-grid"><div class="field"><label>Causa final</label><select id="nfCauseCat">${cats}</select></div><div class="field"><label>Diagnóstico previo</label><select id="nfDiagMatch">${matches}</select></div><div class="field full"><label>Qué causaba realmente la falla</label><textarea id="nfFinalCause">${esc(out.final_cause||o.diagnosis||'')}</textarea></div><div class="field full"><label>Qué se hizo para resolverla</label><textarea id="nfRepairSummary">${esc(out.repair_summary||o.work_planned||'')}</textarea></div><div class="field full"><label>Título público del caso</label><input id="nfPublicTitle" value="${esc(out.public_case_title||'')}", placeholder="Ej: Moto G52 que no cargaba"></div><div class="field full"><label>Resumen público · sin datos personales</label><textarea id="nfPublicSummary" placeholder="Problema, causa confirmada y solución. Sin nombre, teléfono, IMEI ni dirección.">${esc(out.public_case_summary||'')}</textarea></div></div><label class="nf36-check"><input type="checkbox" id="nfPublishCase" ${out.publish_case?'checked':''}><span><b>Mostrar este caso en la página</b><small>Sólo equipo, problema técnico y solución. Nunca datos del cliente.</small></span></label><div class="row-actions"><button class="btn primary" id="nfSaveOutcome">Guardar resultado técnico</button><button class="btn" id="nfCopyFeedback">Copiar enlace de devolución</button>${o.order_status==='delivered'&&!o.closed_at?'<button class="btn dark" id="nfCloseCase">Archivar caso</button>':''}</div><div id="nfOutcomeMsg" class="msg"></div><div class="mgmt-divider"></div><h3>Devolución del cliente</h3>${reviewHtml}</div>`);
 $('#nfSaveOutcome')?.addEventListener('click',()=>nfSaveOutcome(code));
 $('#nfCopyFeedback')?.addEventListener('click',()=>navigator.clipboard?.writeText(String(rurl(o))).then(()=>toast('Enlace de devolución copiado')));
 $('#nfCloseCase')?.addEventListener('click',()=>nfCloseCase(code));
 $('#nfPublishReview')?.addEventListener('click',()=>nfModerateReview(code,rev.id,'published'));
 $('#nfHideReview')?.addEventListener('click',()=>nfModerateReview(code,rev.id,'hidden'));
}
async function nfSaveOutcome(code){msg('#nfOutcomeMsg','Guardando…');try{await nfCaseCall({action:'record_outcome',order_code:code,final_cause_category:$('#nfCauseCat').value,final_cause:$('#nfFinalCause').value.trim(),repair_summary:$('#nfRepairSummary').value.trim(),diagnostic_match:$('#nfDiagMatch').value,public_case_title:$('#nfPublicTitle').value.trim()||null,public_case_summary:$('#nfPublicSummary').value.trim()||null,publish_case:$('#nfPublishCase').checked});toast('Resultado técnico guardado');await load();openOrder(code)}catch(e){msg('#nfOutcomeMsg',e.message,true)}}
async function nfModerateReview(code,id,status){try{await nfCaseCall({action:'moderate_review',review_id:id,status});toast(status==='published'?'Opinión publicada':'Opinión oculta');await load();openOrder(code)}catch(e){toast(e.message)}}
async function nfCloseCase(code){msg('#nfOutcomeMsg','Cerrando caso…');try{await nfCaseCall({action:'close_case',order_code:code});toast('Caso archivado');await load();openOrder(code)}catch(e){msg('#nfOutcomeMsg',e.message,true)}}

const nfOldBusinessStats=nfRenderBusinessStats;
nfRenderBusinessStats=function(){nfOldBusinessStats();const s=$('#stats');if(!s)return;s.insertAdjacentHTML('beforeend',`<div class="stat"><small>Opiniones pendientes</small><b>${esc(NF_BUSINESS.pending_reviews||0)}</b></div><div class="stat"><small>Casos cerrados</small><b>${esc(NF_BUSINESS.closed_cases||0)}</b></div>${NF_BUSINESS.average_rating!=null?`<div class="stat"><small>Valoración publicada</small><b>${Number(NF_BUSINESS.average_rating).toFixed(1)} ★</b></div>`:''}`)};