(() => {
  const MODULES={
    iv:{icon:'💧',title:'Control de acceso periférico',subtitle:'Observación · seguridad · registro',warning:'Este taller no enseña inserción ni manipulación invasiva. Se centra en vigilancia del sitio y seguridad del dispositivo.',steps:[
      {q:'¿Qué corresponde hacer al iniciar el control?',options:['Verificar identidad, indicación y observar el sitio antes de intervenir','Retirar el acceso para revisarlo','Desconectar la línea sin indicación'],correct:0},
      {q:'¿Qué aspecto forma parte de una vigilancia segura?',options:['Observar fijación, piel, molestias y características visibles del sitio','Cubrir el sitio para no mirarlo','Ignorar lo que refiere el paciente'],correct:0},
      {q:'Si el escenario muestra un hallazgo inesperado, ¿qué corresponde?',options:['Detener acciones no indicadas, mantener seguridad y comunicar según protocolo/equipo','Modificar el dispositivo por cuenta propia','Ocultar el hallazgo para evitar alarmar'],correct:0},
      {q:'¿Cómo se completa el control?',options:['Registrar hallazgos, estado del dispositivo y acciones realizadas','No documentar si parece normal','Cambiar la indicación en el registro'],correct:0}
    ],action:'ivsite',result:'Control visual y de seguridad del acceso periférico completado.'},
    urinary:{icon:'🧴',title:'Cuidado de sistema urinario',subtitle:'Circuito cerrado · seguridad · balance',warning:'La simulación aborda cuidado y vigilancia. No incluye técnica de colocación de sonda.',steps:[
      {q:'¿Qué verificás primero?',options:['Identidad, indicación y estado general antes de revisar el sistema','Abrir el circuito para comprobarlo','Vaciar el sistema sin registrar'],correct:0},
      {q:'¿Qué condición general debe preservarse en el cuidado simulado?',options:['Mantener el sistema cerrado y seguro según protocolo','Desconectarlo regularmente','Colocar la bolsa sobre la cama'],correct:0},
      {q:'¿Qué información aporta al balance?',options:['Volumen observado y características relevantes registradas en el escenario','Una estimación sin medir','Solo la hora de control'],correct:0},
      {q:'¿Qué completa el procedimiento?',options:['Registrar, mantener seguridad y comunicar hallazgos relevantes','Omitir el registro si no hay molestias','Modificar la indicación del sistema'],correct:0}
    ],action:'urinary',result:'Vigilancia del sistema urinario y registro de balance completados.'}
  };
  const AVAILABLE={'dispositivos-01':['iv','urinary'],'quirurgico-01':['iv']};
  let active=null,step=0,completed=new Set(),errors=0,originalLoadCase=null;
  function ensureStyles(){if(document.querySelector('link[data-device-care-styles]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./device-care.css';l.dataset.deviceCareStyles='true';document.head.appendChild(l)}
  function ids(){return AVAILABLE[currentCase?.id]||[]}
  function mount(){ensureStyles();const anchor=document.querySelector('.advancedProcedureWorkshop')||document.querySelector('.procedureWorkshop')||document.querySelector('.bedsideLab');if(!anchor||document.querySelector('.deviceCareWorkshop'))return;const s=document.createElement('section');s.className='deviceCareWorkshop';anchor.insertAdjacentElement('afterend',s);render()}
  function render(){const root=document.querySelector('.deviceCareWorkshop');if(!root||!currentCase)return;const available=ids();if(!available.length){root.hidden=true;root.innerHTML='';return}root.hidden=false;root.innerHTML=`<div class="deviceCareHead"><div><span class="eyebrow">Cuidados de dispositivos</span><h3>Vigilancia y seguridad</h3><p>Practicá controles de enfermería sin realizar inserciones ni técnicas invasivas.</p></div><span>${completed.size}/${available.length}</span></div><div class="deviceCareCards">${available.map(id=>{const m=MODULES[id],done=completed.has(id);return `<button class="deviceCard ${done?'done':''}" data-device-care="${id}"><span>${m.icon}</span><b>${m.title}</b><small>${m.subtitle}</small><em>${done?'✓ Completado':'Practicar →'}</em></button>`}).join('')}</div><div id="deviceStage" class="deviceStage ${active?'open':''}"></div>`;root.querySelectorAll('[data-device-care]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.deviceCare)));if(active)renderStage()}
  function open(id){if(!MODULES[id])return;active=id;step=0;errors=0;render();document.querySelector('#deviceStage')?.scrollIntoView({behavior:'smooth',block:'nearest'})}
  function renderStage(message=''){const stage=document.querySelector('#deviceStage'),m=MODULES[active];if(!stage||!m)return;const st=m.steps[step];if(!st)return complete();stage.innerHTML=`<div class="deviceStep"><span>${m.icon}</span><div><span class="eyebrow">Paso ${step+1} de ${m.steps.length}</span><h4>${m.title}</h4><p>${st.q}</p></div></div><div class="deviceWarning">⚠️ ${m.warning}</div><div class="deviceChoices">${st.options.map((o,i)=>`<button data-device-choice="${i}">${o}</button>`).join('')}</div>${message?`<div class="deviceMsg">${message}</div>`:''}`;stage.querySelectorAll('[data-device-choice]').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.deviceChoice))))}
  function answer(index){const m=MODULES[active],st=m.steps[step];if(index!==st.correct){errors++;if(typeof state!=='undefined')state.errors++;if(typeof updateProgress==='function')updateProgress();return renderStage('Esa opción no corresponde en este punto. Revisá la secuencia.')}step++;step>=m.steps.length?complete():renderStage('✓ Paso registrado. Continuá.')}
  function complete(){const stage=document.querySelector('#deviceStage'),m=MODULES[active];completed.add(active);if(m.action&&typeof doAction==='function'&&currentCase.actions?.some(a=>a.id===m.action))doAction(m.action,'device');stage.innerHTML=`<div class="deviceDone"><span>✓</span><div><span class="eyebrow">Control completado</span><h4>${m.title}</h4><p>${m.result}</p><small>Intentos a revisar: ${errors}. Aplicá siempre el protocolo institucional correspondiente.</small></div></div>`;const root=document.querySelector('.deviceCareHead>span');if(root)root.textContent=`${completed.size}/${ids().length}`;document.querySelectorAll('[data-device-care]').forEach(b=>{if(completed.has(b.dataset.deviceCare)){b.classList.add('done');const e=b.querySelector('em');if(e)e.textContent='✓ Completado'}})}
  function reset(){active=null;step=0;completed=new Set();errors=0;document.querySelector('.deviceCareWorkshop')?.remove();setTimeout(mount,80)}
  function hook(){if(typeof loadCase!=='function'||originalLoadCase)return;originalLoadCase=loadCase;loadCase=function(id,scroll=false){const r=originalLoadCase(id,scroll);reset();return r}}
  function init(){hook();setTimeout(mount,180)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();