const SB='https://jggjrfmtpcgskusgohuj.supabase.co';
const KEY='sb_publishable_EaZVrIoJ9RQVF1O4IpgOtA_mqe9aO4k';
const CATS=[['electricista','Electricista'],['plomero','Plomero'],['cerrajero','Cerrajero'],['tecnico','Técnico PC'],['herrero','Herrero'],['aire','Aire acondicionado'],['pintor','Pintor'],['abogado','Abogado'],['contador','Contador'],['otro','Otro servicio']];
const LOCS=['Moreno','Paso del Rey','Merlo','Ituzaingó','Morón','Hurlingham','La Matanza'];
const S={session:null,user:null,profile:null,provider:null,requests:[],opps:[],jobs:[],job:null,admin:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}):'—';
const status=s=>({draft:'Borrador',searching:'Buscando',offered:'Ofertas enviadas',assigned:'Asignado',converted:'Convertido',accepted:'Aceptado',negotiating:'Negociando',awaiting_payment:'Esperando pago',scheduled:'Programado',en_route:'En camino',arrived:'Llegó',working:'Trabajando',review:'Esperando conformidad',completed:'Finalizado',cancelled:'Cancelado',refunded:'Devuelto',pending:'Pendiente',verified:'Verificado',observed:'Observado',rejected:'Rechazado',offline:'Desconectado',available:'Disponible',busy:'Ocupado'})[s]||s||'—';
function toast(t){const x=$('#toast');x.textContent=t;x.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.add('hidden'),3200)}
function saveSession(d){S.session={access_token:d.access_token,refresh_token:d.refresh_token};localStorage.setItem('cerca_live_session',JSON.stringify(S.session))}
function clearSession(){S.session=null;S.user=null;S.profile=null;localStorage.removeItem('cerca_live_session')}
function loadSaved(){try{S.session=JSON.parse(localStorage.getItem('cerca_live_session')||'null')}catch(_){S.session=null}}
async function refresh(){if(!S.session?.refresh_token)throw new Error('Sesión vencida');const r=await fetch(`${SB}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({refresh_token:S.session.refresh_token})});const d=await r.json();if(!r.ok)throw new Error('Sesión vencida');saveSession(d);return d}
async function req(url,opt={},retry=true){const h={...(opt.headers||{}),'apikey':KEY};if(S.session?.access_token)h.Authorization=`Bearer ${S.session.access_token}`;const r=await fetch(url,{...opt,headers:h});if(r.status===401&&retry&&S.session?.refresh_token){await refresh();return req(url,opt,false)}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error_description||d.msg||d.message||d.error||`Error ${r.status}`);return d}
async function edge(slug,body){return req(`${SB}/functions/v1/${slug}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function authUser(){const d=await req(`${SB}/auth/v1/user`);S.user=d;const p=await req(`${SB}/rest/v1/profiles?select=id,role,full_name,locality,is_active&id=eq.${d.id}`,{headers:{Accept:'application/json'}});S.profile=p[0]||null;if(!S.profile)throw new Error('No encontramos el perfil');return S.profile}
function fillSelect(id,items){const e=$(id);if(e&&!e.dataset.ready){e.innerHTML=items.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('');e.dataset.ready='1'}}
function fillLocality(id){const e=$(id);if(e&&!e.dataset.ready){e.innerHTML=LOCS.map(x=>`<option>${esc(x)}</option>`).join('');e.dataset.ready='1'}}
function showAuth(mode='login'){$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden');$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===mode));$('#loginForm').classList.toggle('hidden',mode!=='login');$('#signupForm').classList.toggle('hidden',mode!=='signup')}
function showApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#who').textContent=`${S.profile.full_name||S.user.email} · ${status(S.profile.role)}`;renderTabs();go('home')}
function renderTabs(){const role=S.profile?.role;$('#providerTab').classList.toggle('hidden',role!=='provider');$('#adminTab').classList.toggle('hidden',role!=='admin')}
function go(view){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${view}View`)?.classList.remove('hidden');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='home')loadCustomer();if(view==='provider')loadProvider();if(view==='jobs')loadJobs();if(view==='admin')loadAdmin()}
async function login(e){e.preventDefault();const b=$('#loginBtn');b.disabled=true;try{const d=await req(`${SB}/auth/v1/token?grant_type=password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value})},false);saveSession(d);await authUser();showApp();await loadAll();toast('Sesión iniciada')}catch(err){toast(err.message)}finally{b.disabled=false}}
async function signup(e){e.preventDefault();const b=$('#signupBtn');b.disabled=true;try{const body={email:$('#signupEmail').value.trim(),password:$('#signupPassword').value,data:{full_name:$('#signupName').value.trim(),locality:$('#signupLocality').value,requested_role:$('#signupRole').value}};const d=await req(`${SB}/auth/v1/signup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},false);if(d.access_token){saveSession(d);await authUser();showApp();await loadAll();toast('Cuenta creada')}else{toast('Cuenta creada. Confirmá el correo y luego iniciá sesión.');showAuth('login')}}catch(err){toast(err.message)}finally{b.disabled=false}}
function logout(){clearSession();showAuth('login')}
async function boot(){fillSelect('#reqCategory',CATS);fillLocality('#reqLocality');fillLocality('#signupLocality');fillLocality('#proBase');loadSaved();if(!S.session){showAuth('login');return}try{await authUser();showApp();await loadAll()}catch(_){clearSession();showAuth('login')}}
async function loadAll(){await Promise.allSettled([loadRequests(),loadJobs(),S.profile.role==='provider'?loadProvider():Promise.resolve(),S.profile.role==='admin'?loadAdmin():Promise.resolve()])}

async function createRequest(e){e.preventDefault();const custom=$('#reqCategory').value==='otro'?$('#reqCustom').value.trim():null;try{const d=await edge('cerca-requests',{action:'create',category_slug:$('#reqCategory').value,custom_category:custom,title:$('#reqTitle').value.trim(),description:$('#reqDesc').value.trim(),locality:$('#reqLocality').value,urgency:$('#reqUrgency').value,service_mode:$('#reqMode').value});toast(`Solicitud ${d.request.public_code} creada`);e.target.reset();fillSelect('#reqCategory',CATS);fillLocality('#reqLocality');await loadRequests()}catch(err){toast(err.message)}}
async function loadRequests(){if(!S.session||S.profile?.role==='provider')return;try{const d=await edge('cerca-requests',{action:'my_requests'});S.requests=d.requests||[];renderRequests()}catch(err){console.error(err)}}
function renderRequests(){const box=$('#requestsList');if(!box)return;if(!S.requests.length){box.innerHTML='<div class="empty">Todavía no hay solicitudes reales.</div>';return}box.innerHTML=S.requests.map(r=>{const active=(r.matches||[]).filter(m=>['offered','viewed'].includes(m.status)).length;return `<article class="item"><div class="item-head"><div><span class="eyebrow">${esc(r.public_code)}</span><h4>${esc(r.category?.name||r.custom_category||r.title)}</h4><div class="muted">${esc(r.description)}</div></div><span class="pill">${esc(status(r.job?.status||r.status))}</span></div><div class="meta"><span>📍 ${esc(r.locality)}</span><span>${active} ofertas activas</span><span>Ronda ${r.matching_round||1}</span></div>${r.job?`<div class="item-actions"><button class="btn primary" data-job="${r.job.id}">Abrir trabajo</button></div>`:''}</article>`}).join('');bindJobButtons(box)}

function proChecks(selected=[]){return CATS.filter(x=>x[0]!=='otro').map(([s,n])=>`<label class="check"><input type="checkbox" value="${s}" ${selected.includes(s)?'checked':''}> ${esc(n)}</label>`).join('')}
function covChecks(selected=[]){return LOCS.map(n=>`<label class="check"><input type="checkbox" value="${esc(n)}" ${selected.includes(n)?'checked':''}> ${esc(n)}</label>`).join('')}
async function loadProvider(){if(S.profile?.role!=='provider')return;try{const d=await edge('cerca-provider-profile',{action:'get'});S.provider=d;renderProvider();await loadOpps()}catch(err){toast(err.message)}}
function renderProvider(){const d=S.provider||{},p=d.profile||{};$('#proName').value=p.public_name||S.profile.full_name||'';$('#proBio').value=p.bio||'';$('#proBase').value=p.base_locality||S.profile.locality||'Moreno';$('#proRadius').value=p.max_radius_km??20;$('#proVisit').value=p.visit_price??0;$('#proAvail').value=p.availability_status||'offline';$('#proStatus').textContent=status(p.verification_status||'draft');const sv=(d.services||[]).map(x=>x.category?.slug).filter(Boolean);const cv=(d.coverage||[]).map(x=>x.locality);$('#proServices').innerHTML=proChecks(sv);$('#proCoverage').innerHTML=covChecks(cv)}
async function saveProvider(e){e.preventDefault();const services=$$('#proServices input:checked').map(x=>x.value),coverage=$$('#proCoverage input:checked').map(x=>x.value);try{const d=await edge('cerca-provider-profile',{action:'save',public_name:$('#proName').value.trim(),bio:$('#proBio').value.trim(),base_locality:$('#proBase').value,max_radius_km:Number($('#proRadius').value||0),visit_price:Number($('#proVisit').value||0),availability_status:$('#proAvail').value,service_slugs:services,coverage});S.provider=d;renderProvider();toast('Perfil guardado')}catch(err){toast(err.message)}}
async function submitReview(){try{await edge('cerca-provider-profile',{action:'submit_review'});toast('Perfil enviado a revisión');await loadProvider()}catch(err){toast(err.message.includes('identity')?'Para producción se exige documento de identidad. Para nuestra cuenta demo avisame y la habilito para la prueba.':err.message)}}
async function loadOpps(){if(S.profile?.role!=='provider')return;try{const d=await edge('cerca-requests',{action:'opportunities'});S.opps=d.opportunities||[];renderOpps()}catch(err){console.error(err)}}
function renderOpps(){const box=$('#oppsList');if(!box)return;if(!S.opps.length){box.innerHTML='<div class="empty">No hay oportunidades activas para esta cuenta.</div>';return}box.innerHTML=S.opps.map(o=>{const r=o.request||{};return `<article class="item"><div class="item-head"><div><span class="eyebrow">MATCH ${Math.round(Number(o.score||0))}%</span><h4>${esc(r.category?.name||r.custom_category||r.title)}</h4><div class="muted">${esc(r.description)}</div></div><span class="pill">${esc(r.locality||'')}</span></div><div class="meta"><span>${esc(r.urgency||'')}</span><span>vence ${date(o.expires_at)}</span></div><div class="item-actions"><button class="btn primary" data-opp="${o.id}" data-decision="accept">Aceptar</button><button class="btn outline" data-opp="${o.id}" data-decision="decline">No puedo</button></div></article>`}).join('');$$('[data-opp]').forEach(b=>b.onclick=()=>respondOpp(b.dataset.opp,b.dataset.decision))}
async function respondOpp(id,decision){try{const d=await edge('cerca-requests',{action:'respond',match_id:id,decision});toast(decision==='accept'?'Trabajo aceptado':'Oportunidad rechazada');await Promise.all([loadOpps(),loadJobs()]);if(d.job?.job_id)openJob(d.job.job_id)}catch(err){toast(err.message)}}

async function loadJobs(){if(!S.session)return;try{const d=await edge('cerca-job-list',{action:'list'});S.jobs=d.jobs||[];renderJobs()}catch(err){console.error(err)}}
function renderJobs(){const box=$('#jobsList');if(!box)return;if(!S.jobs.length){box.innerHTML='<div class="empty">Todavía no hay trabajos asignados.</div>';return}box.innerHTML=S.jobs.map(j=>`<article class="item"><div class="item-head"><div><span class="eyebrow">${esc(j.public_code)}</span><h4>${esc(j.request?.category?.name||j.request?.custom_category||j.request?.title||'Servicio')}</h4><div class="muted">${esc(j.request?.locality||'')} · ${date(j.updated_at)}</div></div><span class="pill">${esc(status(j.status))}</span></div><div class="meta">${Number(j.agreed_total||0)>0?`<span>${money(j.agreed_total)}</span>`:''}<span>Comisión ${Number(j.commission_pct||10)}%</span></div><div class="item-actions"><button class="btn primary" data-job="${j.id}">Abrir</button></div></article>`).join('');bindJobButtons(box)}
function bindJobButtons(root=document){root.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>openJob(b.dataset.job))}
async function openJob(id){$('#jobModal').classList.remove('hidden');$('#jobBody').innerHTML='<div class="empty">Cargando trabajo…</div>';try{const d=await edge('cerca-job',{action:'get',job_id:id});S.job=d;renderJob()}catch(err){$('#jobBody').innerHTML=`<div class="empty">${esc(err.message)}</div>`}}
function roleJob(){if(!S.job)return'guest';if(S.job.job.provider_id===S.user.id)return'provider';if(S.job.job.customer_id===S.user.id)return'customer';return S.profile.role==='admin'?'admin':'guest'}
function renderMessages(){return (S.job.messages||[]).map(m=>m.system_message?`<div class="msg sys">${esc(m.body)}<small>${date(m.created_at)}</small></div>`:`<div class="msg ${m.sender_id===S.user.id?'mine':''}">${esc(m.body)}<small>${m.sender_id===S.user.id?'Vos':'Otra parte'} · ${date(m.created_at)}</small></div>`).join('')||'<div class="empty">Todavía no hay mensajes.</div>'}
function quoteCard(q){const r=roleJob(),act=r==='customer'&&['sent','revision_requested'].includes(q.status);return `<div class="quote ${q.status==='accepted'?'accepted':''}"><div class="split"><b>Presupuesto v${q.version}</b><span class="pill">${esc(q.status)}</span></div><div class="money">${money(q.total_amount)}</div><div class="quote-grid"><span>Visita ${money(q.visit_amount)}</span><span>Mano de obra ${money(q.labor_amount)}</span><span>Materiales ${money(q.materials_amount)}</span><span>Extras ${money(q.extra_amount)}</span></div>${q.note?`<div class="muted">${esc(q.note)}</div>`:''}${act?`<div class="item-actions"><button class="btn primary" data-q="${q.id}" data-qa="accept">Aceptar</button><button class="btn outline" data-q="${q.id}" data-qa="revision">Pedir cambio</button><button class="btn danger" data-q="${q.id}" data-qa="reject">Rechazar</button></div>`:''}</div>`}
function paymentSummary(){const j=S.job.job,rows=S.job.payments||[],held=rows.filter(p=>['initial','additional'].includes(p.payment_type)&&p.status==='held').reduce((a,p)=>a+Number(p.amount),0),payout=rows.filter(p=>p.payment_type==='payout'&&p.status==='released').reduce((a,p)=>a+Number(p.amount),0),fee=rows.filter(p=>p.payment_type==='platform_fee'&&p.status==='released').reduce((a,p)=>a+Number(p.amount),0),pct=Number(j.commission_pct||10),gross=Number(j.agreed_total||0),netExpected=gross-gross*pct/100;let action='';const r=roleJob();if(r==='customer'&&j.status==='awaiting_payment')action=`<button class="btn primary" id="payNow">Simular pago protegido ${money(gross)}</button>`;if(r==='customer'&&j.status==='review')action='<button class="btn primary" id="releaseNow">Confirmar conformidad y liberar</button>';return `<div class="paybox"><h3>Pago protegido · sandbox</h3><div class="paygrid"><div><small>Total</small><b>${money(gross)}</b></div><div><small>Retenido</small><b>${money(held)}</b></div><div><small>Neto prestador</small><b>${money(payout||netExpected)}</b></div><div><small>Comisión Cerca</small><b>${money(fee||gross*pct/100)}</b></div></div><div class="muted">No mueve dinero real. Registra retención y liquidación en Supabase.</div><div class="item-actions">${action}</div></div>`}
function providerQuoteBuilder(){if(roleJob()!=='provider'||['completed','cancelled','refunded'].includes(S.job.job.status))return'';return `<div class="card"><h3>Enviar presupuesto</h3><div class="form"><div class="field"><label>Visita</label><input id="qVisit" type="number" min="0" value="0"></div><div class="field"><label>Mano de obra</label><input id="qLabor" type="number" min="0" value="0"></div><div class="field"><label>Materiales</label><input id="qMat" type="number" min="0" value="0"></div><div class="field"><label>Extras</label><input id="qExtra" type="number" min="0" value="0"></div><div class="field full"><label>Detalle</label><textarea id="qNote" rows="3"></textarea></div></div><button class="btn primary" id="sendQuote">Enviar presupuesto</button></div>`}
function statusActions(){if(roleJob()!=='provider')return'';const s=S.job.job.status,m={scheduled:['en_route','Marcar en camino'],en_route:['arrived','Marcar llegada'],arrived:['working','Comenzar trabajo'],working:['review','Enviar a conformidad']};return m[s]?`<button class="btn primary" data-status="${m[s][0]}">${m[s][1]}</button>`:''}
function renderJob(){const d=S.job,j=d.job,r=d.request||{},other=roleJob()==='provider'?(d.customer?.full_name||'Cliente'):(d.provider?.public_name||'Prestador');$('#jobBody').innerHTML=`<div class="job-head"><div><span class="eyebrow">${esc(j.public_code)}</span><h2>${esc(r.category?.name||r.custom_category||r.title||'Servicio')}</h2><div class="muted">${esc(other)} · ${esc(r.locality||'')} · ${esc(status(j.status))}</div></div><button class="btn outline" id="refreshJob">Actualizar</button></div><div class="job-cols"><div><div class="card"><h3>Chat</h3><div class="chat" id="chat">${renderMessages()}</div><div class="chat-send"><input id="chatText" placeholder="Escribí un mensaje"><button class="btn primary" id="sendMsg">Enviar</button></div></div><div class="card"><h3>Presupuestos</h3>${(d.quotes||[]).length?d.quotes.map(quoteCard).join(''):'<div class="empty">Todavía no hay presupuesto.</div>'}</div></div><div>${providerQuoteBuilder()}<div class="card"><h3>Estado del trabajo</h3><div class="muted">${esc(r.description||'')}</div><div class="item-actions">${statusActions()}</div></div>${paymentSummary()}</div></div>`;$('#refreshJob').onclick=()=>openJob(j.id);$('#sendMsg').onclick=sendMsg;$('#chatText').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendMsg()}};$('#sendQuote')&&($('#sendQuote').onclick=sendQuote);$$('[data-q]').forEach(b=>b.onclick=()=>respondQuote(b.dataset.q,b.dataset.qa));$$('[data-status]').forEach(b=>b.onclick=()=>setJobStatus(b.dataset.status));$('#payNow')&&($('#payNow').onclick=payNow);$('#releaseNow')&&($('#releaseNow').onclick=releaseNow);const c=$('#chat');c.scrollTop=c.scrollHeight}
async function sendMsg(){const t=$('#chatText').value.trim();if(!t)return;try{await edge('cerca-job',{action:'send_message',job_id:S.job.job.id,message:t});await openJob(S.job.job.id)}catch(err){toast(err.message)}}
async function sendQuote(){try{await edge('cerca-job',{action:'send_quote',job_id:S.job.job.id,visit_amount:Number($('#qVisit').value||0),labor_amount:Number($('#qLabor').value||0),materials_amount:Number($('#qMat').value||0),extra_amount:Number($('#qExtra').value||0),note:$('#qNote').value.trim()});toast('Presupuesto enviado');await openJob(S.job.job.id)}catch(err){toast(err.message)}}
async function respondQuote(id,decision){let note='';if(decision==='revision')note=prompt('¿Qué querés que revise?')||'';try{await edge('cerca-job',{action:'respond_quote',job_id:S.job.job.id,quote_id:id,decision,note});toast('Presupuesto actualizado');await openJob(S.job.job.id);await loadJobs()}catch(err){toast(err.message)}}
async function setJobStatus(st){try{await edge('cerca-job',{action:'set_status',job_id:S.job.job.id,status:st});await openJob(S.job.job.id);await loadJobs()}catch(err){toast(err.message)}}
async function payNow(){try{await edge('cerca-payment',{action:'simulate_pay',job_id:S.job.job.id,idempotency_key:crypto.randomUUID()});toast('Pago sandbox retenido');await openJob(S.job.job.id);await loadJobs()}catch(err){toast(err.message)}}
async function releaseNow(){try{const d=await edge('cerca-payment',{action:'confirm_completion',job_id:S.job.job.id});toast(d.settlement?`Liquidación: ${money(d.settlement.provider_payout)} prestador / ${money(d.settlement.platform_fee)} Cerca`:'Finalizado');await openJob(S.job.job.id);await loadJobs()}catch(err){toast(err.message)}}

async function loadCustomer(){if(S.profile?.role==='provider'){$('#customerTools').classList.add('hidden');return}$('#customerTools').classList.remove('hidden');await loadRequests()}
async function loadAdmin(){if(S.profile?.role!=='admin')return;try{const d=await edge('cerca-admin',{action:'dashboard'});S.admin=d;$('#adminStats').innerHTML=[['Solicitudes',d.stats.requests],['Trabajos',d.stats.jobs],['Prestadores',d.stats.providers],['Verificaciones',d.stats.pending_verifications],['Reclamos',d.stats.open_disputes],['Fondos retenidos',money(d.stats.held_amount)]].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const ps=d.pending_providers||[];$('#adminProviders').innerHTML=ps.length?ps.map(p=>`<article class="item"><div class="item-head"><div><h4>${esc(p.public_name)}</h4><div class="muted">${esc(p.base_locality||'')} · ${(p.services||[]).map(s=>esc(s.category?.name||'')).join(', ')}</div></div><span class="pill">${esc(status(p.verification_status))}</span></div><div class="meta"><span>${(p.documents||[]).length} documentos</span><span>${(p.coverage||[]).length} zonas</span></div></article>`).join(''):'<div class="empty">No hay prestadores pendientes.</div>'}catch(err){toast(err.message)}}

$$('[data-auth-tab]').forEach(b=>b.onclick=()=>showAuth(b.dataset.authTab));$('#loginForm').onsubmit=login;$('#signupForm').onsubmit=signup;$('#logoutBtn').onclick=logout;$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#requestForm').onsubmit=createRequest;$('#providerForm').onsubmit=saveProvider;$('#submitReview').onclick=submitReview;$('#refreshBtn').onclick=()=>loadAll().then(()=>toast('Datos actualizados'));$('#jobClose').onclick=()=>$('#jobModal').classList.add('hidden');$('#jobModal').onclick=e=>{if(e.target.id==='jobModal')$('#jobModal').classList.add('hidden')};boot();