(()=>{
 const heroEy=document.querySelector('.heroMain .ey');if(heroEy)heroEy.textContent='Lengua de Señas Argentina · v8';
 const handLab=document.getElementById('seguimiento-manos');
 const section=document.createElement('section');section.className='geometryLab';section.id='analizador-configuracion';section.innerHTML=`
  <div class="geometryTop"><div><span class="ey">LSA v8 · geometría de la mano</span><h2>Analizador técnico de configuración</h2><p>Usamos los 21 puntos de MediaPipe para describir geometría observable: flexión de dedos, apertura, separación y rotación en el plano. Estas medidas ayudan a comparar tu propia ejecución, pero todavía no identifican ni califican una seña de LSA.</p></div><div class="v8Pills"><span>Sin nueva cámara</span><span>Usa landmarks v7</span><span>Referencias locales</span></div></div>
  <div class="geometryGrid"><div class="geometryPanel"><div class="geometryHead"><div><h3>Configuración actual</h3><small id="v8LiveHint">Activá el seguimiento v7 y mostrale una mano a la cámara.</small></div><select id="v8HandSelect" disabled><option value="0">Mano 1</option></select></div>
   <div class="handSummary"><div class="summaryTile"><span>Lateralidad estimada</span><strong id="v8Handedness">—</strong></div><div class="summaryTile"><span>Apertura</span><strong id="v8OpenLabel">—</strong></div><div class="summaryTile"><span>Separación</span><strong id="v8SpreadLabel">—</strong></div><div class="summaryTile"><span>Rotación 2D</span><strong id="v8Rotation">—</strong></div></div>
   <div class="fingerStates" id="v8FingerStates"><div class="fingerChip"><b>Pulgar</b><span>—</span></div><div class="fingerChip"><b>Índice</b><span>—</span></div><div class="fingerChip"><b>Medio</b><span>—</span></div><div class="fingerChip"><b>Anular</b><span>—</span></div><div class="fingerChip"><b>Meñique</b><span>—</span></div></div>
   <div class="featureBars"><div class="featureRow"><label>Apertura</label><div class="featureTrack"><i id="v8OpenBar"></i></div><output id="v8OpenValue">—</output></div><div class="featureRow"><label>Separación</label><div class="featureTrack"><i id="v8SpreadBar"></i></div><output id="v8SpreadValue">—</output></div><div class="featureRow"><label>Pulgar–índice</label><div class="featureTrack"><i id="v8PinchBar"></i></div><output id="v8PinchValue">—</output></div><div class="featureRow"><label>Escala en cuadro</label><div class="featureTrack"><i id="v8ScaleBar"></i></div><output id="v8ScaleValue">—</output></div></div>
   <div class="geometryNote"><b>Importante:</b> “extendido”, “intermedio” y “flexionado” describen ángulos geométricos aproximados de los dedos. No significan que una configuración pertenezca a una letra o seña determinada.</div>
  </div>
  <aside class="referencePanel"><h3>Referencias técnicas personales</h3><p>Después de estudiar una configuración en una fuente validada, podés guardar solamente sus medidas geométricas para compararte más tarde. No se guarda foto ni video.</p><div class="referenceForm"><input id="v8ReferenceName" maxlength="40" placeholder="Ej.: práctica después de CAS"><button id="v8SaveReference" disabled>Guardar configuración actual</button></div><div class="referenceList" id="v8ReferenceList"></div>
   <div class="compareBox"><b>Comparar con una referencia</b><select id="v8ReferenceSelect"><option value="">Elegí una referencia</option></select><button class="compareButton" id="v8Compare" disabled>Comparar geometría</button><div class="similarityScore" id="v8Similarity">—</div><div class="similarityBar"><i id="v8SimilarityBar"></i></div><p class="compareText" id="v8CompareText">La similitud compara proporciones y ángulos de una configuración estática. No evalúa movimiento, ubicación corporal, expresión facial ni gramática.</p></div>
   <div class="v8Stats"><div><b id="v8SavedCount">0</b><span>referencias guardadas</span></div><div><b id="v8CompareCount">0</b><span>comparaciones</span></div><div><b id="v8BestSimilarity">0%</b><span>mejor similitud técnica</span></div></div>
  </aside><div class="privacyGeometry"><b>Qué se almacena:</b> únicamente números derivados de los landmarks —ángulos, proporciones y rotación— cuando vos tocás “Guardar”. No almacenamos landmarks crudos, imágenes ni video. Estas referencias son personales y permanecen en este navegador.</div></div>`;
 if(handLab)handLab.insertAdjacentElement('afterend',section);else{const visual=document.getElementById('comprension-visual');if(visual)visual.insertAdjacentElement('afterend',section)}
 const roadmap=document.querySelector('.visionRoadmap .visionSteps');if(roadmap)roadmap.innerHTML=`<div class="visionStep done"><b>✓ v6 · Calidad de imagen</b><span>Luz, estabilidad y movimiento.</span></div><div class="visionStep done"><b>✓ v7 · Manos y articulaciones</b><span>21 landmarks por mano y tracking.</span></div><div class="visionStep currentV8"><b>● v8 · Configuración geométrica</b><span>Dedos, apertura, separación y referencias propias.</span></div><div class="visionStep"><b>Próximo · Secuencias</b><span>Trayectorias temporales y cambios de configuración.</span></div>`;

 const byId=id=>document.getElementById(id);let latestFrame=null,current=null,selectedHand=0,lastRender=0;
 const fingerDefs=[['Pulgar',[2,3,4]],['Índice',[5,6,8]],['Medio',[9,10,12]],['Anular',[13,14,16]],['Meñique',[17,18,20]]];
 const dist=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
 function angle(a,b,c){if(!a||!b||!c)return 0;const v1=[a.x-b.x,a.y-b.y,(a.z||0)-(b.z||0)],v2=[c.x-b.x,c.y-b.y,(c.z||0)-(b.z||0)],d=v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2],n1=Math.hypot(...v1),n2=Math.hypot(...v2);if(!n1||!n2)return 0;return Math.acos(Math.max(-1,Math.min(1,d/(n1*n2))))*180/Math.PI}
 function circularDiff(a,b){let d=Math.abs(a-b)%360;return d>180?360-d:d}
 function state(){return typeof loadState==='function'?loadState():{}}
 function save(patch){if(typeof saveState==='function')saveState(patch)}
 function refs(){const r=state().v8GeometryRefs;return Array.isArray(r)?r:[]}
 function handLabel(frame,i){const c=frame?.handednesses?.[i]?.[0];return c?.categoryName||`Mano ${i+1}`}
 function classifyFinger(a){return a>=158?['Extendido','extended']:a<=122?['Flexionado','flexed']:['Intermedio','mid']}
 function compute(lm,frame,i){if(!lm||lm.length<21)return null;const palmWidth=Math.max(.0001,dist(lm[5],lm[17])),palmLength=Math.max(.0001,dist(lm[0],lm[9]));const angles=fingerDefs.map(([,idx])=>angle(lm[idx[0]],lm[idx[1]],lm[idx[2]]));const tips=[4,8,12,16,20],openRaw=tips.reduce((s,n)=>s+dist(lm[0],lm[n]),0)/(tips.length*palmLength),spreadRaw=([4,8,12,16].reduce((s,n,j)=>s+dist(lm[n],lm[tips[j+1]]),0)/4)/palmWidth,pinchRaw=dist(lm[4],lm[8])/palmWidth;const dx=lm[9].x-lm[0].x,dy=lm[9].y-lm[0].y,rotation=Math.atan2(dx,-dy)*180/Math.PI;const openPct=Math.max(0,Math.min(100,(openRaw-1.05)/1.25*100)),spreadPct=Math.max(0,Math.min(100,spreadRaw/1.35*100)),pinchPct=Math.max(0,Math.min(100,pinchRaw/1.4*100)),scalePct=Math.max(0,Math.min(100,palmWidth/.34*100));return {handedness:handLabel(frame,i),angles:angles.map(x=>Math.round(x*10)/10),openRaw:+openRaw.toFixed(3),spreadRaw:+spreadRaw.toFixed(3),pinchRaw:+pinchRaw.toFixed(3),rotation:+rotation.toFixed(1),scale:+palmWidth.toFixed(4),openPct,spreadPct,pinchPct,scalePct}}
 function openLabel(v){return v>72?'Muy abierta':v>48?'Abierta':v>27?'Intermedia':'Cerrada'}
 function spreadLabel(v){return v>65?'Amplia':v>35?'Media':'Reducida'}
 function renderEmpty(){current=null;byId('v8LiveHint').textContent='Activá el seguimiento v7 y mostrale una mano a la cámara.';byId('v8Handedness').textContent='—';byId('v8OpenLabel').textContent='—';byId('v8SpreadLabel').textContent='—';byId('v8Rotation').textContent='—';['Open','Spread','Pinch','Scale'].forEach(k=>{byId(`v8${k}Bar`).style.width='0%';byId(`v8${k}Value`).textContent='—'});byId('v8FingerStates').innerHTML=fingerDefs.map(([n])=>`<div class="fingerChip"><b>${n}</b><span>—</span></div>`).join('');byId('v8SaveReference').disabled=true;updateCompareButton()}
 function renderCurrent(){const hands=latestFrame?.landmarks||[];if(!hands.length){byId('v8HandSelect').disabled=true;renderEmpty();return}if(selectedHand>=hands.length)selectedHand=0;byId('v8HandSelect').disabled=hands.length<2;byId('v8HandSelect').innerHTML=hands.map((_,i)=>`<option value="${i}">${handLabel(latestFrame,i)} · mano ${i+1}</option>`).join('');byId('v8HandSelect').value=String(selectedHand);current=compute(hands[selectedHand],latestFrame,selectedHand);if(!current)return renderEmpty();byId('v8LiveHint').textContent='Medidas actualizadas en vivo desde el seguimiento v7.';byId('v8Handedness').textContent=current.handedness;byId('v8OpenLabel').textContent=openLabel(current.openPct);byId('v8SpreadLabel').textContent=spreadLabel(current.spreadPct);byId('v8Rotation').textContent=`${Math.round(current.rotation)}°`;byId('v8FingerStates').innerHTML=fingerDefs.map(([name],i)=>{const [label,cls]=classifyFinger(current.angles[i]);return `<div class="fingerChip ${cls}"><b>${name}</b><span>${label} · ${Math.round(current.angles[i])}°</span></div>`}).join('');[['Open',current.openPct,`${Math.round(current.openPct)}%`],['Spread',current.spreadPct,`${Math.round(current.spreadPct)}%`],['Pinch',current.pinchPct,`${Math.round(current.pinchPct)}%`],['Scale',current.scalePct,`${Math.round(current.scalePct)}%`]].forEach(([k,p,t])=>{byId(`v8${k}Bar`).style.width=`${p}%`;byId(`v8${k}Value`).textContent=t});byId('v8SaveReference').disabled=false;updateCompareButton()}
 function onFrame(e){latestFrame=e.detail||null;const now=performance.now();if(now-lastRender<120)return;lastRender=now;renderCurrent()}
 function compactFeatures(f){return {handedness:f.handedness,angles:f.angles,openRaw:f.openRaw,spreadRaw:f.spreadRaw,pinchRaw:f.pinchRaw,rotation:f.rotation}}
 function saveReference(){if(!current)return;const label=(byId('v8ReferenceName').value||'').trim()||`Referencia ${refs().length+1}`,arr=refs().slice(-9);arr.push({id:`r${Date.now()}`,label,created:new Date().toISOString(),features:compactFeatures(current)});save({v8GeometryRefs:arr});byId('v8ReferenceName').value='';renderReferences()}
 function deleteRef(id){const arr=refs().filter(r=>r.id!==id);save({v8GeometryRefs:arr});renderReferences()}
 function renderReferences(){const arr=refs();byId('v8ReferenceList').innerHTML=arr.length?arr.slice().reverse().map(r=>`<div class="referenceItem"><div><b>${escapeHtml(r.label)}</b><small>${r.features?.handedness||'Mano'} · ${new Date(r.created).toLocaleDateString()}</small></div><button class="deleteReference" data-id="${r.id}" aria-label="Eliminar referencia">×</button></div>`).join(''):'<small>Todavía no guardaste referencias técnicas.</small>';byId('v8ReferenceList').querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>deleteRef(b.dataset.id));const value=byId('v8ReferenceSelect').value;byId('v8ReferenceSelect').innerHTML='<option value="">Elegí una referencia</option>'+arr.map(r=>`<option value="${r.id}">${escapeHtml(r.label)}</option>`).join('');if(arr.some(r=>r.id===value))byId('v8ReferenceSelect').value=value;byId('v8SavedCount').textContent=arr.length;updateCompareButton();renderStats()}
 function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
 function similarity(a,b){if(!a||!b)return 0;const angleScores=a.angles.map((v,i)=>Math.max(0,1-Math.abs(v-b.angles[i])/75));const open=Math.max(0,1-Math.abs(a.openRaw-b.openRaw)/.9),spread=Math.max(0,1-Math.abs(a.spreadRaw-b.spreadRaw)/.8),pinch=Math.max(0,1-Math.abs(a.pinchRaw-b.pinchRaw)/.8),rot=Math.max(0,1-circularDiff(a.rotation,b.rotation)/100);return Math.round((angleScores.reduce((x,y)=>x+y,0)+open+spread+pinch+rot)/(angleScores.length+4)*100)}
 function compare(){if(!current)return;const ref=refs().find(r=>r.id===byId('v8ReferenceSelect').value);if(!ref)return;const score=similarity(compactFeatures(current),ref.features);byId('v8Similarity').textContent=`${score}%`;byId('v8SimilarityBar').style.width=`${score}%`;byId('v8CompareText').textContent=score>=88?'Geometría estática muy parecida a tu referencia. Verificá igualmente la seña completa en la fuente donde la estudiaste.':score>=70?'Hay bastante parecido geométrico, aunque varios rasgos todavía cambian. Compará visualmente con tu fuente validada.':'La configuración actual difiere bastante de tu referencia técnica. Ajustá la mano mirando el material donde la aprendiste.';const s=state(),count=(s.v8CompareCount||0)+1,best=Math.max(s.v8BestSimilarity||0,score);save({v8CompareCount:count,v8BestSimilarity:best});renderStats()}
 function renderStats(){const s=state();byId('v8CompareCount').textContent=s.v8CompareCount||0;byId('v8BestSimilarity').textContent=`${s.v8BestSimilarity||0}%`}
 function updateCompareButton(){byId('v8Compare').disabled=!current||!byId('v8ReferenceSelect').value}
 byId('v8HandSelect').onchange=e=>{selectedHand=Number(e.target.value)||0;renderCurrent()};byId('v8SaveReference').onclick=saveReference;byId('v8ReferenceSelect').onchange=updateCompareButton;byId('v8Compare').onclick=compare;window.addEventListener('lsa-hand-frame',onFrame);renderReferences();renderStats();renderEmpty();
})();