(()=>{
 const heroEy=document.querySelector('.heroMain .ey');if(heroEy)heroEy.textContent='Lengua de Señas Argentina · v7';
 const visual=document.getElementById('comprension-visual');
 const section=document.createElement('section');section.className='handLab';section.id='seguimiento-manos';section.innerHTML=`<div class="handLabTop"><div><span class="ey">LSA v7 · visión por computadora</span><h2>Seguimiento de manos y 21 puntos articulares</h2><p>Esta etapa localiza hasta dos manos y dibuja sus articulaciones en tiempo real. Sirve para comprobar encuadre y tracking; todavía no reconoce vocabulario, gramática ni decide si una seña es correcta.</p></div><div class="v7Pills"><span>MediaPipe Hand Landmarker</span><span>Hasta 2 manos</span><span>Inferencia local</span></div></div><div class="handGrid"><div class="handStage" id="v7Stage"><span class="handBadge" id="v7Badge">Modelo sin cargar</span><div class="handPlaceholder"><div><b>Seguimiento apagado</b><br>La biblioteca y el modelo se descargan recién cuando tocás “Activar seguimiento”.</div></div><video id="v7Video" autoplay muted playsinline></video><canvas id="v7Overlay"></canvas><div class="handControls"><button class="start" id="v7Start">Activar seguimiento</button><button class="test" id="v7Test" disabled>Prueba estable · 5 s</button><button class="stop" id="v7Stop" disabled>Apagar</button></div></div><div class="handSide"><div class="handMetric"><span>Manos detectadas ahora</span><strong id="v7Hands">0</strong><p id="v7HandNames">Mostrá una o ambas manos dentro del cuadro.</p></div><div class="handMetric"><span>Puntos articulares visibles</span><strong id="v7Landmarks">0</strong><p>El modelo entrega 21 puntos por cada mano detectada.</p></div><div class="handMetric"><span>Rendimiento aproximado</span><strong id="v7Fps">—</strong><p>Inferencias por segundo, limitadas para evitar sobrecargar el teléfono.</p></div><div class="handStatus"><b id="v7StatusTitle">Preparado para iniciar</b><span id="v7Status">No se envían cuadros de cámara a nuestro servidor.</span></div><div class="trackingResult"><span>Prueba de seguimiento</span><div class="score" id="v7TrackScore">—</div><div class="trackingBar"><i id="v7TrackBar"></i></div><p id="v7TrackText">Durante 5 segundos mové las manos de forma natural sin salir del encuadre.</p></div><div class="landmarkLegend"><span>0 · muñeca</span><span>4 · pulgar</span><span>8 · índice</span><span>12 · medio</span><span>16 · anular</span><span>20 · meñique</span></div></div></div><div class="v7Privacy"><b>Privacidad y alcance:</b> las imágenes se procesan en el dispositivo mediante WebAssembly. Se descargan la biblioteca y el modelo de MediaPipe, pero los cuadros de cámara no se suben. Detectar articulaciones no equivale a comprender LSA.</div></section>`;
 if(visual)visual.insertAdjacentElement('afterend',section);else{const lab=document.getElementById('laboratorio-visual');if(lab)lab.insertAdjacentElement('afterend',section)}
 const roadmap=document.createElement('section');roadmap.className='visionRoadmap';roadmap.innerHTML=`<h3>Camino hacia reconocimiento asistido</h3><div class="visionSteps"><div class="visionStep done"><b>✓ v6 · Calidad de imagen</b><span>Luz, estabilidad y movimiento.</span></div><div class="visionStep current"><b>● v7 · Manos y articulaciones</b><span>21 landmarks por mano y tracking.</span></div><div class="visionStep"><b>Próximo · Configuración</b><span>Comparar geometría y orientación.</span></div><div class="visionStep"><b>Después · Secuencias</b><span>Movimiento temporal validado.</span></div></div>`;section.insertAdjacentElement('afterend',roadmap);
 const video=document.getElementById('v7Video'),canvas=document.getElementById('v7Overlay'),ctx=canvas.getContext('2d');
 const $=id=>document.getElementById(id);let stream=null,landmarker=null,raf=0,lastInfer=0,lastVideoTime=-1,frames=0,fpsClock=performance.now(),testing=false,testEnd=0,testTotal=0,testWithHand=0,testHandSum=0;
 const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
 function setStatus(title,text){$('v7StatusTitle').textContent=title;$('v7Status').textContent=text}
 function state(){return typeof loadState==='function'?loadState():{}}
 function save(patch){if(typeof saveState==='function')saveState(patch)}
 async function ensureLandmarker(){if(landmarker)return landmarker;$('v7Badge').textContent='Cargando modelo…';setStatus('Cargando visión por computadora','La primera carga puede tardar un poco porque descarga WebAssembly y el modelo de manos.');const mod=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/vision_bundle.mjs');const vision=await mod.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');landmarker=await mod.HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.5,minHandPresenceConfidence:.5,minTrackingConfidence:.5});$('v7Badge').textContent='Modelo listo · local';return landmarker}
 async function start(){if(stream)return;try{document.getElementById('v6StopCamera')?.click();document.getElementById('mirrorStop')?.click();await ensureLandmarker();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;await video.play();$('v7Stage').classList.add('active');$('v7Start').disabled=true;$('v7Stop').disabled=false;$('v7Test').disabled=false;setStatus('Seguimiento activo','Mostrá una o dos manos. Los puntos se calculan localmente.');frames=0;fpsClock=performance.now();lastVideoTime=-1;raf=requestAnimationFrame(loop);const s=state();save({v7HandSessions:(s.v7HandSessions||0)+1})}catch(e){console.error(e);$('v7Badge').textContent='No disponible';setStatus('No se pudo iniciar','Revisá permiso de cámara o conexión para descargar el modelo. El resto del curso sigue funcionando.') }}
 function stop(){testing=false;if(raf)cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;ctx.clearRect(0,0,canvas.width,canvas.height);$('v7Stage').classList.remove('active');$('v7Start').disabled=false;$('v7Stop').disabled=true;$('v7Test').disabled=true;$('v7Hands').textContent='0';$('v7Landmarks').textContent='0';$('v7Fps').textContent='—';$('v7HandNames').textContent='Seguimiento apagado.';setStatus('Seguimiento detenido','La cámara quedó apagada.')}
 function resize(){const w=video.videoWidth||640,h=video.videoHeight||480;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
 function draw(result){resize();ctx.clearRect(0,0,canvas.width,canvas.height);const hands=result?.landmarks||[];const handed=result?.handednesses||result?.handedness||[];$('v7Hands').textContent=hands.length;$('v7Landmarks').textContent=hands.length*21;const labels=[];hands.forEach((lm,i)=>{ctx.lineWidth=Math.max(2,canvas.width/260);ctx.strokeStyle='rgba(124,58,237,.95)';ctx.fillStyle='#ffffff';connections.forEach(([a,b])=>{const p=lm[a],q=lm[b];if(!p||!q)return;ctx.beginPath();ctx.moveTo((1-p.x)*canvas.width,p.y*canvas.height);ctx.lineTo((1-q.x)*canvas.width,q.y*canvas.height);ctx.stroke()});lm.forEach((p,j)=>{ctx.beginPath();ctx.arc((1-p.x)*canvas.width,p.y*canvas.height,j===0?5:3,0,Math.PI*2);ctx.fill()});const c=handed[i]?.[0];labels.push(c?.categoryName?`${c.categoryName} ${Math.round((c.score||0)*100)}%`:`Mano ${i+1}`)});$('v7HandNames').textContent=labels.length?`Lateralidad estimada: ${labels.join(' · ')}`:'No hay una mano dentro del cuadro.';if(testing){testTotal++;if(hands.length){testWithHand++;testHandSum+=hands.length}}}
 function finishTest(){testing=false;const coverage=testTotal?Math.round(testWithHand/testTotal*100):0,avg=testWithHand?(testHandSum/testWithHand).toFixed(1):'0';$('v7TrackScore').textContent=`${coverage}%`;$('v7TrackBar').style.width=`${coverage}%`;$('v7TrackText').textContent=coverage>=85?`Seguimiento muy estable · promedio ${avg} mano(s) cuando hubo detección.`:coverage>=60?`Seguimiento usable · promedio ${avg} mano(s). Probá mejorar luz o encuadre.`:`Seguimiento inestable (${coverage}%). Mejorá luz, distancia y mantené las manos dentro del cuadro.`;const s=state();save({v7TrackingTests:(s.v7TrackingTests||0)+1,v7BestTracking:Math.max(s.v7BestTracking||0,coverage)})}
 function loop(ts){if(!stream)return;raf=requestAnimationFrame(loop);if(video.readyState<2||ts-lastInfer<83||video.currentTime===lastVideoTime)return;lastInfer=ts;lastVideoTime=video.currentTime;try{const result=landmarker.detectForVideo(video,performance.now());draw(result);frames++;const elapsed=performance.now()-fpsClock;if(elapsed>=1000){$('v7Fps').textContent=`${Math.round(frames*1000/elapsed)} fps`;frames=0;fpsClock=performance.now()}}catch(e){console.error(e);setStatus('Error de inferencia','El seguimiento tuvo un problema; podés apagarlo y volver a intentar.')}if(testing&&performance.now()>=testEnd)finishTest()}
 function startTest(){if(!stream||testing)return;testing=true;testEnd=performance.now()+5000;testTotal=0;testWithHand=0;testHandSum=0;$('v7TrackScore').textContent='5.0 s';$('v7TrackBar').style.width='0%';$('v7TrackText').textContent='Mantené una o ambas manos visibles y movelas de forma natural.';const countdown=()=>{if(!testing)return;const left=Math.max(0,(testEnd-performance.now())/1000);$('v7TrackScore').textContent=`${left.toFixed(1)} s`;$('v7TrackBar').style.width=`${Math.min(100,(1-left/5)*100)}%`;if(left>0)requestAnimationFrame(countdown)};countdown()}
 $('v7Start').onclick=start;$('v7Stop').onclick=stop;$('v7Test').onclick=startTest;window.addEventListener('beforeunload',stop);
})();