(()=>{
 const heroEy=document.querySelector('.heroMain .ey');if(heroEy)heroEy.textContent='Lengua de Señas Argentina · v6';

 const lab=document.createElement('section');lab.className='visualLab';lab.id='laboratorio-visual';lab.innerHTML=`
  <div class="visualLabTop"><div><span class="ey">LSA v6 · laboratorio visual</span><h2>Prepará tu espacio de práctica con cámara</h2><p>Antes de intentar reconocimiento automático, esta etapa comprueba condiciones técnicas del video: iluminación, estabilidad y movimiento. No identifica manos ni determina si una seña está bien hecha.</p></div><div class="v6Pills"><span>Procesamiento local</span><span>Sin grabación</span><span>Sin reconocimiento lingüístico</span></div></div>
  <div class="cameraLabGrid"><div class="cameraStage" id="v6CameraStage"><span class="cameraBadge">Laboratorio visual · cámara local</span><div class="labPlaceholder"><div><b>La cámara está apagada</b><br>Activala cuando quieras calibrar el espacio. El resto del curso funciona sin cámara.</div></div><video id="v6Video" autoplay muted playsinline></video><div class="guideFrame"></div><div class="labControls"><button class="start" id="v6StartCamera">Activar cámara</button><button class="sample" id="v6MovementSample" disabled>Medir movimiento · 4 s</button><button class="stop" id="v6StopCamera" disabled>Apagar cámara</button></div></div><div class="cameraMetrics">
   <div class="metricCard"><div class="metricTop"><b>💡 Iluminación</b><span class="metricState" id="v6LightState">Sin medir</span></div><div class="metricBar"><i id="v6LightBar"></i></div><p id="v6LightText">Buscamos una imagen suficientemente clara, evitando sombras fuertes o sobreexposición.</p></div>
   <div class="metricCard"><div class="metricTop"><b>🎯 Estabilidad</b><span class="metricState" id="v6StableState">Sin medir</span></div><div class="metricBar"><i id="v6StableBar"></i></div><p id="v6StableText">Una base estable ayuda a observar ubicación, orientación y movimiento con mayor claridad.</p></div>
   <div class="metricCard"><div class="metricTop"><b>↔ Movimiento en imagen</b><span class="metricState" id="v6MotionState">Sin medir</span></div><div class="metricBar"><i id="v6MotionBar"></i></div><p id="v6MotionText">Este valor detecta cambios entre cuadros; no sabe si esos cambios corresponden a una mano o a una seña.</p></div>
   <div class="movementResult"><h3>Muestra de movimiento</h3><span class="movementScore" id="v6MovementScore">—</span><p id="v6MovementResult">Hacé una secuencia de movimiento frente a la cámara y tocá “Medir movimiento”. El resultado solo evalúa cuánta variación visual hubo.</p></div>
   <div class="labNote"><b>Guía de encuadre:</b> el marco punteado es orientativo. En esta versión todavía no detectamos cara, manos ni articulaciones. Buscamos que el usuario aprenda a preparar un video útil para futuras herramientas de visión por computadora.</div>
  </div></div><canvas id="v6AnalyzeCanvas" width="160" height="120" hidden></canvas>
 </section>`;
 const production=[...document.querySelectorAll('.sectionCard')].find(x=>x.textContent.includes('Práctica de producción'));
 if(production)production.insertAdjacentElement('afterend',lab);else{const route=document.querySelector('.sectionCard.route');if(route)route.insertAdjacentElement('beforebegin',lab)}

 const visual=document.createElement('section');visual.className='visualComprehension';visual.id='comprension-visual';visual.innerHTML=`
  <div class="visualCompTop"><div><span class="ey">LSA v6 · observación</span><h2>Aprender a mirar antes de reconocer</h2><p>Las lenguas de señas no dependen solamente de las manos. Este módulo entrena qué observar cuando estudiás material visual oficial.</p></div><div class="v6Pills"><span>CAS</span><span>Señario</span><span>Observación guiada</span></div></div>
  <div class="observationGrid"><article><span>✋</span><b>Configuración</b><p>Prestá atención a la forma general de la mano y dedos.</p></article><article><span>🧭</span><b>Orientación</b><p>Observá hacia dónde se orientan palma, dedos y cuerpo.</p></article><article><span>📍</span><b>Ubicación</b><p>Mirá en qué zona del espacio o del cuerpo se produce.</p></article><article><span>↔️</span><b>Movimiento</b><p>Seguí dirección, recorrido, repetición y ritmo.</p></article><article><span>🙂</span><b>Rasgos no manuales</b><p>La cara, el cuerpo y el espacio también pueden aportar información lingüística.</p></article></div>
  <div class="visualExercise"><div class="visualExerciseTop"><div><span class="ey">Actividad de comprensión visual</span><h3>Observá desde una fuente oficial y después respondé</h3><p>Abrí uno de los recursos de la CAS, observá algunas entradas y volvé al simulador. Las preguntas evalúan criterios de observación, no una seña específica.</p></div><div class="sourceButtons"><a href="https://cas.org.ar/alfabeto-manual-argentino/" target="_blank" rel="noopener">Alfabeto CAS ↗</a><a href="https://senario.cas.org.ar/" target="_blank" rel="noopener">Señario CAS ↗</a><a href="https://cas.org.ar/cursos-de-lsa/" target="_blank" rel="noopener">Dónde estudiar LSA ↗</a></div></div>
   <div class="v6Quiz"><div class="v6QuizMeta"><span id="v6QuizNumber">Pregunta 1 de 5</span><span id="v6QuizBest">Mejor resultado: —</span></div><h4 id="v6QuizQuestion"></h4><div class="v6Options" id="v6QuizOptions"></div><div class="v6Feedback" id="v6QuizFeedback">Elegí una respuesta.</div><button class="v6Next" id="v6QuizNext" hidden>Siguiente →</button></div>
   <div class="visualHistory"><div><b id="v6VisualAttempts">0</b><span>intentos visuales</span></div><div><b id="v6CameraSamples">0</b><span>muestras de cámara</span></div><div><b id="v6VisualBest">0/5</b><span>mejor evaluación</span></div></div>
   <div class="v6Disclaimer"><b>Alcance actual:</b> esta versión puede analizar propiedades de la imagen y entrenar observación. No reconoce LSA, no identifica qué seña realiza una persona y no debe utilizarse para certificar competencia lingüística.</div>
  </div>
 </section>`;
 lab.insertAdjacentElement('afterend',visual);

 const questions=[
  {q:'¿Alcanza con mirar únicamente las manos para comprender una lengua de señas?',a:1,o:['Sí, el resto del cuerpo no aporta información.','No. También pueden ser relevantes el espacio, el cuerpo y los rasgos no manuales.','Solo hace falta mirar los dedos.'],why:'La CAS explica que las lenguas de señas usan todo el cuerpo, el espacio y rasgos no manuales; si se miraran solo las manos se perdería información.'},
  {q:'Cuando observás una seña nueva en un recurso validado, ¿qué conjunto conviene mirar?',a:2,o:['Solamente qué palabra española aparece debajo.','Solo velocidad y mano dominante.','Configuración, orientación, ubicación, movimiento y componentes no manuales.'],why:'La práctica visual mejora cuando se separan distintos rasgos observables en lugar de reducir todo a una forma de mano.'},
  {q:'Si no recordás con claridad una seña después de verla una vez, ¿qué conviene hacer?',a:0,o:['Volver a la fuente, reproducirla otra vez y contrastarla con enseñanza confiable.','Inventar una aproximación parecida.','Traducir la palabra española con gestos.'],why:'El simulador evita inventar equivalencias: la referencia debe seguir siendo material validado y formación adecuada.'},
  {q:'¿Qué puede afirmar hoy el laboratorio de cámara de esta página?',a:1,o:['Que reconoce si una seña es correcta.','Que mide condiciones técnicas como luz, estabilidad y cantidad de cambio visual.','Que identifica automáticamente palabras en LSA.'],why:'La v6 analiza video a nivel técnico y local; todavía no hay reconocimiento lingüístico.'},
  {q:'¿Completar las actividades visuales de esta plataforma equivale a certificar dominio de LSA?',a:2,o:['Sí, si la cámara funciona bien.','Sí, después de cinco intentos.','No. Sirven para práctica y organización del estudio, no como certificación lingüística.'],why:'Las actividades son herramientas educativas complementarias y no reemplazan formación ni evaluación lingüística especializada.'}
 ];
 let qi=0,qscore=0,qanswered=false;
 function v6State(){return loadState()}
 function renderV6Stats(){const s=v6State(),best=s.v6VisualBest||0,attempts=s.v6VisualAttempts||0,samples=s.v6CameraSamples||0;$('v6VisualAttempts').textContent=attempts;$('v6CameraSamples').textContent=samples;$('v6VisualBest').textContent=`${best}/5`;$('v6QuizBest').textContent=attempts?`Mejor resultado: ${best}/5`:'Mejor resultado: —'}
 function renderV6Quiz(){const q=questions[qi];qanswered=false;$('v6QuizNumber').textContent=`Pregunta ${qi+1} de ${questions.length}`;$('v6QuizQuestion').textContent=q.q;$('v6QuizOptions').innerHTML='';$('v6QuizFeedback').className='v6Feedback';$('v6QuizFeedback').textContent='Elegí una respuesta.';$('v6QuizNext').hidden=true;q.o.forEach((txt,i)=>{const b=document.createElement('button');b.textContent=txt;b.onclick=()=>answerV6(i,b);$('v6QuizOptions').appendChild(b)})}
 function answerV6(i,btn){if(qanswered)return;qanswered=true;const q=questions[qi],[...$('v6QuizOptions').children].forEach(x=>x.disabled=true);if(i===q.a){qscore++;btn.classList.add('correct');$('v6QuizFeedback').className='v6Feedback ok';$('v6QuizFeedback').textContent='✓ '+q.why}else{btn.classList.add('wrong');$('v6QuizOptions').children[q.a].classList.add('correct');$('v6QuizFeedback').className='v6Feedback bad';$('v6QuizFeedback').textContent=q.why}$('v6QuizNext').hidden=false;$('v6QuizNext').textContent=qi===questions.length-1?'Finalizar':'Siguiente →'}
 function finishV6Quiz(){const s=v6State(),attempts=(s.v6VisualAttempts||0)+1,best=Math.max(s.v6VisualBest||0,qscore);saveState({v6VisualAttempts:attempts,v6VisualBest:best});$('v6QuizQuestion').textContent=`Resultado: ${qscore}/${questions.length}`;$('v6QuizOptions').innerHTML='';$('v6QuizFeedback').className='v6Feedback '+(qscore>=4?'ok':'');$('v6QuizFeedback').textContent=qscore>=4?'Muy buena base de observación. Podés repetirla después de estudiar más material visual.':'Conviene volver a observar material oficial y repetir la actividad.';$('v6QuizNext').hidden=false;$('v6QuizNext').textContent='Repetir actividad';$('v6QuizNext').onclick=restartV6Quiz;renderV6Stats()}
 function nextV6Quiz(){if(qi<questions.length-1){qi++;renderV6Quiz()}else finishV6Quiz()}
 function restartV6Quiz(){qi=0;qscore=0;$('v6QuizNext').onclick=nextV6Quiz;renderV6Quiz()}
 $('v6QuizNext').onclick=nextV6Quiz;

 let v6Stream=null,v6Loop=0,lastFrame=null,lastAnalyze=0,currentMotion=0,sampling=false,sampleUntil=0,sampleValues=[];
 const canvas=$('v6AnalyzeCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),video=$('v6Video');
 function metricState(id,text,kind){const el=$(id);el.textContent=text;el.className='metricState'+(kind?' '+kind:'')}
 function analyzeFrame(ts){if(!v6Stream)return;v6Loop=requestAnimationFrame(analyzeFrame);if(ts-lastAnalyze<220||video.readyState<2)return;lastAnalyze=ts;ctx.drawImage(video,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data,lum=new Uint8Array(canvas.width*canvas.height);let sum=0,p=0;for(let i=0;i<data.length;i+=4){const y=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)|0;lum[p++]=y;sum+=y}const brightness=sum/lum.length;let motion=0;if(lastFrame){for(let i=0;i<lum.length;i+=3)motion+=Math.abs(lum[i]-lastFrame[i]);motion/=Math.ceil(lum.length/3)}lastFrame=lum;currentMotion=motion;
  $('v6LightBar').style.width=`${Math.min(100,brightness/2.2)}%`;if(brightness<55){metricState('v6LightState','Muy oscuro','bad');$('v6LightText').textContent='Agregá luz frontal o acercate a una zona más iluminada.'}else if(brightness>215){metricState('v6LightState','Muy brillante','warn');$('v6LightText').textContent='Hay mucha luz o zonas sobreexpuestas; evitá una fuente intensa detrás o delante.'}else{metricState('v6LightState','Adecuada','good');$('v6LightText').textContent='La luminosidad general está dentro de un rango útil para practicar.'}
  const stability=Math.max(0,100-Math.min(100,motion*4));$('v6StableBar').style.width=`${stability}%`;if(motion<5)metricState('v6StableState','Estable','good');else if(motion<15)metricState('v6StableState','Movimiento moderado','warn');else metricState('v6StableState','Muy variable','bad');
  const motionPct=Math.min(100,motion*4);$('v6MotionBar').style.width=`${motionPct}%`;if(motion<3)metricState('v6MotionState','Casi sin cambios','warn');else if(motion<18)metricState('v6MotionState','Cambios detectados','good');else metricState('v6MotionState','Cambio alto','warn');
  if(sampling){sampleValues.push(motion);const remain=Math.max(0,(sampleUntil-performance.now())/1000);$('v6MovementScore').textContent=`${remain.toFixed(1)} s`;if(performance.now()>=sampleUntil)finishMovementSample()}
 }
 async function startV6Camera(){if(v6Stream)return;if(typeof stopMirror==='function')try{stopMirror()}catch(e){};try{metricState('v6LightState','Abriendo…','');v6Stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=v6Stream;$('v6CameraStage').classList.add('active');$('v6StartCamera').disabled=true;$('v6StopCamera').disabled=false;$('v6MovementSample').disabled=false;lastFrame=null;v6Loop=requestAnimationFrame(analyzeFrame)}catch(e){metricState('v6LightState','Sin cámara','bad');$('v6LightText').textContent='No se pudo acceder a la cámara. Podés continuar con todas las actividades sin ella.'}}
 function stopV6Camera(){sampling=false;if(v6Loop)cancelAnimationFrame(v6Loop);v6Loop=0;if(v6Stream){v6Stream.getTracks().forEach(t=>t.stop());v6Stream=null}video.srcObject=null;$('v6CameraStage').classList.remove('active');$('v6StartCamera').disabled=false;$('v6StopCamera').disabled=true;$('v6MovementSample').disabled=true}
 function startMovementSample(){if(!v6Stream||sampling)return;sampling=true;sampleValues=[];sampleUntil=performance.now()+4000;$('v6MovementSample').disabled=true;$('v6MovementResult').textContent='Movete de forma natural dentro del marco durante cuatro segundos.'}
 function finishMovementSample(){sampling=false;$('v6MovementSample').disabled=false;const avg=sampleValues.length?sampleValues.reduce((a,b)=>a+b,0)/sampleValues.length:0;let label,text;if(avg<3){label='Muy bajo';text='Hubo poco cambio visual. Para probar el sistema, realizá movimientos algo más amplios dentro del encuadre.'}else if(avg<15){label='Observable';text='Se detectó una cantidad moderada de cambio visual, útil para futuras etapas de seguimiento de movimiento.'}else{label='Alto';text='Hubo mucho cambio visual. Para entrenamiento fino conviene mantener cámara/cuerpo más estables y aislar mejor el movimiento que querés observar.'}$('v6MovementScore').textContent=label;$('v6MovementResult').textContent=text;const s=v6State();saveState({v6CameraSamples:(s.v6CameraSamples||0)+1,v6LastMotion:Math.round(avg*10)/10});renderV6Stats()}
 $('v6StartCamera').onclick=startV6Camera;$('v6StopCamera').onclick=stopV6Camera;$('v6MovementSample').onclick=startMovementSample;window.addEventListener('beforeunload',stopV6Camera);

 renderV6Quiz();renderV6Stats();
})();