(()=>{
 const style=document.createElement('link');style.rel='stylesheet';style.href='./v5.css';document.head.appendChild(style);
 const heroEy=document.querySelector('.heroMain .ey');if(heroEy)heroEy.textContent='Lengua de Señas Argentina · v5';
 const levelInfo={1:['🌱','Inicio'],2:['👋','Comunicación cotidiana'],3:['🎓','Universidad'],4:['🫀','Salud y emergencias'],5:['💬','Conversación']};
 const lessons={
  1:{title:'Inicio guiado',desc:'Fundamentos, dactilología y hábitos seguros para empezar sin reducir la LSA al castellano.',source:'https://cas.org.ar/alfabeto-manual-argentino/',sourceLabel:'Alfabeto Manual Argentino · CAS',sourceText:'Usá el alfabeto oficial como referencia visual. Para conceptos generales, recordá que la LSA tiene estructura propia y modalidad visoespacial.',objectives:['Distinguir LSA de una traducción gestual del castellano.','Usar una referencia oficial antes de incorporar una seña o configuración nueva.','Practicar dactilología con autoevaluación prudente.'],tasks:[['Referencia visual','Abrí el Alfabeto Manual Argentino y repasá al menos cinco letras antes de marcar esta práctica.'],['Producción','Practicá tu nombre completo con el entrenador de deletreo.'],['Autocontrol','Repetí las letras que te resultaron difíciles y registralas para repaso.']],quiz:[['¿Qué describe mejor a la LSA?',['Una codificación gestual del castellano.','Una lengua visoespacial con estructura gramatical propia.','Un alfabeto manual universal.'],1],['Si no conocés una seña o configuración, ¿qué conviene hacer?',['Inventarla para no cortar la práctica.','Verificarla en una fuente validada o con formación confiable.','Traducir literalmente la palabra al movimiento.'],1],['¿Qué significa completar esta lección?',['Que la plataforma certifica dominio de LSA.','Que completaste una práctica educativa dentro del simulador.','Que ya no necesitás referencias visuales.'],1]]},
  2:{title:'Comunicación cotidiana',desc:'Pasar de elementos aislados a intercambios breves usando vocabulario y construcciones previamente estudiadas.',source:'https://senario.cas.org.ar/',sourceLabel:'Señario · CAS',sourceText:'El Señario organiza entradas por temas e incluye referencias visuales. Elegí un tema, mirá primero el material y recién después practicá de memoria.',objectives:['Combinar repertorio ya estudiado en una intención comunicativa.','Evitar ordenar una interacción como traducción literal del castellano.','Construir continuidad mediante sesiones breves y repaso.'],tasks:[['Exploración','Elegí uno de los temas del Señario y estudiá al menos tres entradas con sus referencias visuales.'],['Memoria','Cerrá la referencia e intentá producir esas tres entradas de memoria.'],['Interacción','Completá una misión breve de comunicación y marcá qué parte necesitás repetir.']],quiz:[['¿Las lenguas de señas son universales?',['Sí.','No; existen distintas lenguas de señas y la LSA pertenece a la comunidad sorda argentina.','Solo cambia el alfabeto.'],1],['Para una interacción breve, ¿qué es preferible?',['Copiar palabra por palabra el castellano.','Usar construcciones y repertorio aprendidos en LSA.','Inventar gestos cuando falta vocabulario.'],1],['¿Para qué sirve el repaso adaptativo?',['Para priorizar lo que marcaste como difícil.','Para certificar automáticamente una seña.','Para reemplazar materiales visuales.'],0]]},
  3:{title:'Universidad y estudio',desc:'Organizar repertorio del entorno educativo y practicar situaciones académicas sin inventar equivalencias.',source:'https://senario.cas.org.ar/',sourceLabel:'Señario Vol. 1 · tema “La escuela”',sourceText:'El Volumen 1 incluye “La escuela” entre sus temas. Usalo como punto de partida y sumá a tu cuaderno solo entradas que realmente hayas estudiado.',objectives:['Construir un pequeño repertorio académico validado.','Practicar nombres propios mediante dactilología cuando corresponda.','Resolver una situación universitaria con recursos ya aprendidos.'],tasks:[['Tema Escuela','Estudiá al menos tres entradas del tema “La escuela” en el Señario y marcá el tema como practicado.'],['Cuaderno universitario','Agregá a tu cuaderno al menos tres palabras o expresiones de contexto universitario que hayas verificado previamente.'],['Escena académica','Simulá pedir o intercambiar información universitaria usando solo recursos ya estudiados; si falta una seña, anotala para buscarla después.']],quiz:[['Si falta una seña durante una práctica universitaria, ¿qué hacés?',['La invento.','La verifico en una fuente validada antes de incorporarla.','La reemplazo por cualquier gesto.'],1],['¿La dactilología reemplaza la gramática de la LSA?',['Sí.','No; es un recurso específico y no sustituye la estructura de la lengua.','Solo en la universidad.'],1],['¿Qué registra esta lección?',['Práctica y conceptos dentro del simulador.','Una certificación oficial de competencia.','La corrección automática de todas tus señas.'],0]]},
  4:{title:'Salud y emergencias',desc:'Preparar comunicación accesible para situaciones urgentes sin demorar ni sustituir las acciones de emergencia.',source:'https://senario.cas.org.ar/',sourceLabel:'Repertorio validado + práctica personal',sourceText:'Este módulo no asigna traducciones médicas automáticamente. Construí tu mazo solo con señas que hayas aprendido en una fuente confiable y mantené separados comunicación y protocolo de emergencia.',objectives:['Preparar un mazo personal de señas ya validadas.','Practicar comunicación breve bajo presión sin inventar vocabulario.','Entender que la accesibilidad no debe demorar RCP ni la activación de emergencias.'],tasks:[['Mazo de emergencia','Seleccioná al menos tres tarjetas previamente estudiadas para tu mazo de emergencia.'],['Práctica rápida','Ejecutá varias tarjetas al azar y verificá después con la fuente donde las aprendiste.'],['Escenario combinado','Abrí el simulador de RCP y repasá mentalmente qué información accesible podrías necesitar comunicar sin retrasar las maniobras.']],quiz:[['En una emergencia real, ¿la comunicación debe retrasar RCP o la activación de ayuda?',['Sí.','No; debe acompañar sin demorar acciones críticas.','Solo si conozco pocas señas.'],1],['¿La plataforma debería inventar una seña médica cuando no tiene una referencia validada?',['Sí.','No.','Solo si parece intuitiva.'],1],['¿Qué representa el mazo de emergencia?',['Un repertorio personal de señas previamente estudiadas.','Un diccionario médico oficial.','Una certificación de intérprete.'],0]]},
  5:{title:'Conversación integrada',desc:'Integrar temas, memoria, misiones y autoevaluación en intercambios cada vez más completos.',source:'https://senario.cas.org.ar/',sourceLabel:'Señario · repaso multitemático',sourceText:'Usá varios temas como base visual. La meta es practicar fluidez y planificación con repertorio validado, no recibir una calificación automática de ejecución.',objectives:['Integrar vocabulario de varios temas sin depender siempre de la referencia.','Planificar inicio, desarrollo y cierre de una interacción.','Identificar qué repertorio necesita nuevo estudio.'],tasks:[['Repaso multitemático','Elegí al menos cinco temas que ya hayas practicado y seleccioná una entrada de cada uno.'],['Conversación','Realizá una interacción simulada de inicio, desarrollo y cierre usando solo recursos conocidos.'],['Reflexión','Anotá qué parte salió fluida y qué parte debería volver al repaso inteligente.']],quiz:[['Completar los cinco niveles equivale a una certificación oficial de LSA?',['Sí.','No; es una herramienta educativa y de práctica personal.','Sí, si usé la cámara.'],1],['Si una interacción se traba por vocabulario faltante, ¿qué conviene hacer después?',['Inventar la seña la próxima vez.','Registrar lo que falta y estudiarlo en una fuente validada.','Eliminar ese concepto de la conversación.'],1],['¿Cuál es la función principal del historial?',['Mostrar intentos y evolución dentro del simulador.','Acreditar competencia lingüística formal.','Guardar videos de la cámara.'],0]]}
 };
 const passed=id=>{const a=loadState().v4PassedLevels||[];return Array.isArray(a)&&a.includes(id)};
 const openLevel=id=>id===1||passed(id-1);
 const lessonState=()=>({...((loadState().v5Lessons)||{})});
 const historyState=()=>Array.isArray(loadState().v5History)?loadState().v5History:[];
 const completedCount=()=>Object.values(lessonState()).filter(x=>x&&x.completed).length;
 const bestScore=()=>{const vals=Object.values(lessonState()).map(x=>x&&x.best||0);return vals.length?Math.max(...vals):0};
 const attemptCount=()=>historyState().length;

 const studio=document.createElement('section');studio.className='courseStudio';studio.id='curso-v5';studio.innerHTML=`<div class="courseTop"><div><span class="ey">LSA v5 · curso interactivo</span><h2>Lecciones completas por nivel</h2><p>Cada lección combina objetivos, referencia oficial, práctica guiada y una evaluación conceptual. La plataforma registra avance, pero no certifica la ejecución lingüística de una seña.</p></div><span class="v5Pill">5 niveles · historial local</span></div><div class="courseStats"><div><b id="v5Completed">0/5</b><span>lecciones completadas</span></div><div><b id="v5Best">0%</b><span>mejor evaluación</span></div><div><b id="v5Attempts">0</b><span>intentos registrados</span></div><div><b id="v5CourseXP">0</b><span>XP de curso</span></div></div><div class="courseProgress"><i id="v5CourseBar"></i></div><div class="lessonGrid" id="v5LessonGrid"></div><div class="courseLaunch"><button id="v5Recommended">Abrir lección recomendada</button><button id="v5HistoryJump">Ver historial</button></div><div class="lessonPlayer hidden" id="v5LessonPlayer"><div class="lessonPlayerTop"><div><span class="ey" id="v5LessonEy"></span><h3 id="v5LessonTitle"></h3><p id="v5LessonDesc"></p></div><button class="lessonClose" id="v5LessonClose">Cerrar</button></div><div class="lessonTabs"><span class="active">1 · Objetivos</span><span>2 · Práctica</span><span>3 · Evaluación</span></div><div class="objectiveList" id="v5Objectives"></div><div class="lessonSource"><p id="v5SourceText"></p><a id="v5SourceLink" href="https://senario.cas.org.ar/" target="_blank" rel="noopener">Abrir fuente ↗</a></div><div class="practiceChecklist" id="v5Practice"></div><div class="lessonQuiz"><div class="lessonQuizHead"><h4>Evaluación conceptual</h4><span class="v5Pill" id="v5QuizProgress">Pregunta 1/3</span></div><div id="v5QuizArea"><div class="lessonQuestion" id="v5Question"></div><div class="lessonOptions" id="v5Options"></div><div class="lessonFeedback" id="v5Feedback">Elegí una respuesta.</div><div class="lessonFooter"><small>Se aprueba con 2/3. Esto evalúa conceptos y práctica registrada, no la forma de una seña.</small><button class="lessonNext" id="v5QuizNext" disabled>Siguiente →</button></div></div><div class="lessonResult hidden" id="v5QuizResult"><div class="score" id="v5ResultScore">0%</div><h4 id="v5ResultTitle">Evaluación completada</h4><p id="v5ResultText"></p><button class="lessonComplete" id="v5CompleteLesson" disabled>Completar lección</button></div></div></div>`;
 const cp=document.getElementById('v4Checkpoint'),road=document.getElementById('ruta-niveles');if(cp)cp.insertAdjacentElement('afterend',studio);else if(road)road.insertAdjacentElement('afterend',studio);else document.querySelector('main.wrap').appendChild(studio);

 const special=document.createElement('section');special.className='specialTracks';special.innerHTML=`<div class="specialTop"><div><span class="ey">Trayectos destacados</span><h2>Universidad y Salud, con práctica contextual.</h2><p>Dos módulos pensados para el uso que más valor puede aportar dentro de Ayuda para el Alumno, siempre partiendo de vocabulario previamente validado.</p></div><span class="v5Pill">Sin traducción automática</span></div><div class="trackGrid"><article class="trackCard"><span class="trackIcon">🎓</span><h3>LSA en la universidad</h3><p>Organizá vocabulario académico, dactilología de nombres y situaciones de cursada sin inventar señas nuevas.</p><div class="trackTags"><span>Tema Escuela</span><span>Cuaderno personal</span><span>Escena académica</span></div><button id="v5UniversityBtn">Abrir trayecto Universidad</button></article><article class="trackCard"><span class="trackIcon">🫀</span><h3>LSA en salud y emergencias</h3><p>Construí un repertorio personal validado y entrená comunicación breve sin demorar los protocolos de emergencia.</p><div class="trackTags"><span>Mazo personal</span><span>Práctica rápida</span><span>Puente con RCP</span></div><button id="v5HealthBtn">Abrir trayecto Salud</button></article></div><div class="v5Notice"><b>Importante:</b> estos trayectos no crean un vocabulario médico o universitario propio. Organizan la práctica con material que el estudiante ya estudió en fuentes confiables o con referentes de la comunidad sorda.</div>`;
 studio.insertAdjacentElement('afterend',special);

 const history=document.createElement('section');history.className='historyPanel';history.id='historial-v5';history.innerHTML=`<div class="historyTop"><div><span class="ey">Historial local</span><h2>Resultados e intentos</h2><p>Guardamos fecha, nivel y puntaje conceptual para que puedas ver tu evolución en este dispositivo.</p></div><span class="v5Pill">No se suben datos</span></div><div class="historyList" id="v5History"></div>`;special.insertAdjacentElement('afterend',history);

 let activeLevel=null,quizIndex=0,quizScore=0,quizAnswered=false,quizFinished=false;
 function renderCourse(){const ls=lessonState(),completed=completedCount();$('v5Completed').textContent=`${completed}/5`;$('v5Best').textContent=`${bestScore()}%`;$('v5Attempts').textContent=attemptCount();$('v5CourseXP').textContent=loadState().v5CourseXP||0;$('v5CourseBar').style.width=`${completed/5*100}%`;$('v5LessonGrid').innerHTML='';for(let id=1;id<=5;id++){const l=lessons[id],info=levelInfo[id],st=ls[id]||{},open=openLevel(id),card=document.createElement('article');card.className='lessonCard'+(st.completed?' done':(!open?' locked':(id===recommendedLevel()?' current':'')));card.innerHTML=`<span class="lessonIcon">${info[0]}</span><h3>${id}. ${info[1]}</h3><p>${l.desc}</p><div class="lessonMeta"><span>${st.attempts||0} intento${(st.attempts||0)===1?'':'s'}</span><span>${st.best?`Mejor ${st.best}%`:open?'Disponible':'Bloqueado'}</span></div><button ${open?'':'disabled'}>${st.completed?'Repetir lección':open?'Abrir lección':'Completá el nivel anterior'}</button>`;card.querySelector('button').onclick=()=>openLesson(id);$('v5LessonGrid').appendChild(card)}renderHistory();$('v5UniversityBtn').disabled=!openLevel(3);$('v5HealthBtn').disabled=!openLevel(4)}
 function recommendedLevel(){const ls=lessonState();for(let i=1;i<=5;i++)if(openLevel(i)&&!(ls[i]&&ls[i].completed))return i;for(let i=5;i>=1;i--)if(openLevel(i))return i;return 1}
 function openLesson(id){if(!openLevel(id))return;activeLevel=id;quizIndex=0;quizScore=0;quizAnswered=false;quizFinished=false;const l=lessons[id],info=levelInfo[id];$('v5LessonPlayer').classList.remove('hidden');$('v5LessonEy').textContent=`Lección ${id} · ${info[1]}`;$('v5LessonTitle').textContent=l.title;$('v5LessonDesc').textContent=l.desc;$('v5Objectives').innerHTML=l.objectives.map((x,i)=>`<div><b>Objetivo ${i+1}</b><br>${x}</div>`).join('');$('v5SourceText').innerHTML=`<b>${l.sourceLabel}</b><br>${l.sourceText}`;$('v5SourceLink').href=l.source;$('v5Practice').innerHTML=l.tasks.map(([t,d],i)=>`<label class="practiceCheck"><input type="checkbox" data-v5task="${i}"><span><b>${t}</b><small>${d}</small></span></label>`).join('');document.querySelectorAll('[data-v5task]').forEach(x=>x.onchange=updateCompleteButton);$('v5QuizArea').classList.remove('hidden');$('v5QuizResult').classList.add('hidden');renderQuestion();$('v5LessonPlayer').scrollIntoView({behavior:'smooth',block:'start'})}
 function renderQuestion(){const l=lessons[activeLevel],q=l.quiz[quizIndex];quizAnswered=false;$('v5QuizProgress').textContent=`Pregunta ${quizIndex+1}/${l.quiz.length}`;$('v5Question').textContent=q[0];$('v5Options').innerHTML='';$('v5Feedback').className='lessonFeedback';$('v5Feedback').textContent='Elegí una respuesta.';$('v5QuizNext').disabled=true;$('v5QuizNext').textContent=quizIndex===l.quiz.length-1?'Ver resultado':'Siguiente →';q[1].forEach((txt,i)=>{const b=document.createElement('button');b.className='lessonOption';b.textContent=txt;b.onclick=()=>answerQuestion(i,b);$('v5Options').appendChild(b)})}
 function answerQuestion(i,btn){if(quizAnswered)return;quizAnswered=true;const q=lessons[activeLevel].quiz[quizIndex],ok=i===q[2];document.querySelectorAll('.lessonOption').forEach(x=>x.disabled=true);if(ok){quizScore++;btn.classList.add('correct');$('v5Feedback').className='lessonFeedback ok';$('v5Feedback').textContent='✓ Correcto.'}else{btn.classList.add('wrong');const correct=$('v5Options').children[q[2]];if(correct)correct.classList.add('correct');$('v5Feedback').className='lessonFeedback bad';$('v5Feedback').textContent='Revisá este concepto antes de avanzar.'}$('v5QuizNext').disabled=false}
 function finishAssessment(){quizFinished=true;const pct=Math.round(quizScore/lessons[activeLevel].quiz.length*100),passedEval=quizScore>=2;$('v5QuizArea').classList.add('hidden');$('v5QuizResult').classList.remove('hidden');$('v5ResultScore').textContent=`${pct}%`;$('v5ResultTitle').textContent=passedEval?'Evaluación conceptual aprobada':'Conviene repetir la evaluación';$('v5ResultText').textContent=passedEval?'Ahora completá todas las prácticas marcadas para cerrar la lección.':'Necesitás al menos 2 de 3 respuestas correctas. Podés repetir la lección sin perder tu progreso previo.';recordAttempt(activeLevel,pct,passedEval);updateCompleteButton();renderCourse()}
 $('v5QuizNext').onclick=()=>{if(!quizAnswered)return;if(quizIndex<lessons[activeLevel].quiz.length-1){quizIndex++;renderQuestion()}else finishAssessment()};
 function allTasks(){const boxes=[...document.querySelectorAll('[data-v5task]')];return boxes.length&&boxes.every(x=>x.checked)}
 function updateCompleteButton(){if(!activeLevel)return;const passedEval=quizFinished&&quizScore>=2;$('v5CompleteLesson').disabled=!(passedEval&&allTasks())}
 function recordAttempt(level,pct,ok){const s=loadState(),ls={...(s.v5Lessons||{})},old=ls[level]||{};ls[level]={...old,attempts:(old.attempts||0)+1,best:Math.max(old.best||0,pct),last:new Date().toISOString()};const hist=Array.isArray(s.v5History)?s.v5History.slice():[];hist.unshift({level,pct,ok,date:new Date().toISOString()});saveState({v5Lessons:ls,v5History:hist.slice(0,30)})}
 function completeLesson(){if($('v5CompleteLesson').disabled||!activeLevel)return;const s=loadState(),ls={...(s.v5Lessons||{})},old=ls[activeLevel]||{},first=!old.completed,pct=Math.round(quizScore/lessons[activeLevel].quiz.length*100);ls[activeLevel]={...old,completed:true,best:Math.max(old.best||0,pct),last:new Date().toISOString()};let xp=s.v5CourseXP||0,v4xp=s.v4XP||0;if(first){const gain=40+activeLevel*10;xp+=gain;v4xp+=gain}saveState({v5Lessons:ls,v5CourseXP:xp,v4XP:v4xp});$('v5ResultTitle').textContent='Lección completada';$('v5ResultText').textContent=first?`Sumaste ${40+activeLevel*10} XP de curso. El resultado queda guardado solo en este dispositivo.`:'La lección volvió a completarse. Conservamos tu mejor resultado.';$('v5CompleteLesson').disabled=true;$('v5CompleteLesson').textContent='✓ Lección completada';if($('v4XP'))$('v4XP').textContent=v4xp;renderCourse()}
 $('v5CompleteLesson').onclick=completeLesson;$('v5LessonClose').onclick=()=>{$('v5LessonPlayer').classList.add('hidden')};
 function renderHistory(){const hist=historyState(),box=$('v5History');if(!hist.length){box.innerHTML='<div class="emptyHistory">Todavía no hay evaluaciones registradas. Completá una lección para empezar tu historial.</div>';return}box.innerHTML=hist.slice(0,12).map(r=>{const info=levelInfo[r.level]||['🤟',`Nivel ${r.level}`],d=new Date(r.date);return `<div class="historyRow"><span class="historyIcon">${info[0]}</span><div><b>${info[1]}</b><small>${r.ok?'Evaluación aprobada':'Evaluación para repetir'}</small></div><span class="historyScore">${r.pct}%</span><span class="historyDate">${isNaN(d)?'':d.toLocaleDateString('es-AR')}</span></div>`}).join('')}
 $('v5Recommended').onclick=()=>openLesson(recommendedLevel());$('v5HistoryJump').onclick=()=>history.scrollIntoView({behavior:'smooth',block:'start'});$('v5UniversityBtn').onclick=()=>openLesson(3);$('v5HealthBtn').onclick=()=>openLesson(4);
 // Mantener los bloqueos sincronizados si el usuario completa checkpoints o actividades v4.
 ['v4CheckPass','dailyGood','dailyRepeat','missionGood','missionAgain','wordForm','emergencyNext'].forEach(id=>{const el=$(id);if(el)el.addEventListener('click',()=>setTimeout(renderCourse,50))});
 renderCourse();
})();