(()=>{
 const style=document.createElement('link');style.rel='stylesheet';style.href='./v3.css';document.head.appendChild(style);
 const heroEy=document.querySelector('.heroMain .ey');if(heroEy)heroEy.textContent='Lengua de Señas Argentina · v3';
 const dashStats=document.querySelector('.dashboard .stats');if(dashStats){dashStats.classList.add('v3Stats');dashStats.insertAdjacentHTML('beforeend','<div><b id="dailyStreak">0</b><span>días de racha</span></div><div><b id="dailyDays">0</b><span>días practicados</span></div><div><b id="weakCount">0</b><span>ítems a repasar</span></div>')}

 const daily=document.createElement('section');daily.className='dailyCard';daily.id='sesion-diaria';daily.innerHTML=`
  <div class="dailyTop"><div><span class="ey">LSA v3 · práctica guiada</span><h2>Sesión diaria de 5 pasos</h2><p>El simulador mezcla dactilología, un tema del Señario, tarjetas personales y una misión. Lo que marcás para repetir vuelve con mayor prioridad.</p></div><div class="dailyBadges"><span>≈ 5 minutos</span><span>Repaso adaptativo</span><span>Datos locales</span></div></div>
  <div class="dailyStart" id="dailyStart"><div><b id="dailyStartTitle">Una práctica corta para mantener continuidad</b><small id="dailyStartText">No califica tu LSA: organiza ejercicios basados en material que ya estudiaste y en referencias oficiales.</small></div><button id="dailyStartBtn">Iniciar sesión →</button></div>
  <div class="dailyPlayer hidden" id="dailyPlayer"><div class="dailyMeta"><span id="dailyStepLabel"></span><span id="dailyScoreLabel"></span></div><div class="dailyProgress"><i id="dailyBar"></i></div><div id="dailyPlay"><span class="dailyType" id="dailyType"></span><div class="dailyPrompt" id="dailyPrompt"></div><div class="dailyHint" id="dailyHint"></div><a id="dailySource" class="dailySource" href="https://senario.cas.org.ar/" target="_blank" rel="noopener">Abrir referencia CAS ↗</a><div class="dailyActions"><button id="dailyGood">✓ Me salió / completado</button><button id="dailyRepeat">↻ Necesito repetir</button></div></div><div class="dailyDone hidden" id="dailyDone"><span class="big">✓</span><h3>Sesión completada</h3><p id="dailyDoneText"></p><button class="primaryButton" id="dailyAgain">Hacer otra sesión</button></div></div>`;
 const dashboard=document.querySelector('.dashboard');if(dashboard)dashboard.insertAdjacentElement('afterend',daily);

 const review=document.createElement('section');review.className='smartReview';review.innerHTML=`
  <div class="reviewTop"><div><span class="ey">Repaso inteligente</span><h2>Volvé primero a lo que más cuesta.</h2><p>Cada “necesito repetir” suma prioridad. Cuando algo empieza a salir bien, su prioridad baja progresivamente.</p></div><button class="reviewButton" id="smartReviewBtn">Iniciar repaso →</button></div>
  <div class="reviewGrid"><div class="reviewBox"><h3>Letras prioritarias</h3><p>Dactilología que marcaste para repetir.</p><div class="reviewChips" id="weakLettersList"></div></div><div class="reviewBox"><h3>Tarjetas prioritarias</h3><p>Palabras o expresiones de tu cuaderno que necesitan más práctica.</p><div class="reviewChips" id="weakWordsList"></div></div></div>`;
 const route=document.querySelector('.sectionCard.route');if(route)route.insertAdjacentElement('beforebegin',review);

 const notebook=document.querySelector('.sectionCard.notebook');
 if(notebook){
  const wordPractice=$('wordPractice');if(wordPractice){wordPractice.insertAdjacentHTML('beforeend','<div class="wordReviewActions hidden" id="wordReviewActions"><button id="wordRemembered">✓ La recordé</button><button id="wordRepeatV3">↻ Repetir</button></div>')}
  const bridge=document.createElement('section');bridge.className='emergencyBridge';bridge.innerHTML=`
   <div class="emergencyTop"><div><span class="ey">Puente entre simuladores</span><h2>LSA en una situación de emergencia</h2><p>Armá un pequeño conjunto con señas que ya hayas estudiado y validado. Este módulo no inventa equivalencias ni sustituye a un intérprete o a los servicios de emergencia.</p></div><div class="dailyBadges"><span>LSA + RCP</span><span>Práctica personal</span></div></div>
   <div class="bridgeGrid"><div class="bridgeInfo"><h3>Cómo usarlo</h3><p>Primero incorporá al cuaderno palabras o expresiones desde el Señario, un curso o una fuente validada. Después elegí cuáles querés practicar en contextos urgentes.</p><div class="bridgeSteps"><div><b>1</b><span>Estudiá la seña en una fuente confiable.</span></div><div><b>2</b><span>Agregala a “Mi cuaderno de práctica”.</span></div><div><b>3</b><span>Marcala acá para tu mazo de emergencia.</span></div><div><b>4</b><span>Practicá producción rápida y clara.</span></div></div><div class="miniNotice">La comunicación accesible en una emergencia es un complemento; no debe demorar la activación del sistema de emergencias ni las maniobras indicadas.</div></div><div class="emergencyDeck"><h3>Mi mazo de emergencia</h3><p id="emergencyDeckHelp">Elegí entre tus tarjetas ya estudiadas.</p><div class="emergencyWords" id="emergencyWords"></div><div class="emergencyDrill hidden" id="emergencyDrill"><span class="ey">Práctica rápida</span><div class="prompt" id="emergencyPrompt">—</div><div class="small" id="emergencyHint">Producí la seña de memoria y luego verificá con tu fuente.</div><div class="emergencyDrillActions"><button id="emergencyNext">Otra tarjeta</button><button id="emergencyScenario">Situación aleatoria</button><a href="/simuladores/rcp/">Abrir simulador RCP →</a></div></div></div></div>`;
  notebook.insertAdjacentElement('afterend',bridge);
 }

 const todayKey=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
 const getWeakLetters=()=>({...((loadState().v3WeakLetters)||{})});
 const getWeakWords=()=>({...((loadState().v3WeakWords)||{})});
 function saveWeakLetter(letter,delta){if(!letter)return;const map=getWeakLetters();map[letter]=Math.max(0,(map[letter]||0)+delta);saveState({v3WeakLetters:map});renderReview();updateV3Stats()}
 function saveWeakWord(word,delta){if(!word)return;const map=getWeakWords();map[word]=Math.max(0,(map[word]||0)+delta);saveState({v3WeakWords:map});renderReview();updateV3Stats()}
 const letterRepeatBtn=$('letterRepeat'),letterGoodBtn=$('letterGood');
 if(letterRepeatBtn)letterRepeatBtn.addEventListener('click',()=>saveWeakLetter(currentLetter,1),true);
 if(letterGoodBtn)letterGoodBtn.addEventListener('click',()=>saveWeakLetter(currentLetter,-1),true);
 if($('spellAgain'))$('spellAgain').addEventListener('click',()=>{const l=spelling.letters[spelling.index];saveWeakLetter(l,1)},true);
 if($('spellGood'))$('spellGood').addEventListener('click',()=>{const l=spelling.letters[spelling.index];saveWeakLetter(l,-1)},true);

 if($('practiceRandom'))$('practiceRandom').addEventListener('click',()=>{if(practiceWords.length)$('wordReviewActions').classList.remove('hidden')});
 if($('wordRemembered'))$('wordRemembered').onclick=()=>{const w=$('practicePrompt').textContent.trim();if(w&&w!=='—')saveWeakWord(w,-1);$('wordReviewActions').classList.add('hidden')};
 if($('wordRepeatV3'))$('wordRepeatV3').onclick=()=>{const w=$('practicePrompt').textContent.trim();if(w&&w!=='—')saveWeakWord(w,1);$('wordReviewActions').classList.add('hidden')};

 function calcStreak(dates){const set=new Set(dates||[]);let streak=0;const d=new Date();for(let i=0;i<500;i++){const p=n=>String(n).padStart(2,'0'),k=`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;if(set.has(k)){streak++;d.setDate(d.getDate()-1)}else{if(i===0){d.setDate(d.getDate()-1);continue}break}}return streak}
 function updateV3Stats(){const s=loadState(),dates=Array.isArray(s.v3DailyDates)?s.v3DailyDates:[],wl=getWeakLetters(),ww=getWeakWords();if($('dailyStreak'))$('dailyStreak').textContent=calcStreak(dates);if($('dailyDays'))$('dailyDays').textContent=dates.length;if($('weakCount'))$('weakCount').textContent=Object.values(wl).filter(v=>v>0).length+Object.values(ww).filter(v=>v>0).length;const done=dates.includes(todayKey());if(done){$('dailyStartTitle').textContent='Ya completaste una sesión hoy';$('dailyStartText').textContent='Podés repetirla si querés reforzar contenido; la racha del día ya quedó registrada.'}}
 function renderReview(){const wl=Object.entries(getWeakLetters()).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,8),ww=Object.entries(getWeakWords()).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,8);$('weakLettersList').innerHTML=wl.length?wl.map(([k,v])=>`<span class="reviewChip">${k} · ${v}</span>`).join(''):'<span class="reviewEmpty">Todavía no hay letras pendientes.</span>';$('weakWordsList').innerHTML=ww.length?ww.map(([k,v])=>`<span class="reviewChip">${k} · ${v}</span>`).join(''):'<span class="reviewEmpty">Todavía no hay tarjetas pendientes.</span>'}

 let dailyQueue=[],dailyIndex=0,dailyOk=0,dailyRepeat=0;
 function weightedLetter(){const entries=Object.entries(getWeakLetters()).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);if(entries.length)return entries[0][0];return letters[Math.floor(Math.random()*letters.length)]}
 function topicItem(){const p=progressState();let pool=topics.filter(t=>(p[t.id]||0)===1);if(!pool.length)pool=topics.filter(t=>(p[t.id]||0)>=1);if(!pool.length)pool=topics;const t=pool[Math.floor(Math.random()*pool.length)],status=p[t.id]||0;return {type:'Tema del Señario',prompt:t.name,hint:status?'Elegí 2 o 3 entradas de este tema y producilas de memoria. Verificá después con el Señario.':'Todavía no marcaste este tema como estudiado. Exploralo en el Señario y practicá al menos 2 entradas.',source:'https://senario.cas.org.ar/',kind:'topic',id:t.id,status}}
 function wordItem(){if(!practiceWords.length)return {type:'Dactilología extra',prompt:`Letra ${weightedLetter()}`,hint:'Producí la letra y comprobala después con el Alfabeto Manual Argentino.',source:'https://cas.org.ar/alfabeto-manual-argentino/',kind:'letter',id:weightedLetter()};const weak=Object.entries(getWeakWords()).filter(([w,v])=>v>0&&practiceWords.includes(w)).sort((a,b)=>b[1]-a[1]);const w=weak.length?weak[0][0]:practiceWords[Math.floor(Math.random()*practiceWords.length)];return {type:'Tarjeta personal',prompt:w,hint:'Producí la seña que ya estudiaste. Si dudás, volvé a tu fuente validada antes de marcarla como lograda.',source:'https://senario.cas.org.ar/',kind:'word',id:w}}
 function missionItem(){const m=missions[Math.floor(Math.random()*missions.length)];return {type:'Misión corta',prompt:m.name,hint:m.steps[0][1]+' '+m.steps[0][2],source:'https://senario.cas.org.ar/',kind:'mission',id:m.id}}
 function buildDailyQueue(smart=false){if(smart){const wl=Object.entries(getWeakLetters()).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([l])=>({type:'Repaso de letra',prompt:`Letra ${l}`,hint:'Producila de memoria y verificá con el alfabeto oficial.',source:'https://cas.org.ar/alfabeto-manual-argentino/',kind:'letter',id:l}));const ww=Object.entries(getWeakWords()).filter(([w,v])=>v>0&&practiceWords.includes(w)).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([w])=>({type:'Repaso de tarjeta',prompt:w,hint:'Producí la seña que ya estudiaste y verificá después.',source:'https://senario.cas.org.ar/',kind:'word',id:w}));dailyQueue=[...wl,...ww].slice(0,5);if(!dailyQueue.length)dailyQueue=[{type:'Dactilología',prompt:`Letra ${weightedLetter()}`,hint:'Producí la letra y comprobala después.',source:'https://cas.org.ar/alfabeto-manual-argentino/',kind:'letter',id:weightedLetter()},topicItem(),wordItem()]}else{const l1=weightedLetter();let l2=letters[Math.floor(Math.random()*letters.length)];if(l2===l1)l2=letters[(letters.indexOf(l1)+5)%letters.length];dailyQueue=[{type:'Dactilología',prompt:`Letra ${l1}`,hint:'Producila sin mirar. Después comprobá la configuración con el Alfabeto Manual Argentino.',source:'https://cas.org.ar/alfabeto-manual-argentino/',kind:'letter',id:l1},{type:'Dactilología',prompt:`Letra ${l2}`,hint:'Buscá claridad en la configuración de la mano antes de avanzar.',source:'https://cas.org.ar/alfabeto-manual-argentino/',kind:'letter',id:l2},topicItem(),wordItem(),missionItem()]}}
 function startDaily(smart=false){buildDailyQueue(smart);dailyIndex=0;dailyOk=0;dailyRepeat=0;$('dailyPlayer').classList.remove('hidden');$('dailyPlay').classList.remove('hidden');$('dailyDone').classList.add('hidden');renderDaily();$('dailyPlayer').scrollIntoView({behavior:'smooth',block:'center'})}
 function renderDaily(){const item=dailyQueue[dailyIndex];$('dailyStepLabel').textContent=`Paso ${dailyIndex+1} de ${dailyQueue.length}`;$('dailyScoreLabel').textContent=`${dailyOk} logrados · ${dailyRepeat} a repetir`;$('dailyBar').style.width=`${dailyIndex/dailyQueue.length*100}%`;$('dailyType').textContent=item.type;$('dailyPrompt').textContent=item.prompt;$('dailyHint').textContent=item.hint;$('dailySource').href=item.source}
 function rateDaily(ok){const item=dailyQueue[dailyIndex];if(ok)dailyOk++;else dailyRepeat++;if(item.kind==='letter')saveWeakLetter(item.id,ok?-1:1);if(item.kind==='word')saveWeakWord(item.id,ok?-1:1);if(item.kind==='topic'&&ok){const state=progressState()[item.id]||0;setTopic(item.id,state>=1?2:1)}dailyIndex++;if(dailyIndex>=dailyQueue.length){finishDaily();return}renderDaily()}
 function finishDaily(){const s=loadState(),dates=Array.isArray(s.v3DailyDates)?s.v3DailyDates.slice():[];const today=todayKey();if(!dates.includes(today)){dates.push(today);dates.sort()}saveState({v3DailyDates:dates});if(typeof addPracticeSession==='function')addPracticeSession();$('dailyPlay').classList.add('hidden');$('dailyDone').classList.remove('hidden');$('dailyBar').style.width='100%';$('dailyDoneText').textContent=`Completaste ${dailyQueue.length} pasos: ${dailyOk} marcados como logrados y ${dailyRepeat} para repetir. Los pendientes tendrán más prioridad en próximos repasos.`;updateV3Stats();renderReview()}
 $('dailyStartBtn').onclick=()=>startDaily(false);$('dailyGood').onclick=()=>rateDaily(true);$('dailyRepeat').onclick=()=>rateDaily(false);$('dailyAgain').onclick=()=>startDaily(false);$('smartReviewBtn').onclick=()=>startDaily(true);

 const emergencyScenarios=[
  'Practicá comunicar una necesidad urgente usando únicamente señas que ya estudiaste y validaste.',
  'Practicá señalar o describir dónde está el problema usando tu repertorio aprendido, sin inventar una seña nueva.',
  'Practicá pedir ayuda de forma visual con recursos que ya hayas aprendido en LSA.',
  'Imaginá que la otra persona no comprendió: repetí el mensaje más lento, con mejor ubicación y mirada.'
 ];
 function emergencySelected(){const s=loadState();return Array.isArray(s.v3EmergencyWords)?s.v3EmergencyWords:[]}
 function toggleEmergency(word){let arr=emergencySelected();arr=arr.includes(word)?arr.filter(x=>x!==word):[...arr,word];saveState({v3EmergencyWords:arr});renderEmergencyDeck()}
 function renderEmergencyDeck(){if(!$('emergencyWords'))return;const selected=emergencySelected().filter(w=>practiceWords.includes(w));if(selected.length!==emergencySelected().length)saveState({v3EmergencyWords:selected});$('emergencyWords').innerHTML='';if(!practiceWords.length){$('emergencyWords').innerHTML='<span class="reviewEmpty">Primero agregá al menos una tarjeta en tu cuaderno.</span>';$('emergencyDrill').classList.add('hidden');return}practiceWords.forEach(w=>{const active=selected.includes(w),row=document.createElement('div');row.className='emergencyWord'+(active?' active':'');row.innerHTML=`<span>${w}</span><button>${active?'Quitar':'Agregar al mazo'}</button>`;row.querySelector('button').onclick=()=>toggleEmergency(w);$('emergencyWords').appendChild(row)});$('emergencyDrill').classList.toggle('hidden',!selected.length);if(selected.length&&$('emergencyPrompt').textContent==='—')pickEmergencyWord()}
 function pickEmergencyWord(){const arr=emergencySelected().filter(w=>practiceWords.includes(w));if(!arr.length)return;$('emergencyPrompt').textContent=arr[Math.floor(Math.random()*arr.length)];$('emergencyHint').textContent='Producí esta seña de memoria. Si dudás, verificá con la fuente donde la aprendiste.'}
 if($('emergencyNext'))$('emergencyNext').onclick=pickEmergencyWord;if($('emergencyScenario'))$('emergencyScenario').onclick=()=>{const txt=emergencyScenarios[Math.floor(Math.random()*emergencyScenarios.length)];$('emergencyPrompt').textContent='Situación simulada';$('emergencyHint').textContent=txt};
 if($('wordForm'))$('wordForm').addEventListener('submit',()=>setTimeout(renderEmergencyDeck,0));if($('wordList'))$('wordList').addEventListener('click',()=>setTimeout(renderEmergencyDeck,0));

 renderReview();updateV3Stats();renderEmergencyDeck();
})();