(()=>{
const $=id=>document.getElementById(id);
const symbols=['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'];
const es=['Hidrógeno','Helio','Litio','Berilio','Boro','Carbono','Nitrógeno','Oxígeno','Flúor','Neón','Sodio','Magnesio','Aluminio','Silicio','Fósforo','Azufre','Cloro','Argón','Potasio','Calcio','Escandio','Titanio','Vanadio','Cromo','Manganeso','Hierro','Cobalto','Níquel','Cobre','Zinc','Galio','Germanio','Arsénico','Selenio','Bromo','Kriptón','Rubidio','Estroncio','Itrio','Circonio','Niobio','Molibdeno','Tecnecio','Rutenio','Rodio','Paladio','Plata','Cadmio','Indio','Estaño','Antimonio','Telurio','Yodo','Xenón','Cesio','Bario','Lantano','Cerio','Praseodimio','Neodimio','Prometio','Samario','Europio','Gadolinio','Terbio','Disprosio','Holmio','Erbio','Tulio','Iterbio','Lutecio','Hafnio','Tantalio','Wolframio','Renio','Osmio','Iridio','Platino','Oro','Mercurio','Talio','Plomo','Bismuto','Polonio','Astato','Radón','Francio','Radio','Actinio','Torio','Protactinio','Uranio','Neptunio','Plutonio','Americio','Curio','Berkelio','Californio','Einsteinio','Fermio','Mendelevio','Nobelio','Lawrencio','Rutherfordio','Dubnio','Seaborgio','Bohrio','Hassio','Meitnerio','Darmstadtio','Roentgenio','Copernicio','Nihonio','Flerovio','Moscovio','Livermorio','Teneso','Oganesón'];
const items=symbols.map((s,i)=>({z:i+1,symbol:s,name:es[i]}));
let rows={},ready=false,activeZ=6;
const hero=document.querySelector('.hero .ey');if(hero)hero.textContent='Química · simulador v2';
const main=document.querySelector('main');
const insight=document.querySelector('.insightGrid');
const atomic=document.createElement('section');atomic.className='atomicStudio';atomic.id='modelo-atomico';atomic.innerHTML=`<div class="v2Head"><div><span class="ey">v2 · estructura electrónica</span><h2>Del casillero al átomo: capas, subniveles y orbitales</h2><p>Elegí un elemento y observá cómo su configuración electrónica explica su posición. La distribución se construye desde la configuración publicada por PubChem; no usamos una regla de Aufbau simplificada cuando el elemento tiene excepciones reales.</p></div><div class="v2Badges"><span>Configuración real</span><span>Capas electrónicas</span><span>Diagrama orbital</span></div></div><div class="atomGrid"><article class="atomPicker"><label for="v2Element"><b>Elemento</b></label><select id="v2Element"></select><div class="selectedBig"><div class="bigSymbol" id="v2Symbol">C</div><div class="bigMeta"><b id="v2Name">Carbono</b><span id="v2Meta">Z = 6</span></div></div><div class="configBox"><small>Configuración electrónica de referencia</small><code id="v2Config">Cargando…</code></div><div class="shells" id="v2Shells"></div><p class="shellNote" id="v2ShellNote"></p></article><article class="atomDetail"><span class="ey">Orbitales y valencia</span><h3 class="orbitalTitle">Diagrama de ocupación</h3><div class="orbitals" id="v2Orbitals"></div><div class="atomFacts"><div class="atomFact"><span>Período</span><b id="v2Period">—</b></div><div class="atomFact"><span>Grupo</span><b id="v2Group">—</b></div><div class="atomFact"><span>e⁻ capa externa</span><b id="v2Outer">—</b></div><div class="atomFact"><span>Estados oxidación</span><b id="v2Ox">—</b></div></div><div class="ionGuide"><h4>Átomo → ion: qué cambia</h4><p id="v2IonText">Seleccioná un elemento para ver la tendencia de ionización.</p><div class="ionCompare"><div class="radiusModel"><b>Átomo neutro</b><div class="radiusCircle atom" id="v2AtomCircle">C</div><small id="v2AtomRadius">radio atómico —</small></div><div class="arrow">→</div><div class="radiusModel"><b id="v2IonLabel">Ion / estado</b><div class="radiusCircle ion same" id="v2IonCircle">?</div><small id="v2IonRadius">comparación cualitativa</small></div></div></div></article></div>`;
if(insight)insight.insertAdjacentElement('afterend',atomic);else main.appendChild(atomic);
const reason=document.createElement('section');reason.className='reasonLab';reason.id='razonar-tendencias';reason.innerHTML=`<div class="v2Head"><div><span class="ey">v2 · tendencias razonadas</span><h2>¿Cuál tiene mayor propiedad… y por qué?</h2><p>Compará dos elementos con los valores de referencia y usá la tabla para justificar el resultado. Las tendencias ayudan, pero los datos reales mandan cuando hay excepciones.</p></div><div class="v2Badges"><span>Comparación</span><span>Justificación</span></div></div><div class="reasonGrid"><article class="reasonCard"><div class="reasonControls"><label><b>Elemento A</b><select id="reasonA"></select></label><label><b>Elemento B</b><select id="reasonB"></select></label><label><b>Propiedad</b><select id="reasonProp"><option value="Electronegativity">electronegatividad</option><option value="AtomicRadius">radio atómico</option><option value="IonizationEnergy">energía de ionización</option><option value="ElectronAffinity">afinidad electrónica</option></select></label><button id="reasonNew">Generar comparación</button></div><div class="reasonFeedback" id="reasonFeedback">Elegí dos elementos y una propiedad.</div></article><article class="reasonQuestion"><span class="rqEy">Pregunta razonada</span><h3 id="reasonQuestion">Esperando selección…</h3><div class="reasonChoices" id="reasonChoices"></div></article></div>`;atomic.insertAdjacentElement('afterend',reason);
const react=document.createElement('section');react.className='reactivityLab';react.id='reactividad';react.innerHTML=`<div class="v2Head"><div><span class="ey">v2 · comportamiento químico</span><h2>Familias: reactividad, iones y compuestos típicos</h2><p>Las familias permiten anticipar patrones sin memorizar 118 casos aislados. Estos son patrones generales: siempre hay excepciones y la reacción concreta depende de condiciones y especie química.</p></div></div><div class="reactivityGrid" id="reactivityGrid"></div><div class="v2Note"><b>Importante:</b> “reactivo” no significa automáticamente “peligroso”, y una familia no determina por sí sola el comportamiento de todos sus compuestos. Las fichas sirven para orientar el razonamiento químico.</div>`;reason.insertAdjacentElement('afterend',react);
const families=[
['Grupo 1 · alcalinos','Un electrón externo; los metales del grupo tienden a oxidarse y formar M⁺. La reactividad con agua aumenta marcadamente al descender.',['ns¹','M⁺','reductores'],['NaCl','KOH','Li₂CO₃']],
['Grupo 2 · alcalinotérreos','Dos electrones externos y tendencia habitual a M²⁺. Sus óxidos e hidróxidos muestran carácter básico variable.',['ns²','M²⁺','óxidos'],['MgO','CaCO₃','Ca(OH)₂']],
['Grupo 14 · carbono','Pasa de no metal a metales al bajar. La química covalente es central y los estados +4/+2 ganan diferente importancia según el elemento.',['ns²np²','covalencia','+4 / +2'],['CO₂','SiO₂','SnCl₂']],
['Grupo 15 · pnictógenos','Cinco electrones de valencia en los representativos. Son frecuentes −3, +3 y +5, con gran diversidad de enlaces y estructuras.',['ns²np³','−3/+3/+5','redox'],['NH₃','H₃PO₄','N₂O₅']],
['Grupo 16 · calcógenos','Seis electrones externos; −2 es muy común para O/S/Se, aunque aparecen estados positivos en los elementos más pesados y en oxocompuestos.',['ns²np⁴','−2','oxocompuestos'],['H₂O','SO₂','SO₄²⁻']],
['Grupo 17 · halógenos','Alta electronegatividad y fuerte tendencia a formar X⁻ en sales binarias. La capacidad oxidante molecular cambia al descender.',['ns²np⁵','X⁻','oxidantes'],['NaCl','HBr','KI']],
['Grupo 18 · gases nobles','Capas externas completas (He: 1s²). Su baja reactividad es característica, aunque Xe y otros pesados forman compuestos bajo condiciones adecuadas.',['capa completa','baja reactividad','monoatómicos'],['XeF₂','XeF₄','KrF₂']],
['Metales de transición','Los electrones d participan en enlace y redox; son comunes múltiples estados de oxidación, complejos coloreados y actividad catalítica.',['bloque d','redox','complejos'],['FeCl₃','CuSO₄','KMnO₄']],
['Lantánidos','Predomina el estado +3 y el llenado 4f. Sus propiedades magnéticas y espectroscópicas son importantes en materiales.',['4f','+3','materiales'],['CeO₂','Nd₂O₃','Eu₂O₃']],
['Actínidos','Serie 5f; todos radiactivos. Presentan estados de oxidación variables y química nuclear relevante.',['5f','radiactivos','nuclear'],['UO₂','PuO₂','ThO₂']]
];
$('reactivityGrid').innerHTML=families.map(([t,p,tags,ex])=>`<article class="familyChem"><h3>${t}</h3><p>${p}</p><div class="chemTags">${tags.map(x=>`<span>${x}</span>`).join('')}</div><div class="compoundExamples"><b>Ejemplos de especies/compuestos:</b> ${ex.join(' · ')}</div></article>`).join('');
function groupOf(z){if(z===1)return 1;if(z===2)return 18;if(z>=3&&z<=10)return [1,2,13,14,15,16,17,18][z-3];if(z>=11&&z<=18)return [1,2,13,14,15,16,17,18][z-11];if(z>=19&&z<=36)return z-18;if(z>=37&&z<=54)return z-36;if(z===55||z===87)return 1;if(z===56||z===88)return 2;if((z>=57&&z<=71)||(z>=89&&z<=103))return null;if(z>=72&&z<=86)return z-68;if(z>=104&&z<=118)return z-100;return null}
function periodOf(z){if(z<=2)return 1;if(z<=10)return 2;if(z<=18)return 3;if(z<=36)return 4;if(z<=54)return 5;if(z<=86)return 6;return 7}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function parseTable(j){const cols=j.Table.Columns.Column;for(const r of j.Table.Row){const obj={};r.Cell.forEach((v,i)=>obj[cols[i]]=v);rows[Number(obj.AtomicNumber)]=obj}ready=true;renderAtom(activeZ);makeReason()}
async function load(){try{const r=await fetch('https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON');if(!r.ok)throw new Error('PubChem '+r.status);parseTable(await r.json())}catch(e){console.error(e);$('v2Config').textContent='No se pudieron cargar los datos de PubChem. La tabla principal sigue disponible.'}}
function expandConfig(z,seen=new Set()){const r=rows[z];if(!r)return'';let cfg=(r.ElectronConfiguration||'').trim();const m=cfg.match(/^\[([A-Za-z]+)\]\s*/);if(!m)return cfg;if(seen.has(z))return cfg;seen.add(z);const coreZ=symbols.indexOf(m[1])+1;if(!coreZ)return cfg;return `${expandConfig(coreZ,seen)} ${cfg.slice(m[0].length)}`.trim()}
function tokens(z){const out=[];const cfg=expandConfig(z);const re=/(\d+)([spdf])(\d+)/g;let m;while((m=re.exec(cfg)))out.push({n:Number(m[1]),type:m[2],e:Number(m[3]),label:`${m[1]}${m[2]}`});return out}
function shellCounts(z){const c={};for(const t of tokens(z))c[t.n]=(c[t.n]||0)+t.e;return c}
function orbitalBoxes(type,e){const n={s:1,p:3,d:5,f:7}[type]||1,occ=Array(n).fill(0);for(let i=0;i<Math.min(e,n);i++)occ[i]++;for(let i=0;i<Math.max(0,e-n);i++)occ[i]++;return occ.map(x=>`<span class="obox">${x===2?'↑↓':x===1?'↑':''}</span>`).join('')}
function simpleIon(z){const g=groupOf(z),r=rows[z]||{},family=(r.GroupBlock||'').toLowerCase();if(z===1)return{label:'H⁺ / H⁻',charge:0,kind:'same',text:'El hidrógeno es especial: puede aparecer formalmente como +1 o −1 según la especie; no conviene tratarlo como un metal alcalino ordinario.'};if(family.includes('transition')||family.includes('lanthanide')||family.includes('actinide'))return{label:'Estados variables',charge:0,kind:'same',text:`No asignamos un ion único. Estados de oxidación reportados: ${r.OxidationStates||'variables'}. En metales de transición y series f, la química depende fuertemente de la especie.`};if(g===1)return{label:'M⁺',charge:1,kind:'smaller',text:'Al perder un electrón forma habitualmente un catión +1. Un catión es más pequeño que el átomo neutro porque disminuye la repulsión electrónica y puede perderse una capa externa.'};if(g===2)return{label:'M²⁺',charge:2,kind:'smaller',text:'La formación de M²⁺ es característica. El catión resulta cualitativamente más pequeño que el átomo neutro.'};if(g===13)return{label:'M³⁺',charge:3,kind:'smaller',text:'En muchos elementos del grupo 13 el estado +3 es importante; al bajar también gana relevancia +1. El ion positivo es menor que el átomo neutro.'};if(g===15)return{label:'X³⁻ / estados +',charge:-3,kind:'larger',text:'En compuestos iónicos simples, los miembros no metálicos pueden alcanzar −3; también son comunes estados positivos +3/+5. Un anión simple es mayor que el átomo neutro.'};if(g===16)return{label:'X²⁻',charge:-2,kind:'larger',text:'Para los calcógenos no metálicos, −2 es muy frecuente. Al ganar electrones aumenta la repulsión electrónica y el anión es mayor que el átomo.'};if(g===17)return{label:'X⁻',charge:-1,kind:'larger',text:'Los halógenos forman aniones −1 con mucha frecuencia. El anión tiene mayor radio que el átomo neutro.'};if(g===18)return{label:'Sin ion simple habitual',charge:0,kind:'same',text:'La capa externa completa reduce la tendencia a formar iones monoatómicos simples en condiciones ordinarias.'};return{label:'Predomina enlace covalente / variable',charge:0,kind:'same',text:`No conviene predecir un ion monoatómico único solo desde el grupo. Estados de oxidación reportados: ${r.OxidationStates||'—'}.`}}
function renderAtom(z){activeZ=z;const e=items[z-1],r=rows[z]||{};$('v2Element').value=String(z);$('v2Symbol').textContent=e.symbol;$('v2Name').textContent=e.name;$('v2Meta').textContent=`Z = ${z} · período ${periodOf(z)}${groupOf(z)?` · grupo ${groupOf(z)}`:' · bloque f'}`;$('v2Config').textContent=r.ElectronConfiguration||'Esperando datos de PubChem…';$('v2Period').textContent=periodOf(z);$('v2Group').textContent=groupOf(z)||'serie f';$('v2Ox').textContent=r.OxidationStates||'—';const sh=shellCounts(z),levels=Object.keys(sh).map(Number).sort((a,b)=>a-b),maxN=levels.length?Math.max(...levels):null;$('v2Outer').textContent=maxN?sh[maxN]:'—';$('v2Shells').innerHTML=levels.length?levels.map(n=>`<div class="shell" style="--e:${Math.min(10,sh[n])}"><b>${sh[n]}</b><span>n=${n}</span></div>`).join(''):'<div class="muted">Cargando distribución…</div>';$('v2ShellNote').textContent=maxN?`Distribución por niveles principales: ${levels.map(n=>`${n}: ${sh[n]} e⁻`).join(' · ')}. “Electrones de capa externa” no equivale siempre a valencia química, especialmente en bloques d y f.`:'';const ts=tokens(z);$('v2Orbitals').innerHTML=ts.length?ts.map(t=>`<div class="subshell"><span>${t.label}${t.e}</span><div class="boxes">${orbitalBoxes(t.type,t.e)}</div></div>`).join(''):'<span class="muted">Esperando configuración electrónica…</span>';const ion=simpleIon(z);$('v2IonLabel').textContent=ion.label;$('v2IonText').textContent=ion.text;$('v2AtomCircle').textContent=e.symbol;$('v2IonCircle').textContent=ion.label.replace(' / ','/');$('v2IonCircle').className=`radiusCircle ion ${ion.kind}`;$('v2AtomRadius').textContent=r.AtomicRadius?`radio atómico de referencia: ${r.AtomicRadius} pm`:'radio atómico: —';$('v2IonRadius').textContent=ion.kind==='smaller'?'catión: radio menor (cualitativo)':ion.kind==='larger'?'anión: radio mayor (cualitativo)':'sin comparación iónica simple'}
function options(){return items.map(e=>`<option value="${e.z}">${e.z} · ${e.symbol} · ${e.name}</option>`).join('')}
$('v2Element').innerHTML=options();$('reasonA').innerHTML=options();$('reasonB').innerHTML=options();$('reasonA').value='11';$('reasonB').value='17';
$('v2Element').onchange=e=>renderAtom(Number(e.target.value));
document.addEventListener('click',e=>{const b=e.target.closest('.element[data-z]');if(!b)return;const z=Number(b.dataset.z);renderAtom(z);setTimeout(()=>atomic.scrollIntoView({behavior:'smooth',block:'start'}),80)});
const props={Electronegativity:{name:'electronegatividad',unit:'',trend:'En general aumenta hacia la derecha y hacia arriba, con excepciones y valores ausentes para varios gases nobles.'},AtomicRadius:{name:'radio atómico',unit:'pm',trend:'En general disminuye de izquierda a derecha y aumenta al bajar por la incorporación de niveles electrónicos.'},IonizationEnergy:{name:'energía de ionización',unit:'eV',trend:'En general aumenta hacia la derecha y hacia arriba; subniveles y apareamientos producen excepciones locales.'},ElectronAffinity:{name:'afinidad electrónica',unit:'eV',trend:'Es una propiedad más irregular que radio o ionización; conviene apoyarse especialmente en el valor experimental/tabulado.'}};
function makeReason(){if(!ready)return;const a=Number($('reasonA').value),b=Number($('reasonB').value),key=$('reasonProp').value,pa=props[key],ra=rows[a]||{},rb=rows[b]||{},va=num(ra[key]),vb=num(rb[key]),ea=items[a-1],eb=items[b-1];$('reasonFeedback').className='reasonFeedback';if(va===null||vb===null){$('reasonQuestion').textContent=`No hay dato comparable de ${pa.name} para ambos elementos.`;$('reasonChoices').innerHTML='';$('reasonFeedback').textContent='Elegí otra propiedad o par de elementos.';return}const higher=va>vb?a:b,lower=va>vb?b:a,hi=items[higher-1],lo=items[lower-1];$('reasonQuestion').textContent=`¿Cuál tiene mayor ${pa.name}: ${ea.symbol} o ${eb.symbol}?`;$('reasonChoices').innerHTML=`<button data-z="${a}">${ea.symbol} · ${ea.name}</button><button data-z="${b}">${eb.symbol} · ${eb.name}</button>`;[...$('reasonChoices').children].forEach(btn=>btn.onclick=()=>{const pick=Number(btn.dataset.z),ok=pick===higher;$('reasonFeedback').className='reasonFeedback '+(ok?'ok':'bad');$('reasonFeedback').innerHTML=`<b>${ok?'✓ Correcto':'No en este par'}.</b> ${hi.symbol}: ${rows[higher][key]} ${pa.unit}; ${lo.symbol}: ${rows[lower][key]} ${pa.unit}. ${pa.trend} Períodos/grupos: ${ea.symbol} (${periodOf(a)}, ${groupOf(a)||'f'}) · ${eb.symbol} (${periodOf(b)}, ${groupOf(b)||'f'}).`;});}
$('reasonNew').onclick=makeReason;$('reasonA').onchange=makeReason;$('reasonB').onchange=makeReason;$('reasonProp').onchange=makeReason;
renderAtom(activeZ);load();
})();
