(()=>{
const $=id=>document.getElementById(id);
const hero=document.querySelector('.hero .ey');if(hero)hero.textContent='Química · simulador v4';
const source=document.querySelector('.sourceNote');
const root=document.createElement('div');root.id='v4Labs';root.innerHTML=`
<section class="moleculeLab" id="lewis-vsepr"><div class="v4Head"><div><span class="ey">v4 · Lewis + VSEPR</span><h2>De electrones de valencia a geometría molecular</h2><p>Explorá moléculas e iones representativos. El simulador cuenta electrones, identifica dominios alrededor del átomo central y conecta estructura de Lewis, notación AXE, geometría y polaridad.</p></div><div class="v4Badges"><span>Lewis</span><span>VSEPR</span><span>Polaridad</span><span>Resonancia</span></div></div><div class="molGrid"><article class="chemCard"><div class="singleControl"><label>Molécula o ion<select id="molSelect"></select></label></div><div class="molStage"><div class="molCanvas" id="molCanvas"></div></div><div class="molFacts"><div><span>e⁻ de valencia</span><b id="molElectrons">—</b></div><div><span>AXE</span><b id="molAxe">—</b></div><div><span>Geometría</span><b id="molGeometry">—</b></div><div><span>Ángulo ideal/aprox.</span><b id="molAngle">—</b></div><div><span>Pares libres central</span><b id="molLone">—</b></div><div><span>Polaridad molecular</span><b id="molPolarity">—</b></div></div></article><article class="chemCard"><span class="ey">Razonamiento paso a paso</span><h3 id="molTitle">—</h3><div class="nameWorkbench" id="molSteps"></div><div class="polarityBar"><i id="molPolarityBar"></i></div><p id="molPolarityText"></p><div class="resonanceNote" id="molCaution"></div></article></div></section>
<section class="oxidationLab" id="numeros-oxidacion"><div class="v4Head"><div><span class="ey">v4 · números de oxidación</span><h2>Resolvé el estado de oxidación desconocido</h2><p>Usá la suma algebraica de números de oxidación y la carga total. Incluimos excepciones importantes como peróxidos y OF₂ para evitar reglas memorizadas sin contexto.</p></div><div class="v4Badges"><span>Balance algebraico</span><span>Excepciones</span></div></div><div class="oxidGrid"><article class="chemCard"><div class="singleControl"><label>Ejercicio<select id="oxidSelect"></select></label></div><div class="oxidEquation" id="oxidEquation">—</div><div class="oxidTable" id="oxidTable"></div><div class="chemControls"><label>Tu respuesta<input id="oxidAnswer" inputmode="numeric" placeholder="Ej.: +6"></label><label>&nbsp;<button id="oxidCheck">Comprobar</button></label></div><div class="practiceFeedback" id="oxidFeedback">Calculá primero la contribución conocida.</div></article><article class="chemCard"><h3>Reglas que sí conviene entender</h3><div class="nameWorkbench"><div class="nameStep"><b>Elemento libre</b><span>número de oxidación 0.</span></div><div class="nameStep"><b>Ion monoatómico</b><span>coincide con su carga.</span></div><div class="nameStep"><b>F</b><span>−1 en sus compuestos.</span></div><div class="nameStep"><b>O</b><span>usualmente −2; peróxidos −1; con F puede ser positivo.</span></div><div class="nameStep"><b>H</b><span>usualmente +1; en hidruros metálicos puede ser −1.</span></div><div class="nameStep"><b>Suma</b><span>igual a 0 en especie neutra o a la carga en un ion.</span></div></div></article></div></section>
<section class="nomenLab" id="nomenclatura"><div class="v4Head"><div><span class="ey">v4 · formulación y nomenclatura</span><h2>Pasá de fórmula a nombre y de nombre a fórmula</h2><p>Práctica guiada con nomenclatura Stock y sistemática en ejemplos representativos. El objetivo es relacionar composición, estado de oxidación y prefijos, no memorizar una lista.</p></div><div class="v4Badges"><span>Stock</span><span>Sistemática</span><span>Práctica</span></div></div><div class="nomenGrid"><article class="chemCard"><div class="singleControl"><label>Compuesto<select id="nameSelect"></select></label></div><div class="nameAnswer" id="nameFormula">—</div><div class="nameWorkbench"><div class="nameStep"><b>Nombre Stock</b><span id="nameStock">—</span></div><div class="nameStep"><b>Nombre sistemático</b><span id="nameSystematic">—</span></div><div class="nameStep"><b>Cómo razonarlo</b><span id="nameReason">—</span></div></div></article><article class="chemCard"><span class="ey">Desafío</span><h3 id="nameQuizQ">—</h3><div class="practiceChoices" id="nameChoices"></div><div class="practiceFeedback" id="nameFeedback">Elegí una respuesta.</div><button id="nameNext">Otro desafío</button></article></div></section>
<section class="reactionLab" id="reacciones-basicas"><div class="v4Head"><div><span class="ey">v4 · reacciones químicas</span><h2>Reconocé patrones de reacción y qué información aporta una ecuación</h2><p>Trabajá con ecuaciones ya balanceadas para identificar síntesis, descomposición, desplazamiento, precipitación, neutralización y combustión. Una ecuación balanceada conserva átomos; no demuestra por sí sola mecanismo ni velocidad.</p></div><div class="v4Badges"><span>Balance</span><span>Clasificación</span><span>Contexto</span></div></div><div class="reactionGrid"><article class="chemCard"><div class="reactionList" id="reactionList"></div></article><article class="reactionSim"><span class="ey">Desafío de clasificación</span><div class="big" id="reactionQ">—</div><div class="practiceChoices" id="reactionChoices"></div><div class="practiceFeedback" id="reactionFeedback">Elegí el tipo de reacción.</div><div class="miniGrid"><div><span>Correctas</span><b id="reactionOK">0</b></div><div><span>Intentos</span><b id="reactionAttempts">0</b></div></div><button id="reactionNext">Otra reacción</button></article></div></section>`;
if(source)source.insertAdjacentElement('beforebegin',root);else document.querySelector('main')?.appendChild(root);

const molecules=[
{id:'CO2',label:'CO₂',name:'Dióxido de carbono',central:'C',outer:['O','O'],bonds:[2,2],ve:16,axe:'AX₂',geom:'Lineal',angle:'180°',lone:0,polar:'No polar',polarity:10,steps:['C aporta 4 e⁻ y 2 O aportan 12 e⁻: total 16.','C queda al centro y se forman dos enlaces dobles C=O en la representación principal.','Alrededor de C hay 2 dominios electrónicos y 0 pares libres → AX₂.','Los dipolos C=O son opuestos y se cancelan en una molécula lineal simétrica.'],note:'No requiere resonancia equivalente para la estructura principal de Lewis en este nivel.'},
{id:'BF3',label:'BF₃',name:'Trifluoruro de boro',central:'B',outer:['F','F','F'],bonds:[1,1,1],ve:24,axe:'AX₃',geom:'Trigonal plana',angle:'120°',lone:0,polar:'No polar (molécula simétrica)',polarity:15,steps:['B aporta 3 e⁻ y 3 F aportan 21 e⁻: total 24.','Tres enlaces B–F rodean al B.','Hay 3 dominios y 0 pares libres → AX₃.','La geometría simétrica cancela los dipolos de enlace.'],note:'BF₃ es una excepción clásica al octeto: el B queda con 6 electrones a su alrededor en la estructura simple.'},
{id:'CH4',label:'CH₄',name:'Metano',central:'C',outer:['H','H','H','H'],bonds:[1,1,1,1],ve:8,axe:'AX₄',geom:'Tetraédrica',angle:'109,5°',lone:0,polar:'No polar',polarity:8,steps:['C aporta 4 e⁻ y 4 H aportan 4 e⁻: total 8.','Se forman cuatro enlaces simples C–H.','4 dominios enlazantes y 0 pares libres → AX₄.','La disposición tetraédrica simétrica cancela los dipolos.'],note:'Cada H completa un dueto; C completa el octeto.'},
{id:'NH3',label:'NH₃',name:'Amoníaco',central:'N',outer:['H','H','H'],bonds:[1,1,1],ve:8,axe:'AX₃E',geom:'Piramidal trigonal',angle:'≈107°',lone:1,polar:'Polar',polarity:75,steps:['N aporta 5 e⁻ y 3 H aportan 3 e⁻: total 8.','Tres pares forman enlaces N–H y queda un par libre sobre N.','4 dominios electrónicos: 3 enlaces + 1 par libre → AX₃E.','El par libre rompe la simetría y los dipolos no se cancelan.'],note:'La geometría electrónica es tetraédrica; la geometría molecular es piramidal trigonal.'},
{id:'H2O',label:'H₂O',name:'Agua',central:'O',outer:['H','H'],bonds:[1,1],ve:8,axe:'AX₂E₂',geom:'Angular',angle:'≈104,5°',lone:2,polar:'Polar',polarity:90,steps:['O aporta 6 e⁻ y 2 H aportan 2 e⁻: total 8.','Se forman dos enlaces O–H y quedan dos pares libres en O.','4 dominios: 2 enlaces + 2 pares libres → AX₂E₂.','La geometría angular impide que los dipolos O–H se cancelen.'],note:'Los pares libres ejercen mayor repulsión y reducen el ángulo respecto de 109,5°.'},
{id:'SO2',label:'SO₂',name:'Dióxido de azufre',central:'S',outer:['O','O'],bonds:[2,1],ve:18,axe:'AX₂E',geom:'Angular',angle:'≈119°',lone:1,polar:'Polar',polarity:80,steps:['S aporta 6 e⁻ y 2 O aportan 12 e⁻: total 18.','La descripción de Lewis incluye estructuras de resonancia equivalentes.','Alrededor de S se consideran 3 dominios principales: 2 enlaces + 1 par libre → AX₂E.','La forma angular produce un momento dipolar neto.'],note:'La distribución electrónica real se describe mejor con resonancia; no interpretes un único enlace simple/doble como localizado permanentemente.'},
{id:'PCl5',label:'PCl₅',name:'Pentacloruro de fósforo',central:'P',outer:['Cl','Cl','Cl','Cl','Cl'],bonds:[1,1,1,1,1],ve:40,axe:'AX₅',geom:'Bipiramidal trigonal',angle:'90° / 120° / 180°',lone:0,polar:'No polar en geometría ideal',polarity:18,steps:['P aporta 5 e⁻ y 5 Cl aportan 35 e⁻: total 40.','Cinco enlaces P–Cl generan cinco dominios.','5 dominios, sin pares libres → AX₅.','En la geometría ideal, la distribución simétrica cancela el dipolo global.'],note:'Es un ejemplo de especie hipervalente en el modelo de Lewis; el enlace real no debe imaginarse simplemente como cinco pares localizados idénticos.'},
{id:'SF6',label:'SF₆',name:'Hexafluoruro de azufre',central:'S',outer:['F','F','F','F','F','F'],bonds:[1,1,1,1,1,1],ve:48,axe:'AX₆',geom:'Octaédrica',angle:'90° / 180°',lone:0,polar:'No polar en geometría ideal',polarity:10,steps:['S aporta 6 e⁻ y 6 F aportan 42 e⁻: total 48.','Seis enlaces S–F producen seis dominios.','6 dominios y 0 pares libres → AX₆.','La simetría octaédrica cancela los dipolos de enlace.'],note:'Otro ejemplo hipervalente; VSEPR describe muy bien su geometría global.'},
{id:'XeF4',label:'XeF₄',name:'Tetrafluoruro de xenón',central:'Xe',outer:['F','F','F','F'],bonds:[1,1,1,1],ve:36,axe:'AX₄E₂',geom:'Cuadrada planar',angle:'90° / 180°',lone:2,polar:'No polar en geometría ideal',polarity:12,steps:['Xe aporta 8 e⁻ y 4 F aportan 28 e⁻: total 36.','Cuatro enlaces Xe–F y dos pares libres generan seis dominios.','Los pares libres ocupan posiciones opuestas en la geometría electrónica octaédrica → AX₄E₂.','La molécula resultante es cuadrada planar y simétrica.'],note:'Los gases nobles pesados pueden formar compuestos; “gas noble” no significa reactividad absolutamente nula.'},
{id:'NH4',label:'NH₄⁺',name:'Ion amonio',central:'N',outer:['H','H','H','H'],bonds:[1,1,1,1],ve:8,axe:'AX₄',geom:'Tetraédrica',angle:'109,5°',lone:0,polar:'Ion: distribución tetraédrica simétrica',polarity:35,steps:['N aporta 5 e⁻ + 4 H aportan 4 e⁻ − 1 e⁻ por la carga +: total 8.','Hay cuatro enlaces N–H y ningún par libre en N.','4 dominios → AX₄ tetraédrico.','La especie tiene carga neta +1; hablar de “polar/no polar” como en una molécula neutra requiere cautela.'],note:'La carga formal total del ion es +1. La geometría sigue siendo tetraédrica.'},
{id:'NO3',label:'NO₃⁻',name:'Ion nitrato',central:'N',outer:['O','O','O'],bonds:[2,1,1],ve:24,axe:'AX₃',geom:'Trigonal plana',angle:'120°',lone:0,polar:'Ion trigonal plano; enlaces equivalentes por resonancia',polarity:45,steps:['N aporta 5 e⁻ + 3 O aportan 18 e⁻ + 1 e⁻ por la carga −: total 24.','Las estructuras de Lewis equivalentes distribuyen el enlace π/carga entre los tres O.','N tiene 3 dominios y 0 pares libres → AX₃ trigonal plano.','Los tres enlaces N–O son equivalentes en la estructura real por resonancia.'],note:'No hay un “doble enlace fijo” en un oxígeno específico; la resonancia representa deslocalización.'},
{id:'CO3',label:'CO₃²⁻',name:'Ion carbonato',central:'C',outer:['O','O','O'],bonds:[2,1,1],ve:24,axe:'AX₃',geom:'Trigonal plana',angle:'120°',lone:0,polar:'Ion trigonal plano; resonancia',polarity:45,steps:['C aporta 4 e⁻ + 3 O aportan 18 e⁻ + 2 e⁻ por la carga 2−: total 24.','Tres estructuras de resonancia equivalentes distribuyen el carácter de doble enlace.','3 dominios alrededor de C → AX₃.','La geometría es trigonal plana y los enlaces C–O resultan equivalentes en promedio.'],note:'La carga total es 2− y se distribuye en el ion; no debe asignarse como localizada rígidamente en una sola estructura.'}
];
const molSelect=$('molSelect');molSelect.innerHTML=molecules.map((m,i)=>`<option value="${i}">${m.label} · ${m.name}</option>`).join('');
function positions(n){if(n===2)return[[32,90],[200,90]];if(n===3)return[[116,10],[30,160],[202,160]];if(n===4)return[[116,5],[15,95],[217,95],[116,178]];if(n===5)return[[116,0],[22,72],[210,72],[48,176],[184,176]];return[[116,0],[20,55],[212,55],[20,165],[212,165],[116,185]]}
function renderMol(){const m=molecules[Number(molSelect.value)||0],c=$('molCanvas');c.innerHTML='';const center=document.createElement('div');center.className='centerAtom';center.textContent=m.central;c.appendChild(center);const pts=positions(m.outer.length);const cx=140,cy=115;pts.forEach((p,i)=>{const ox=p[0]+24,oy=p[1]+24,dx=ox-cx,dy=oy-cy,len=Math.sqrt(dx*dx+dy*dy)-48,ang=Math.atan2(dy,dx)*180/Math.PI;const line=document.createElement('div');line.className='bondLine';line.style.left=`${cx}px`;line.style.top=`${cy}px`;line.style.width=`${Math.max(22,len)}px`;line.style.transform=`rotate(${ang}deg)`;c.appendChild(line);if((m.bonds[i]||1)>1){const line2=line.cloneNode();line2.style.marginTop='6px';c.appendChild(line2)}const a=document.createElement('div');a.className='outerAtom';a.style.left=`${p[0]}px`;a.style.top=`${p[1]}px`;a.textContent=m.outer[i];c.appendChild(a)});for(let i=0;i<m.lone;i++){const lp=document.createElement('div');lp.className='lonePair';lp.textContent='••';lp.style.left=i%2===0?'88px':'168px';lp.style.top=i<2?'58px':'145px';c.appendChild(lp)}$('molElectrons').textContent=m.ve;$('molAxe').textContent=m.axe;$('molGeometry').textContent=m.geom;$('molAngle').textContent=m.angle;$('molLone').textContent=m.lone;$('molPolarity').textContent=m.polar;$('molTitle').textContent=`${m.label} · ${m.name}`;$('molSteps').innerHTML=m.steps.map((s,i)=>`<div class="nameStep"><b>${i+1} · ${['Contar electrones','Construir Lewis','Aplicar VSEPR','Evaluar polaridad'][i]}</b><span>${s}</span></div>`).join('');$('molPolarityBar').style.width=`${m.polarity}%`;$('molPolarityText').textContent=m.polar.includes('Polar')&&!m.polar.includes('No polar')?'La geometría y la distribución de enlaces producen separación neta de carga.':'La simetría global reduce o cancela el momento dipolar neto en el modelo ideal.';$('molCaution').innerHTML=`<b>Detalle importante:</b> ${m.note}`}
molSelect.onchange=renderMol;renderMol();

const oxidCases=[
{label:'H₂O → O',formula:'H₂O',unknown:'O',known:'2 H × (+1)',charge:0,answer:-2,explain:'2(+1)+x=0 → x=−2.'},
{label:'H₂O₂ → O (peróxido)',formula:'H₂O₂',unknown:'O',known:'2 H × (+1)',charge:0,answer:-1,explain:'2(+1)+2x=0 → x=−1. Es la excepción peróxido.'},
{label:'OF₂ → O',formula:'OF₂',unknown:'O',known:'2 F × (−1)',charge:0,answer:2,explain:'x+2(−1)=0 → x=+2. El F es más electronegativo y conserva −1.'},
{label:'NH₃ → N',formula:'NH₃',unknown:'N',known:'3 H × (+1)',charge:0,answer:-3,explain:'x+3(+1)=0 → x=−3.'},
{label:'NO₃⁻ → N',formula:'NO₃⁻',unknown:'N',known:'3 O × (−2)',charge:-1,answer:5,explain:'x+3(−2)=−1 → x=+5.'},
{label:'KMnO₄ → Mn',formula:'KMnO₄',unknown:'Mn',known:'K +1; 4 O × (−2)',charge:0,answer:7,explain:'(+1)+x+4(−2)=0 → x=+7.'},
{label:'Cr₂O₇²⁻ → Cr',formula:'Cr₂O₇²⁻',unknown:'Cr',known:'7 O × (−2)',charge:-2,answer:6,explain:'2x+7(−2)=−2 → 2x=12 → x=+6.'},
{label:'Fe₂O₃ → Fe',formula:'Fe₂O₃',unknown:'Fe',known:'3 O × (−2)',charge:0,answer:3,explain:'2x+3(−2)=0 → 2x=6 → x=+3.'},
{label:'H₂SO₄ → S',formula:'H₂SO₄',unknown:'S',known:'2 H × (+1); 4 O × (−2)',charge:0,answer:6,explain:'2(+1)+x+4(−2)=0 → x=+6.'}
];
const oxidSelect=$('oxidSelect');oxidSelect.innerHTML=oxidCases.map((x,i)=>`<option value="${i}">${x.label}</option>`).join('');
function renderOxid(){const o=oxidCases[Number(oxidSelect.value)||0];$('oxidEquation').textContent=`${o.formula} · hallar ${o.unknown}`;$('oxidTable').innerHTML=`<div class="oxidRow"><b>Conocidos</b><span>${o.known}</span><span>carga ${o.charge>=0?'+':''}${o.charge}</span></div><div class="oxidRow"><b>Incógnita</b><span>${o.unknown} = x</span><span>?</span></div>`;$('oxidAnswer').value='';$('oxidFeedback').className='practiceFeedback';$('oxidFeedback').textContent='Planteá la suma algebraica y comparala con la carga total.'}
oxidSelect.onchange=renderOxid;$('oxidCheck').onclick=()=>{const o=oxidCases[Number(oxidSelect.value)||0],raw=$('oxidAnswer').value.trim().replace('−','-').replace('＋','+'),n=Number(raw);const ok=n===o.answer;$('oxidFeedback').className='practiceFeedback '+(ok?'ok':'bad');$('oxidFeedback').innerHTML=`<b>${ok?'✓ Correcto.':'Todavía no.'}</b> ${o.explain} Por eso ${o.unknown} = ${o.answer>0?'+':''}${o.answer}.`};renderOxid();

const names=[
{f:'NaCl',stock:'cloruro de sodio',sys:'monocloruro de sodio (el “mono-” suele omitirse en uso habitual)',reason:'Na trabaja aquí como +1 y Cl como −1: proporción 1:1.'},
{f:'CaO',stock:'óxido de calcio',sys:'monóxido de calcio',reason:'Ca²⁺ y O²⁻ se neutralizan 1:1.'},
{f:'FeCl₂',stock:'cloruro de hierro(II)',sys:'dicloruro de hierro',reason:'Dos Cl⁻ aportan −2, por lo que Fe debe estar en +2.'},
{f:'FeCl₃',stock:'cloruro de hierro(III)',sys:'tricloruro de hierro',reason:'Tres Cl⁻ aportan −3, por lo que Fe está en +3.'},
{f:'Cu₂O',stock:'óxido de cobre(I)',sys:'monóxido de dicobre',reason:'O es −2; los dos Cu suman +2 → cada Cu es +1.'},
{f:'CuO',stock:'óxido de cobre(II)',sys:'monóxido de cobre',reason:'O es −2 y la proporción es 1:1 → Cu es +2.'},
{f:'CO₂',stock:'óxido de carbono(IV)',sys:'dióxido de carbono',reason:'Dos O en −2 suman −4 → C es +4.'},
{f:'N₂O₅',stock:'óxido de nitrógeno(V)',sys:'pentóxido de dinitrógeno',reason:'Cinco O suman −10; dos N deben sumar +10 → cada N es +5.'},
{f:'SO₃',stock:'óxido de azufre(VI)',sys:'trióxido de azufre',reason:'Tres O suman −6 → S es +6.'},
{f:'PCl₅',stock:'cloruro de fósforo(V)',sys:'pentacloruro de fósforo',reason:'Cinco Cl en −1 requieren P en +5.'}
];
const nameSelect=$('nameSelect');nameSelect.innerHTML=names.map((n,i)=>`<option value="${i}">${n.f}</option>`).join('');
function renderName(){const n=names[Number(nameSelect.value)||0];$('nameFormula').textContent=n.f;$('nameStock').textContent=n.stock;$('nameSystematic').textContent=n.sys;$('nameReason').textContent=n.reason}nameSelect.onchange=renderName;renderName();
let nq=0;function shuffle(a){return a.slice().sort(()=>Math.random()-.5)}
function renderNameQuiz(){const target=names[nq%names.length],pool=shuffle([target,...shuffle(names.filter(x=>x!==target)).slice(0,2)]);$('nameQuizQ').textContent=`¿Cuál es el nombre Stock de ${target.f}?`;$('nameChoices').innerHTML=pool.map((x)=>`<button data-ok="${x===target?'1':'0'}">${x.stock}</button>`).join('');$('nameFeedback').className='practiceFeedback';$('nameFeedback').textContent='Elegí una respuesta.';[...$('nameChoices').children].forEach(b=>b.onclick=()=>{const ok=b.dataset.ok==='1';$('nameFeedback').className='practiceFeedback '+(ok?'ok':'bad');$('nameFeedback').innerHTML=`<b>${ok?'✓ Correcto.':'No.'}</b> ${target.reason}`})}$('nameNext').onclick=()=>{nq++;renderNameQuiz()};renderNameQuiz();

const reactions=[
{eq:'2 H₂ + O₂ → 2 H₂O',type:'síntesis',tags:['combinación','redox'],why:'Dos reactivos forman un producto principal. También es combustión de H₂, por eso una reacción puede pertenecer a más de una categoría según el criterio.'},
{eq:'CaCO₃ → CaO + CO₂',type:'descomposición',tags:['térmica','carbonato'],why:'Un compuesto se transforma en sustancias más simples; es la descomposición térmica clásica del carbonato de calcio.'},
{eq:'Zn + 2 HCl → ZnCl₂ + H₂',type:'desplazamiento simple',tags:['redox','metal + ácido'],why:'Zn desplaza al H del ácido: Zn se oxida y H⁺ se reduce a H₂.'},
{eq:'AgNO₃ + NaCl → AgCl(s) + NaNO₃',type:'precipitación',tags:['doble desplazamiento','AgCl(s)'],why:'El intercambio iónico produce AgCl poco soluble, que precipita.'},
{eq:'HCl + NaOH → NaCl + H₂O',type:'neutralización',tags:['ácido-base','doble desplazamiento'],why:'H⁺ y OH⁻ forman agua; es una neutralización ácido-base.'},
{eq:'CH₄ + 2 O₂ → CO₂ + 2 H₂O',type:'combustión',tags:['hidrocarburo','oxidación'],why:'Combustión completa ideal de un hidrocarburo con O₂, formando CO₂ y H₂O.'},
{eq:'2 KClO₃ → 2 KCl + 3 O₂',type:'descomposición',tags:['libera O₂','balanceada'],why:'Un reactivo compuesto produce dos productos, incluido O₂.'},
{eq:'Fe + CuSO₄ → FeSO₄ + Cu',type:'desplazamiento simple',tags:['redox','metal'],why:'Fe desplaza a Cu²⁺: Fe se oxida a Fe²⁺ y Cu²⁺ se reduce a Cu.'}
];
$('reactionList').innerHTML=reactions.slice(0,6).map(r=>`<div class="reactionItem"><div class="reactionEq">${r.eq}</div><div class="reactionTags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div></div>`).join('');
let rq=0,rok=0,ratt=0;const types=['síntesis','descomposición','desplazamiento simple','precipitación','neutralización','combustión'];
function renderReactionQ(){const r=reactions[rq%reactions.length];$('reactionQ').textContent=r.eq;const choices=shuffle([r.type,...shuffle(types.filter(t=>t!==r.type)).slice(0,2)]);$('reactionChoices').innerHTML=choices.map(t=>`<button data-type="${t}">${t}</button>`).join('');$('reactionFeedback').className='practiceFeedback';$('reactionFeedback').textContent='Elegí el tipo principal usado en esta actividad.';[...$('reactionChoices').children].forEach(b=>b.onclick=()=>{ratt++;const ok=b.dataset.type===r.type;if(ok)rok++;$('reactionOK').textContent=rok;$('reactionAttempts').textContent=ratt;$('reactionFeedback').className='practiceFeedback '+(ok?'ok':'bad');$('reactionFeedback').innerHTML=`<b>${ok?'✓ Correcto.':'No para la clasificación principal elegida.'}</b> ${r.why}`})}$('reactionNext').onclick=()=>{rq++;renderReactionQ()};renderReactionQ();

// Corrección defensiva de v3: normaliza el signo menos tipográfico de PubChem antes de regenerar estados.
let periodic={};
function parseOxSafe(s,z){const normalized=String(s||'').replace(/[−–—]/g,'-').replace(/[＋]/g,'+');const vals=(normalized.match(/[+-]?\d+/g)||[]).map(Number).filter(v=>Number.isInteger(v)&&v!==0&&Math.abs(v)<=8);if(vals.length)return[...new Set(vals)];const g=(()=>{if(z===1)return 1;if(z===2)return 18;if(z>=3&&z<=10)return[1,2,13,14,15,16,17,18][z-3];if(z>=11&&z<=18)return[1,2,13,14,15,16,17,18][z-11];if(z>=19&&z<=36)return z-18;if(z>=37&&z<=54)return z-36;if(z===55||z===87)return 1;if(z===56||z===88)return 2;if(z>=72&&z<=86)return z-68;if(z>=104&&z<=118)return z-100;return null})();if(g===1)return[1];if(g===2)return[2];if(g===13)return[3];if(g===15)return[-3,3,5];if(g===16)return[-2,4,6];if(g===17)return[-1,1,3,5,7];return[]}
function fixV3Charges(which){const esel=$(`formula${which}`),csel=$(`charge${which}`);if(!esel||!csel)return;const z=Number(esel.value),vals=parseOxSafe(periodic[z]?.OxidationStates,z);if(!vals.length)return;csel.innerHTML=vals.map(v=>`<option value="${v}">${v>0?'+':''}${v}</option>`).join('');const preferred=which==='A'?vals.find(v=>v>0):vals.find(v=>v<0);if(preferred!==undefined)csel.value=String(preferred);csel.dispatchEvent(new Event('change',{bubbles:true}))}
async function loadPeriodicFix(){try{const r=await fetch('https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON');if(!r.ok)return;const j=await r.json(),cols=j.Table.Columns.Column;for(const rr of j.Table.Row){const o={};rr.Cell.forEach((v,i)=>o[cols[i]]=v);periodic[Number(o.AtomicNumber)]=o}['A','B'].forEach(fixV3Charges);['formulaA','formulaB'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(()=>fixV3Charges(id.endsWith('A')?'A':'B'),0)))}catch(e){console.warn('No se pudo aplicar normalización v4 de estados de oxidación',e)}}loadPeriodicFix();
})();