(()=>{
const $=id=>document.getElementById(id);
const symbols=['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'];
const names=['Hidrógeno','Helio','Litio','Berilio','Boro','Carbono','Nitrógeno','Oxígeno','Flúor','Neón','Sodio','Magnesio','Aluminio','Silicio','Fósforo','Azufre','Cloro','Argón','Potasio','Calcio','Escandio','Titanio','Vanadio','Cromo','Manganeso','Hierro','Cobalto','Níquel','Cobre','Zinc','Galio','Germanio','Arsénico','Selenio','Bromo','Kriptón','Rubidio','Estroncio','Itrio','Circonio','Niobio','Molibdeno','Tecnecio','Rutenio','Rodio','Paladio','Plata','Cadmio','Indio','Estaño','Antimonio','Telurio','Yodo','Xenón','Cesio','Bario','Lantano','Cerio','Praseodimio','Neodimio','Prometio','Samario','Europio','Gadolinio','Terbio','Disprosio','Holmio','Erbio','Tulio','Iterbio','Lutecio','Hafnio','Tantalio','Wolframio','Renio','Osmio','Iridio','Platino','Oro','Mercurio','Talio','Plomo','Bismuto','Polonio','Astato','Radón','Francio','Radio','Actinio','Torio','Protactinio','Uranio','Neptunio','Plutonio','Americio','Curio','Berkelio','Californio','Einsteinio','Fermio','Mendelevio','Nobelio','Lawrencio','Rutherfordio','Dubnio','Seaborgio','Bohrio','Hassio','Meitnerio','Darmstadtio','Roentgenio','Copernicio','Nihonio','Flerovio','Moscovio','Livermorio','Teneso','Oganesón'];
const elements=symbols.map((s,i)=>({z:i+1,symbol:s,name:names[i]}));
const pos={}; const set=(z,p,g)=>pos[z]={period:p,group:g};
[[1,1],[2,18]].forEach(([z,g])=>set(z,1,g));
[[3,1],[4,2],[5,13],[6,14],[7,15],[8,16],[9,17],[10,18]].forEach(([z,g])=>set(z,2,g));
[[11,1],[12,2],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18]].forEach(([z,g])=>set(z,3,g));
for(let z=19;z<=36;z++)set(z,4,z-18); for(let z=37;z<=54;z++)set(z,5,z-36);
set(55,6,1);set(56,6,2);for(let z=72;z<=86;z++)set(z,6,z-68);
set(87,7,1);set(88,7,2);for(let z=104;z<=118;z++)set(z,7,z-100);
for(let z=57;z<=71;z++)pos[z]={period:6,group:null,f:1,fcol:z-56};for(let z=89;z<=103;z++)pos[z]={period:7,group:null,f:2,fcol:z-88};
elements.forEach(e=>Object.assign(e,pos[e.z]||{}));
const groupInfo={
1:{title:'Grupo 1 · alcalinos + H',text:'Los metales alcalinos tienen configuración externa ns¹ y suelen formar +1. El hidrógeno ocupa la misma columna por su electrón 1s¹, pero su química es singular.'},
2:{title:'Grupo 2 · alcalinotérreos',text:'Configuración externa ns². Suelen formar cationes +2 y, en general, son menos reactivos que los alcalinos del mismo período.'},
3:{title:'Grupo 3',text:'Zona de transición entre bloque s y d. El tratamiento de La/Lu en este grupo puede variar según la representación de la tabla.'},
4:{title:'Grupo 4',text:'Metales de transición como Ti, Zr y Hf. Suelen mostrar alta resistencia mecánica y estados de oxidación +4 frecuentes.'},
5:{title:'Grupo 5',text:'V, Nb y Ta son metales de transición con varios estados de oxidación; +5 es especialmente importante.'},
6:{title:'Grupo 6',text:'Cr, Mo y W muestran química redox rica. Cr(VI) y compuestos de Mo/W aparecen en contextos industriales y catalíticos.'},
7:{title:'Grupo 7',text:'Mn, Tc y Re. El manganeso destaca por muchos estados de oxidación y una química redox particularmente amplia.'},
8:{title:'Grupo 8',text:'Fe, Ru y Os. El hierro domina aplicaciones biológicas, metalúrgicas y redox.'},
9:{title:'Grupo 9',text:'Co, Rh e Ir. Metales de transición asociados con catálisis y múltiples estados de oxidación.'},
10:{title:'Grupo 10',text:'Ni, Pd y Pt. Importantes en catálisis, aleaciones y electroquímica.'},
11:{title:'Grupo 11 · metales de acuñación',text:'Cu, Ag y Au presentan buena conductividad y química característica de estados +1 y +2 según el elemento.'},
12:{title:'Grupo 12',text:'Zn, Cd y Hg. El zinc es esencial en bioquímica; Cd y Hg requieren especial atención toxicológica.'},
13:{title:'Grupo 13 · familia del boro',text:'Configuración externa ns²np¹. El estado +3 es frecuente; aumenta el carácter metálico al descender.'},
14:{title:'Grupo 14 · familia del carbono',text:'Configuración ns²np². Incluye desde C no metálico hasta Pb metálico; +4 y +2 son estados importantes.'},
15:{title:'Grupo 15 · pnictógenos',text:'Configuración ns²np³. Estados −3, +3 y +5 aparecen con frecuencia, con gran variedad estructural.'},
16:{title:'Grupo 16 · calcógenos',text:'Configuración ns²np⁴. Oxígeno y azufre son centrales en química inorgánica, orgánica, ambiental y biológica.'},
17:{title:'Grupo 17 · halógenos',text:'Configuración ns²np⁵. Alta tendencia a captar un electrón; el estado −1 es muy común y la reactividad cambia marcadamente al bajar.'},
18:{title:'Grupo 18 · gases nobles',text:'Capas de valencia completas en condiciones ordinarias. Presentan baja reactividad, aunque existen compuestos de algunos elementos pesados del grupo.'}
};
const periodInfo={
1:'Solo H y He. Corresponde al llenado del nivel n=1.',2:'Se incorporan los subniveles 2s y 2p; aparecen metales, metaloides y no metales con cambios marcados de izquierda a derecha.',3:'Llenado 3s y 3p. Permite ver muy bien el descenso del carácter metálico de Na/Mg hacia Cl/Ar.',4:'Primer período que incorpora el bloque d: aparecen los metales de transición 3d.',5:'Análogo al período 4 con la serie 4d, incluyendo Ag, Cd, Sn, I y Xe.',6:'Incluye 6s, lantánidos 4f, serie 5d y 6p. Es uno de los períodos más extensos.',7:'Incluye actínidos y elementos superpesados; muchos son radiactivos y varios solo se producen artificialmente.'};
const contexts={1:'Clave en ácidos, enlaces O–H/N–H y procesos energéticos.',6:'Base estructural de la química orgánica; forma redes, cadenas y múltiples enlaces.',7:'Central en aminoácidos, bases nitrogenadas, fertilizantes y química redox.',8:'Oxidante fundamental y componente del agua y de innumerables funciones orgánicas.',11:'Importante en equilibrio osmótico, sales, bases y química de metales alcalinos.',12:'Presente en clorofila, aleaciones y numerosas sales inorgánicas.',13:'Metal liviano de enorme uso industrial; su óxido superficial explica buena parte de su resistencia.',14:'Base de semiconductores y silicatos; conecta química, materiales y geología.',15:'Esencial en ATP, ácidos nucleicos y fosfatos.',16:'Aparece en sulfuros, sulfatos, aminoácidos azufrados y procesos industriales.',17:'Halógeno muy usado en desinfección y química de cloruros.',19:'Catión biológico clave y ejemplo clásico de metal alcalino.',20:'Importante en huesos, carbonatos, cemento y señalización biológica.',26:'Esencial en metalurgia y en proteínas como hemoglobina; su química Fe²⁺/Fe³⁺ es redox clásica.',29:'Excelente conductor y metal de transición con química Cu⁺/Cu²⁺ relevante.',30:'Elemento esencial y frecuente en enzimas, galvanizado y aleaciones.',35:'Único no metal líquido a temperatura ambiente ordinaria.',47:'Metal conductor y fotosensible en algunos compuestos; relevante en materiales.',53:'Halógeno importante en función tiroidea y química analítica.',79:'Metal noble, conductor y resistente a corrosión; química y aplicaciones de alto valor.',80:'Metal líquido a temperatura ambiente; tóxico, con química ambiental importante.',82:'Metal pesado de alta densidad; su toxicidad es relevante en salud ambiental.',92:'Actínido radiactivo con importancia en química nuclear y energía.'};
let dataByZ={},compareMode=false,compare=[],quiz=null;
const propMeta={electronegativity:['Electronegatividad','Pauling'],atomicRadius:['Radio atómico','pm'],ionizationEnergy:['Energía de ionización','eV'],electronAffinity:['Afinidad electrónica','eV'],meltingPoint:['Punto de fusión','K'],boilingPoint:['Punto de ebullición','K'],density:['Densidad','g/cm³'],year:['Año de descubrimiento','']};
function classify(groupBlock=''){const s=groupBlock.toLowerCase();if(s.includes('noble'))return'noble';if(s.includes('alkali metal'))return'alkali';if(s.includes('alkaline'))return'alkaline';if(s.includes('halogen'))return'halogen';if(s.includes('metalloid'))return'metalloid';if(s.includes('post-transition'))return'post';if(s.includes('transition'))return'transition';if(s.includes('lanthanide'))return'lanthanide';if(s.includes('actinide'))return'actinide';if(s.includes('nonmetal'))return'nonmetal';return'unknown'}
function fallbackClass(e){if(e.z>=57&&e.z<=71)return'lanthanide';if(e.z>=89&&e.z<=103)return'actinide';if([2,10,18,36,54,86,118].includes(e.z))return'noble';if([9,17,35,53,85,117].includes(e.z))return'halogen';if([3,11,19,37,55,87].includes(e.z))return'alkali';if([4,12,20,38,56,88].includes(e.z))return'alkaline';if([5,14,32,33,51,52].includes(e.z))return'metalloid';if([1,6,7,8,15,16,34].includes(e.z))return'nonmetal';if((e.group>=3&&e.group<=12))return'transition';return'post'}
function familyName(c){return({nonmetal:'No metal',noble:'Gas noble',alkali:'Metal alcalino',alkaline:'Alcalinotérreo',halogen:'Halógeno',metalloid:'Metaloide',post:'Metal post-transición',transition:'Metal de transición',lanthanide:'Lantánido',actinide:'Actínido',unknown:'Sin clasificar'})[c]||c}
function fmt(v,unit=''){if(v===undefined||v===null||v==='')return'—';return`${v}${unit?' '+unit:''}`}
function valueOf(e,key){const d=dataByZ[e.z]||{};return key==='year'?(d.YearDiscovered==='Ancient'?null:Number(d.YearDiscovered)):Number(d[{electronegativity:'Electronegativity',atomicRadius:'AtomicRadius',ionizationEnergy:'IonizationEnergy',electronAffinity:'ElectronAffinity',meltingPoint:'MeltingPoint',boilingPoint:'BoilingPoint',density:'Density'}[key]])}
function currentClass(e){return classify(dataByZ[e.z]?.GroupBlock)||fallbackClass(e)}
function renderHeads(){const grid=$('periodicGrid');grid.innerHTML='<div class="corner"></div>';for(let g=1;g<=18;g++){const b=document.createElement('button');b.className='groupHead';b.style.gridColumn=g+1;b.textContent=g;b.title=`Explorar grupo ${g}`;b.onclick=()=>showGroup(g);grid.appendChild(b)}for(let p=1;p<=7;p++){const b=document.createElement('button');b.className='periodHead';b.style.gridRow=p+1;b.textContent=p;b.title=`Explorar período ${p}`;b.onclick=()=>showPeriod(p);grid.appendChild(b)}grid.insertAdjacentHTML('beforeend','<div class="placeholder" style="grid-column:4;grid-row:7">57–71<br>lantánidos</div><div class="placeholder" style="grid-column:4;grid-row:8">89–103<br>actínidos</div>')}
function colorForValue(v,min,max){if(!Number.isFinite(v))return'#edf1f6';const t=(v-min)/(max-min||1),h=215-(t*175);return`hsl(${h} 78% 82%)`}
function renderTable(){renderHeads();const grid=$('periodicGrid'),f=$('fBlock');f.innerHTML='';const mode=$('property').value;let vals=[];if(mode!=='family')vals=elements.map(e=>valueOf(e,mode)).filter(Number.isFinite);const min=Math.min(...vals),max=Math.max(...vals);const q=$('search').value.trim().toLowerCase(),filter=$('filter').value;elements.forEach(e=>{const d=dataByZ[e.z]||{},c=currentClass(e),btn=document.createElement('button');btn.className=`element family-${c}`;btn.dataset.z=e.z;const val=mode==='family'?familyName(c):valueOf(e,mode);btn.innerHTML=`<span class="z">${e.z}</span><span class="symbol">${e.symbol}</span><span class="name">${e.name}</span><span class="value">${mode==='family'?'':Number.isFinite(val)?val:'—'}</span>`;if(mode!=='family')btn.style.background=colorForValue(val,min,max);const hay=`${e.z} ${e.symbol} ${e.name}`.toLowerCase();if(q&&hay.includes(q))btn.classList.add('match');let pass=true;if(filter==='metal')pass=['alkali','alkaline','transition','post','lanthanide','actinide'].includes(c);if(filter==='nonmetal')pass=['nonmetal','noble','halogen'].includes(c);if(filter==='metalloid')pass=c==='metalloid';if(['gas','solid','liquid'].includes(filter))pass=(d.StandardState||'').toLowerCase()===filter;if(!pass)btn.classList.add('dim');if(compare.includes(e.z))btn.classList.add('selected');btn.onclick=()=>compareMode?toggleCompare(e.z):showElement(e.z);if(e.f){btn.style.gridColumn=e.fcol;btn.style.gridRow=e.f;f.appendChild(btn)}else{btn.style.gridColumn=e.group+1;btn.style.gridRow=e.period+1;grid.appendChild(btn)}});renderLegend(mode,min,max)}
function renderLegend(mode,min,max){const el=$('legend');if(mode==='family'){const items=['alkali','alkaline','transition','post','metalloid','nonmetal','halogen','noble','lanthanide','actinide'];el.innerHTML=items.map(c=>`<span class="legendItem"><i class="dot family-${c}"></i>${familyName(c)}</span>`).join('');$('trendTitle').textContent='Familias químicas';$('trendText').textContent='Los colores agrupan comportamientos relacionados. Tocá encabezados de grupo o período para leer la lógica química de cada zona.'}else{const [label,unit]=propMeta[mode];el.innerHTML=`<span class="legendItem">menor</span><span style="width:150px;height:12px;border-radius:8px;background:linear-gradient(90deg,hsl(215 78% 82%),hsl(40 78% 82%))"></span><span class="legendItem">mayor</span>`;$('trendTitle').textContent=label;$('trendText').textContent=`Mapa relativo según los datos disponibles${unit?` (${unit})`:''}. Las celdas sin valor quedan neutras; buscá patrones y también excepciones.`}}
function showElement(z){const e=elements[z-1],d=dataByZ[z]||{},c=currentClass(e),gi=e.group?groupInfo[e.group]:null;const p=$('selectionPanel');p.innerHTML=`<span class="ey">Elemento ${z}</span><div class="elementHero"><div class="bigElement family-${c}"><b>${e.symbol}</b><span>${e.name}</span></div><div><h2>${e.name}</h2><p>${familyName(c)} · período ${e.period}${e.group?` · grupo ${e.group}`:' · bloque f'}</p><p>${contexts[z]||`Su posición permite relacionarlo con las tendencias del período ${e.period}${e.group?` y del grupo ${e.group}`:''}.`}</p></div></div><div class="propertyGrid">${prop('Masa atómica',d.AtomicMass,'u')}${prop('Configuración electrónica',d.ElectronConfiguration)}${prop('Estados de oxidación',d.OxidationStates)}${prop('Electronegatividad',d.Electronegativity,'Pauling')}${prop('Radio atómico',d.AtomicRadius,'pm')}${prop('1ª ionización',d.IonizationEnergy,'eV')}${prop('Afinidad electrónica',d.ElectronAffinity,'eV')}${prop('Estado estándar',d.StandardState)}${prop('Densidad',d.Density,'g/cm³')}${prop('Fusión',d.MeltingPoint,'K')}${prop('Ebullición',d.BoilingPoint,'K')}${prop('Descubierto',d.YearDiscovered)}</div><div class="studyBox"><b>Qué conviene mirar al estudiar ${e.name}</b><span>${gi?gi.text:'Compará su configuración electrónica, estados de oxidación y vecinos inmediatos para interpretar su comportamiento.'}</span></div>`;p.scrollIntoView({behavior:'smooth',block:'nearest'})}
function prop(label,v,u=''){return`<div class="prop"><small>${label}</small><b>${fmt(v,u)}</b></div>`}
function showGroup(g){const info=groupInfo[g],members=elements.filter(e=>e.group===g);$('selectionPanel').innerHTML=`<span class="ey">Grupo ${g}</span><h2>${info.title}</h2><p>${info.text}</p><div class="studyBox"><b>Elementos del grupo</b><span>${members.map(e=>`${e.symbol} · ${e.name}`).join(' · ')}</span></div><div class="studyBox"><b>Cómo estudiarlo</b><span>Compará radio atómico, energía de ionización, electronegatividad y estados de oxidación de arriba hacia abajo. Buscá la tendencia general y después las excepciones.</span></div>`;highlightSet(new Set(members.map(e=>e.z)))}
function showPeriod(pn){const members=elements.filter(e=>e.period===pn);$('selectionPanel').innerHTML=`<span class="ey">Período ${pn}</span><h2>Fila ${pn}</h2><p>${periodInfo[pn]}</p><div class="studyBox"><b>Lectura útil</b><span>Recorré de izquierda a derecha y observá cómo cambian carácter metálico, radio, energía de ionización y electronegatividad. Los elementos del bloque f se muestran en la serie separada.</span></div>`;highlightSet(new Set(members.map(e=>e.z)))}
function highlightSet(set){document.querySelectorAll('.element').forEach(el=>el.classList.toggle('match',set.has(Number(el.dataset.z))))}
function toggleCompare(z){if(compare.includes(z))compare=compare.filter(x=>x!==z);else if(compare.length<3)compare.push(z);else compare=[compare[1],compare[2],z];renderTable();renderCompare()}
function renderCompare(){const panel=$('comparePanel');panel.classList.remove('hidden');if(!compare.length){$('compareContent').innerHTML='<p class="muted">Elegí hasta tres elementos desde la tabla.</p>';return}const es=compare.map(z=>elements[z-1]);const rows=[['Número atómico',e=>e.z],['Familia',e=>familyName(currentClass(e))],['Período / grupo',e=>`${e.period} / ${e.group||'f'}`],['Masa atómica',e=>fmt(dataByZ[e.z]?.AtomicMass,'u')],['Configuración',e=>fmt(dataByZ[e.z]?.ElectronConfiguration)],['Electronegatividad',e=>fmt(dataByZ[e.z]?.Electronegativity)],['Radio atómico',e=>fmt(dataByZ[e.z]?.AtomicRadius,'pm')],['Ionización',e=>fmt(dataByZ[e.z]?.IonizationEnergy,'eV')],['Oxidación',e=>fmt(dataByZ[e.z]?.OxidationStates)],['Estado',e=>fmt(dataByZ[e.z]?.StandardState)]];$('compareContent').innerHTML=`<table class="compareTable"><thead><tr><th>Propiedad</th>${es.map(e=>`<th>${e.symbol} · ${e.name}</th>`).join('')}</tr></thead><tbody>${rows.map(([l,f])=>`<tr><td>${l}</td>${es.map(e=>`<td>${f(e)}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="studyBox"><b>Interpretación</b><span>${comparisonInsight(es)}</span></div>`}
function comparisonInsight(es){if(es.length<2)return'Agregá otro elemento para buscar semejanzas y diferencias.';const sameGroup=es.every(e=>e.group&&e.group===es[0].group),samePeriod=es.every(e=>e.period===es[0].period);if(sameGroup)return`Están en el mismo grupo ${es[0].group}: compará cómo cambian tamaño, ionización y reactividad al bajar.`;if(samePeriod)return`Están en el mismo período ${es[0].period}: seguí el cambio de carácter metálico y propiedades hacia la derecha.`;return'Pertenecen a posiciones diferentes: usá configuración electrónica, familia y tendencias para explicar por qué sus propiedades cambian.'}
function buildChips(){for(let g=1;g<=18;g++){const b=document.createElement('button');b.textContent=`Grupo ${g}`;b.onclick=()=>showGroup(g);$('groupChips').appendChild(b)}for(let p=1;p<=7;p++){const b=document.createElement('button');b.textContent=`Período ${p}`;b.onclick=()=>showPeriod(p);$('periodChips').appendChild(b)}}
function random(arr){return arr[Math.floor(Math.random()*arr.length)]}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function makeQuestion(){const e=random(elements),types=['symbol','z','name'];if(Object.keys(dataByZ).length>100)types.push('family');const type=random(types);if(type==='symbol')return{q:`¿Qué elemento corresponde al símbolo ${e.symbol}?`,a:e.name,opts:shuffle([e.name,...shuffle(elements.filter(x=>x.z!==e.z)).slice(0,3).map(x=>x.name)])};if(type==='z')return{q:`¿Cuál es el símbolo del elemento con número atómico ${e.z}?`,a:e.symbol,opts:shuffle([e.symbol,...shuffle(elements.filter(x=>x.z!==e.z)).slice(0,3).map(x=>x.symbol)])};if(type==='name')return{q:`¿Cuál es el número atómico de ${e.name}?`,a:String(e.z),opts:shuffle([String(e.z),...shuffle(elements.filter(x=>x.z!==e.z)).slice(0,3).map(x=>String(x.z))])};const fam=familyName(currentClass(e)),alts=shuffle(['Metal alcalino','Alcalinotérreo','Metal de transición','Halógeno','Gas noble','Metaloide','No metal','Lantánido','Actínido','Metal post-transición'].filter(x=>x!==fam)).slice(0,3);return{q:`${e.symbol} (${e.name}) pertenece principalmente a…`,a:fam,opts:shuffle([fam,...alts])}}
function startQuiz(){quiz={i:0,score:0,total:8,answered:false};nextQuestion();$('quiz').scrollIntoView({behavior:'smooth',block:'start'})}
function nextQuestion(){if(quiz.i>=quiz.total){$('quizQuestion').textContent=`Ronda terminada: ${quiz.score}/${quiz.total}`;$('quizProgress').textContent='Completado';$('quizOptions').innerHTML='';$('quizFeedback').textContent=quiz.score>=6?'Muy buen manejo. Probá otra ronda o explorá las preguntas que fallaste.':'Conviene volver a explorar grupos, períodos y símbolos antes de repetir.';return}quiz.current=makeQuestion();quiz.answered=false;$('quizProgress').textContent=`Pregunta ${quiz.i+1} de ${quiz.total}`;$('quizScore').textContent=`${quiz.score} puntos`;$('quizQuestion').textContent=quiz.current.q;$('quizFeedback').textContent='';$('quizOptions').innerHTML='';quiz.current.opts.forEach(o=>{const b=document.createElement('button');b.textContent=o;b.onclick=()=>answerQuiz(o,b);$('quizOptions').appendChild(b)})}
function answerQuiz(o,b){if(quiz.answered)return;quiz.answered=true;const ok=o===quiz.current.a;if(ok){quiz.score++;b.classList.add('correct');$('quizFeedback').textContent='✓ Correcto.'}else{b.classList.add('wrong');[...$('quizOptions').children].find(x=>x.textContent===quiz.current.a)?.classList.add('correct');$('quizFeedback').textContent=`La respuesta correcta es ${quiz.current.a}.`}$('quizScore').textContent=`${quiz.score} puntos`;setTimeout(()=>{quiz.i++;nextQuestion()},700)}
async function loadData(){try{const r=await fetch('https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json(),cols=j.Table.Columns.Column;for(const row of j.Table.Row){const o={};row.Cell.forEach((v,i)=>o[cols[i]]=v);dataByZ[Number(o.AtomicNumber)]=o}$('dataStatus').textContent='Datos atómicos cargados · PubChem';renderTable()}catch(e){console.error(e);$('dataStatus').textContent='Modo local: estructura disponible; datos avanzados no cargaron';renderTable()}}
$('property').onchange=renderTable;$('filter').onchange=renderTable;$('search').oninput=renderTable;$('compareToggle').onclick=()=>{compareMode=!compareMode;$('compareToggle').classList.toggle('active',compareMode);$('compareToggle').textContent=compareMode?'✓ Comparación activa':'⇄ Comparar elementos';if(compareMode)$('comparePanel').classList.remove('hidden')};$('clearCompare').onclick=()=>{compare=[];renderTable();renderCompare()};$('startQuiz').onclick=startQuiz;$('startQuizHero').onclick=startQuiz;$('jumpTable').onclick=()=>document.getElementById('explorar').scrollIntoView({behavior:'smooth'});
buildChips();renderTable();loadData();
})();