const SUPA='https://abcuvgoipnwiltlbcqxa.supabase.co';const KEY='sb_publishable_qCFyX0zIAgDPIiWQxAIb0g_cFiK21fM';let token=sessionStorage.getItem('mente_mod_token')||'';let currentFilter='pending';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function rpc(name,body){const r=await fetch(SUPA+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!r.ok)throw new Error(await r.text());return r.json()}
async function login(email,password){const r=await fetch(SUPA+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('login_failed');return r.json()}
function showPanel(){if(token){$('#loginBox').hidden=true;$('#moderationBox').hidden=false;loadQueue()}else{$('#loginBox').hidden=false;$('#moderationBox').hidden=true}}
$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const st=$('#loginStatus');st.textContent='Ingresando…';st.className='formStatus';try{const d=await login($('#loginEmail').value.trim(),$('#loginPassword').value);token=d.access_token;sessionStorage.setItem('mente_mod_token',token);$('#loginPassword').value='';st.textContent='';showPanel()}catch{st.textContent='No pudimos iniciar sesión o la cuenta no tiene acceso.';st.className='formStatus err'}});
$('#logoutBtn')?.addEventListener('click',()=>{token='';sessionStorage.removeItem('mente_mod_token');showPanel()});$('#refreshQueue')?.addEventListener('click',()=>loadQueue());
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));loadQueue()}));
function storyCard(x){const canPublish=x.publish_consent===true;return '<article class="moderationStory" data-id="'+esc(x.story_id)+'"><div class="storyMeta"><span class="modBadge">'+esc(x.status)+'</span><span class="modBadge '+(canPublish?'yes':'no')+'">'+(canPublish?'Autorizó publicación':'No autorizó publicación')+'</span><span class="modBadge">'+new Date(x.created_at).toLocaleString('es-AR')+'</span></div><div class="rawStory">'+esc(x.story_text||'(texto ya no disponible)')+'</div><label>Texto que se publicaría<textarea class="publishText" '+(canPublish?'':'disabled')+'>'+esc(x.published_text||x.story_text||'')+'</textarea></label><label>Nota interna opcional<input class="modNotes" value="'+esc(x.moderator_notes||'')+'"></label><div class="moderationActions"><button class="approveBtn" data-action="publish" '+(canPublish?'':'disabled')+'>Publicar en el muro</button><button class="privateBtn" data-action="private">Dejar privado</button><button class="rejectBtn" data-action="reject">Rechazar</button><button class="deleteBtn" data-action="delete">Eliminar</button></div><div class="formStatus itemStatus"></div></article>'}
async function loadQueue(){const box=$('#storyQueue'),status=$('#queueStatus');if(!box)return;status.textContent='Cargando…';try{const rows=await rpc('get_mental_health_moderation_queue',{status_filter:currentFilter,result_limit:100});status.textContent='';box.innerHTML=rows.length?rows.map(storyCard).join(''):'<div class="queueEmpty">No hay relatos en esta categoría.</div>';bindActions()}catch(e){token='';sessionStorage.removeItem('mente_mod_token');status.textContent='La sesión venció o esta cuenta no tiene permisos de moderación.';status.className='formStatus err';showPanel()}}
function bindActions(){$$('#storyQueue [data-action]').forEach(btn=>btn.addEventListener('click',async()=>{const card=btn.closest('.moderationStory'),id=card.dataset.id,action=btn.dataset.action,st=card.querySelector('.itemStatus');if(action==='delete'&&!confirm('¿Eliminar definitivamente este relato?'))return;if(action==='publish'&&!confirm('¿Publicar este texto de forma anónima en el muro?'))return;st.textContent='Guardando…';st.className='formStatus';card.querySelectorAll('button').forEach(b=>b.disabled=true);try{await rpc('moderate_mental_health_story',{story_id_input:id,action_input:action,published_text_input:card.querySelector('.publishText')?.value||null,moderator_notes_input:card.querySelector('.modNotes')?.value||null});st.textContent='Listo.';st.className='formStatus ok';setTimeout(loadQueue,450)}catch(e){st.textContent='No se pudo guardar el cambio.';st.className='formStatus err';card.querySelectorAll('button').forEach(b=>{if(!(b.dataset.action==='publish'&&card.querySelector('.publishText')?.disabled))b.disabled=false})}}))}
showPanel();